-- Batch 2 (verses 101-150)
INSERT INTO "Verse" (id,"chapterId",number,"globalNumber",slug,sanskrit,transliteration,"wordByWord",translation,"translationAuthor",commentary,"commentaryAuthor","createdAt","updatedAt")
VALUES
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',54,101,'2-54','अर्जुन उवाच

स्थितप्रज्ञस्य का भाषा समाधिस्थस्य केशव।

स्थितधीः किं प्रभाषेत किमासीत व्रजेत किम्।।2.54।।','arjuna uvācha
sthita-prajñasya kā bhāṣhā samādhi-sthasya keśhava
sthita-dhīḥ kiṁ prabhāṣheta kim āsīta vrajeta kim',to_json('arjunaḥ uvācha—Arjun said; sthita-prajñasya—one with steady intellect; kā—what; bhāṣhā—talk; samādhi-sthasya—situated in divine consciousness; keśhava—Shree Krishna, killer of the Keshi Demon; sthita-dhīḥ—enlightened person; kim—what; prabhāṣheta—talks; kim—how; āsīta—sits; vrajeta—walks; kim—how'::text),'Arjuna said, "O Krishna, what is the description of one who has steady wisdom and is merged in the superconscious state? How does one of steady wisdom speak, how do they sit, and how do they walk?"','Swami Sivananda','2.54 स्थितप्रज्ञस्य of the (sage of) steady wisdom? का what? भाषा description? समाधिस्थस्य of the (man) merged in the superconscious state? केशव O Kesava? स्थितधीः the sage of steady wisdom? किम् what (how)? प्रभाषेत speaks? किम् what (how)? आसीत sits? व्रजेत walks? किम् what (how).Commentary Arjuna wants to know from Lord Krishna the characteristic marks of one who is established in the Self in Samadhi how he speaks? how he sits? how he moves about.The characteristic marks of the sage of steady wisdom and the means of attaining that steady knowledge of the Self are described in the verses from 55 to 72 of this chapter.Steady wisdom is settled knowledge of ones identity with Brahman attained by direct realisation. (Cf.XIV.21? 27).','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',55,102,'2-55','श्री भगवानुवाच

प्रजहाति यदा कामान् सर्वान् पार्थ मनोगतान्।

आत्मन्येवात्मना तुष्टः स्थितप्रज्ञस्तदोच्यते।।2.55।।','śhrī bhagavān uvācha
prajahāti yadā kāmān sarvān pārtha mano-gatān
ātmany-evātmanā tuṣhṭaḥ sthita-prajñas tadochyate',to_json('śhrī-bhagavān uvācha—The Supreme Lord said; prajahāti—discards; yadā—when; kāmān—selfish desires; sarvān—all; pārtha—Arjun, the son of Pritha; manaḥ-gatān—of the mind; ātmani—of the self; eva—only; ātmanā—by the purified mind; tuṣhṭaḥ—satisfied; sthita-prajñaḥ—one with steady intellect; tadā—at that time; uchyate—is said'::text),'The Blessed Lord said, "When a man completely casts off, O Arjuna, all the desires of the mind and is satisfied in the Self by the Self, then he is said to be one of steady wisdom."','Swami Sivananda','2.55 प्रजहाति casts off? यदा when? कामान् desires? सर्वान् all? पार्थ O Partha? मनोगतान् of the mind? आत्मनि in the Self? एव only? आत्मना by the Self? तुष्टः satisfied? स्थितप्रज्ञः of steady wisdom? तदा then? उच्यते (he) is called.Commentary In this verse Lord Krishna gives His answer to the first part of Arjunas estion.If anyone gets sugarcandy will he crave for blacksugar Certainly not. If anyone can attain the supreme bliss of the Self? will he thirst for the sensual pleasures No? not at all. The sumtotal of all the pleasures of the world will seem worthless for the sage of steady wisdom who is satisfied in the Self. (Cf.III.17VI.7?8).','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',56,103,'2-56','दुःखेष्वनुद्विग्नमनाः सुखेषु विगतस्पृहः।

वीतरागभयक्रोधः स्थितधीर्मुनिरुच्यते।।2.56।।','duḥkheṣhv-anudvigna-manāḥ sukheṣhu vigata-spṛihaḥ
vīta-rāga-bhaya-krodhaḥ sthita-dhīr munir uchyate',to_json('duḥkheṣhu—amidst miseries; anudvigna-manāḥ—one whose mind is undisturbed; sukheṣhu—in pleasure; vigata-spṛihaḥ—without craving; vīta—free from; rāga—attachment; bhaya—fear; krodhaḥ—anger; sthita-dhīḥ—enlightened person; muniḥ—a sage; uchyate—is called'::text),'He whose mind is not shaken by adversity, who does not long for pleasures, and is free from attachment, fear, and anger, is called a sage of steady wisdom.','Swami Sivananda','2.56 दुःखेषु in adversity? अनुद्विग्नमनाः of unshaken mind? सुखेषु in pleasure? विगतस्पृहः withut hankering? वीतरागभयक्रोधः free from attachment? fear and anger? स्थितधीः of steady wisdom? मुनिः sage? उच्यते (he) is called.Commentary Lord Krishna gives His answer to the second part of Arjunas estion as to the conduct of a sage of steady wisdom in the 56th? 57th and 58th verses.The mind of a sage of steady wisdom is not distressed in calamities. He is not affected by the three afflictions (Taapas) -- Adhyatmika (arising from diseases or disorders in ones own body)? Adhidaivika (arising from thunder? lightning? storm? flood? etc.)? and Adhibhautika (arising from scorpions? cobras? tigers? etc.). When he is placed in an affluent condition he does not long for sensual pleasures. (Cf.IV.10).','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',57,104,'2-57','यः सर्वत्रानभिस्नेहस्तत्तत्प्राप्य शुभाशुभम्।

नाभिनन्दति न द्वेष्टि तस्य प्रज्ञा प्रतिष्ठिता।।2.57।।','yaḥ sarvatrānabhisnehas tat tat prāpya śhubhāśhubham
nābhinandati na dveṣhṭi tasya prajñā pratiṣhṭhitā',to_json('yaḥ—who; sarvatra—in all conditions; anabhisnehaḥ—unattached; tat—that; tat—that; prāpya—attaining; śhubha—good; aśhubham—evil; na—neither; abhinandati—delight in; na—nor; dveṣhṭi—dejected by; tasya—his; prajñā—knowledge; pratiṣhṭhitā—is fixed'::text),'He who is everywhere without attachment, upon encountering anything good or bad, neither rejoices nor hastens; his wisdom is firm.','Swami Sivananda','2.57 यः he who? सर्वत्र everywhere? अनभिस्नेहः without attachment? तत् that? तत् that? प्राप्य having obtained? शुभाशुभम् good and evil? न not? अभिनन्दति rejoices? न not? द्वेष्टि hates? तस्य of him? प्रज्ञा wisdom? प्रतिष्ठिता is fixed.Commentary The sage possesses poised understanding or evenness of mind. He does not rejoice in pleasure nor is he averse to pain that may befall him. He is ite indifferent as he is rooted in the Self. He has no attachment even for his life or body as he identifies himself with Brahman or the Supreme Self. He will not praise anybody when the latter does any good to him nor censure anyone when one does him any harm. This is the answer given by the Lord to Arjunas ery How does a sage of steady wisdom talk','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',58,105,'2-58','यदा संहरते चायं कूर्मोऽङ्गानीव सर्वशः।

इन्द्रियाणीन्द्रियार्थेभ्यस्तस्य प्रज्ञा प्रतिष्ठिता।।2.58।।','yadā sanharate chāyaṁ kūrmo ’ṅgānīva sarvaśhaḥ
indriyāṇīndriyārthebhyas tasya prajñā pratiṣhṭhitā',to_json('yadā—when; sanharate—withdraw; cha—and; ayam—this; kūrmaḥ—tortoise; aṅgāni—limbs; iva—as; sarvaśhaḥ—fully; indriyāṇi—senses; indriya-arthebhyaḥ—from the sense objects; tasya—his; prajñā—divine wisdom; pratiṣhṭhitā—fixed in'::text),'When, like the tortoise which withdraws all its limbs on all sides, he withdraws his senses from the sense-objects, then his wisdom becomes steady.','Swami Sivananda','2.58 यदा when? संहरते withdraws? च and? अयम् this (Yogi)? कूर्मः tortoise? अङ्गानि limbs? इव like? सर्वशः everywhere? इन्द्रियाणि the senses? इन्द्रियार्थेभ्यः from the senseobjects? तस्य of him? प्रज्ञा wisdom प्रतिष्ठिता is steadied.Commentary Withdrawal of the senses is Pratyahara or abstraction. The mind has a natural,tendency to run towards external objects. The Yogi again and again withdraws the mind from the objects of the senses and fixes it on the Self. A Yogi who is endowed with the power of Pratyahara can enter into Samadhi even in a crowded place by withdrawing his senses within the twinkling of an eye. He is not disturbed by tumultuous sounds and noises of any description. Even on the battlefield he can rest in his centre? the Self? by withdrawing his senses. He who practises Pratyahara is dead to the world. He will not be affected by the outside vibrations. At any time by mere willing he can bring his senses under his perfect control. They are his obedient servants or instruments.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',59,106,'2-59','विषया विनिवर्तन्ते निराहारस्य देहिनः।

रसवर्जं रसोऽप्यस्य परं दृष्ट्वा निवर्तते।।2.59।।','viṣhayā vinivartante nirāhārasya dehinaḥ
rasa-varjaṁ raso ’pyasya paraṁ dṛiṣhṭvā nivartate',to_json('viṣhayāḥ—objects for senses; vinivartante—restrain; nirāhārasya—practicing self restraint; dehinaḥ—for the embodied; rasa-varjam—cessation of taste; rasaḥ—taste; api—however; asya—person’s; param—the Supreme; dṛiṣhṭvā—on realization; nivartate—ceases to be'::text),'The objects of the senses turn away from the abstinent man, leaving the longing behind; but his longing also turns away upon seeing the Supreme.','Swami Sivananda','2.59 विषयाः the objects of senses? विनिवर्तन्ते turn away? निराहारस्य abstinent? देहिनः of the man? रसवर्जम् leaving the longing? रसः loving (taste)? अपि even? अस्य of his? परम् the Supreme? दृष्ट्वा having seen? निवर्तते turns away.Commentary Knowledge of the Self alone can destroy in toto the subtle Vasanas (latent tendencies) and all the subtle desires? all subtle attachments and even the longing for objects. By practising severe austerities? by abandoning the sensual objects? the objects of the senses may turn away from the ascetic but the relish or taste or longing for the objects will still remain.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',60,107,'2-60','यततो ह्यपि कौन्तेय पुरुषस्य विपश्चितः।

इन्द्रियाणि प्रमाथीनि हरन्ति प्रसभं मनः।।2.60।।','yatato hyapi kaunteya puruṣhasya vipaśhchitaḥ
indriyāṇi pramāthīni haranti prasabhaṁ manaḥ',to_json('yatataḥ—while practicing self-control; hi—for; api—even; kaunteya—Arjun, the son of Kunti; puruṣhasya—of a person; vipaśhchitaḥ—one endowed with discrimination; indriyāṇi—the senses; pramāthīni—turbulent; haranti—carry away; prasabham—forcibly; manaḥ—the mind'::text),'The turbulent senses, O Arjuna, can violently carry away the mind of a wise person, even though they are striving to control them.','Swami Sivananda','2.60 यततः of the striving? हि indeed? अपि even? कौन्तेय O Kaunteya (son of Kunti)? पुरुषस्य of man? विपश्चितः (of the) wise? इन्द्रियाणि the senses? प्रमाथीनि turbulent? हरन्ति carry away? प्रसभम् violently? मनः the mind.Commentary The aspirant should first bring the senses under his control. The senses are like horses. If you keep the horses under your perfect control you can reach your destinaton safely. Turbulent horses will throw you down on the way. Even so the turbulent senses will hurl you down into the objects of the senses and you cannot reach your spiritual destination? viz.? Param Dhama (the supreme abode) or the abode of eternal peace and immortality or Moksha (final liberation). (Cf.III.33V.14).','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',61,108,'2-61','तानि सर्वाणि संयम्य युक्त आसीत मत्परः।

वशे हि यस्येन्द्रियाणि तस्य प्रज्ञा प्रतिष्ठिता।।2.61।।','tāni sarvāṇi sanyamya yukta āsīta mat-paraḥ
vaśhe hi yasyendriyāṇi tasya prajñā pratiṣhṭhitā',to_json('tāni—them; sarvāṇi—all; sanyamya—subduing; yuktaḥ—united; āsīta—seated; mat-paraḥ—toward me (Shree Krishna); vaśhe—control; hi—certainly; yasya—whose; indriyāṇi—senses; tasya—their; prajñā—perfect knowledge pratiṣhṭhitā'::text),'Having restrained them all, he should sit steadfast, intent on Me; his wisdom is steady whose senses are under control.','Swami Sivananda','2.61 तानि them? सर्वाणि all? संयम्य having restrained? युक्तः joined? आसीत should sit? मत्परः intent on Me? वशे under control? हि indeed? यस्य whose? इन्द्रियाणि senses? तस्य his? प्रज्ञा wisdom? प्रतिष्ठिता is settled.Commentary He should control the senses and sit focussed on Me as the Supreme? with a calm mind. The wisdom of the Yogi who thus seated has brought all his senses under subjugation is doubtless ite steady. He is established in the Self. Sri Sankaracharya explains Asita Matparah as He should sit contemplating I am no other than He. (Cf.II.64).','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',62,109,'2-62','ध्यायतो विषयान्पुंसः सङ्गस्तेषूपजायते।

सङ्गात् संजायते कामः कामात्क्रोधोऽभिजायते।।2.62।।','dhyāyato viṣhayān puṁsaḥ saṅgas teṣhūpajāyate
saṅgāt sañjāyate kāmaḥ kāmāt krodho ’bhijāyate',to_json('dhyāyataḥ—contemplating; viṣhayān—sense objects; puṁsaḥ—of a person; saṅgaḥ—attachment; teṣhu—to them (sense objects); upajāyate—arises; saṅgāt—from attachment; sañjāyate—develops; kāmaḥ—desire; kāmāt—from desire; krodhaḥ—anger; abhijāyate—arises'::text),'When one thinks of objects, attachment to them arises; from attachment, desire is born; from desire, anger arises.','Swami Sivananda','2.62 ध्यायतः thinking? विषयान् (on) objects of the senses? पुंसः of a man? सङ्गः attachment? तेषु in them? उपजायते arises? सङ्गात् from attachment? संजायते is born? कामः desire? कामात् from desire? क्रोधः anger? अभिजायते arises.Commentary When a man thinks of the beauty and the pleasant and alluring features of the senseobjects he becomes attached to them. He then regards them as something worthy of acisition and possession and hankers after them. He develops a strong desire to possess them. Then he endeavours his level best to obtain them. When his desire is frustrated by some cause or other? anger arises in his mind. If anybody puts any obstruction in his way of obtaining the objects he hates him? fights with him and develops hostility towards hi. (Cf.II.64).','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',63,110,'2-63','क्रोधाद्भवति संमोहः संमोहात्स्मृतिविभ्रमः।

स्मृतिभ्रंशाद् बुद्धिनाशो बुद्धिनाशात्प्रणश्यति।।2.63।।','krodhād bhavati sammohaḥ sammohāt smṛiti-vibhramaḥ
smṛiti-bhranśhād buddhi-nāśho buddhi-nāśhāt praṇaśhyati',to_json('krodhāt—from anger; bhavati—comes; sammohaḥ—clouding of judgement; sammohāt—from clouding of judgement; smṛiti—memory; vibhramaḥ—bewilderment; smṛiti-bhranśhāt—from bewilderment of memory; buddhi-nāśhaḥ—destruction of intellect; buddhi-nāśhāt—from destruction of intellect; praṇaśhyati—one is ruined'::text),'Anger leads to delusion, which causes loss of memory; this, in turn, leads to the destruction of discrimination, resulting in destruction.','Swami Sivananda','2.63 क्रोधात् from anger? भवति comes? संमोहः delusion? संमोहात् from delusion? स्मृतिविभ्रमः loss of memory? स्मृतिभ्रंशात् from loss of memory? बुद्धिनाशः the destruction of discriminatio? बुद्धिनाशात् from the,destruction of discrimination? प्रणश्यति (he) perishes.Commentary From anger arises delusion. When a man becomes angry he loses his power of discrimination between right and wrong. He will speak and do anything he likes. He will be swept away by the impulse of passion and emotion and will act irrationally.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',64,111,'2-64','रागद्वेषवियुक्तैस्तु विषयानिन्द्रियैश्चरन्।

आत्मवश्यैर्विधेयात्मा प्रसादमधिगच्छति।।2.64।।','rāga-dveṣha-viyuktais tu viṣhayān indriyaiśh charan
ātma-vaśhyair-vidheyātmā prasādam adhigachchhati',to_json('rāga—attachment; dveṣha—aversion; viyuktaiḥ—free; tu—but; viṣhayān—objects of the senses; indriyaiḥ—by the senses; charan—while using; ātma-vaśhyaiḥ—controlling one’s mind; vidheya-ātmā—one who controls the mind; prasādam—the Grace of God; adhigachchhati—attains'::text),'But the self-controlled man, moving among objects with the senses restrained and free from attraction and repulsion, attains peace.','Swami Sivananda','2.64 रागद्वेषवियुक्तैः free from attraction and repulsion? तु but? विषयान् objects? इन्द्रियैः with senses? चरन् moving (amongst)? आत्मवश्यैः selfrestrained? विधेयात्मा the selfcontrolled? प्रसादम् to peace? अधिगच्छति attains.Commentary The mind and the senses are naturally endowed with the two currents of attraction and repulsion. Therefore? the mind and the senses like certain objects and dislike certain other objects. But the disciplined man moves among senseobjects with the mind and the senses free from attraction and repulsion and mastered by the Self? attains to the peace of the Eternal. The senses and the mind obey his will? as the disciplined self has a very strong will. The disciplined self takes only those objects which are ite necessary for the maintenance of the body without any love or hatred. He never takes those objects which are forbidden by the scriptures.In this verse Lord Krishna gives the answer to Arjunas fourth estion? How does a sage of steady wisdom move about (Cf.III.7.19?25XVIII.9).','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',65,112,'2-65','प्रसादे सर्वदुःखानां हानिरस्योपजायते।

प्रसन्नचेतसो ह्याशु बुद्धिः पर्यवतिष्ठते।।2.65।।','prasāde sarva-duḥkhānāṁ hānir asyopajāyate
prasanna-chetaso hyāśhu buddhiḥ paryavatiṣhṭhate',to_json('prasāde—by divine grace; sarva—all; duḥkhānām—of sorrows; hāniḥ—destruction; asya—his; upajāyate—comes; prasanna-chetasaḥ—with a tranquil mind; hi—indeed; āśhu—soon; buddhiḥ—intellect; paryavatiṣhṭhate—becomes firmly established'::text),'In that peace, all pains are destroyed; for the intellect of the tranquil-minded soon becomes steady.','Swami Sivananda','2.65 प्रसादे in peace? सर्वदुःखानाम् (of) all pains? हानिः destruction? अस्य of him? उपजायते arises (or happens)? प्रसन्नचेतसः of the tranilminded? हि because? आशु soon? बुद्धिः intellect (or reason)? पर्यवतिष्ठते becomes steady.Commentary When the mental peace is attained? there is no hankering after senseobjects. The Yogi has perfect mastery over his reason. The intellect abides in the Self. It is ite steady. The miseries of the body and the mind come to an end.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',66,113,'2-66','नास्ति बुद्धिरयुक्तस्य न चायुक्तस्य भावना।

न चाभावयतः शान्तिरशान्तस्य कुतः सुखम्।।2.66।।','nāsti buddhir-ayuktasya na chāyuktasya bhāvanā
na chābhāvayataḥ śhāntir aśhāntasya kutaḥ sukham',to_json('na—not; asti—is; buddhiḥ—intellect; ayuktasya—not united; na—not; cha—and; ayuktasya—not united; bhāvanā—contemplation; na—nor; cha—and; abhāvayataḥ—for those not united; śhāntiḥ—peace; aśhāntasya—of the unpeaceful; kutaḥ—where; sukham—happiness'::text),'There is no knowledge of the Self for the unsteady, and no meditation is possible for the unsteady, and no peace for the unmeditative, and how can there be happiness for one who has no peace?','Swami Sivananda','2.66 न not? अस्ति is? बुद्धिः knowledge (of the Self)? अयुक्तस्य of the unsteady? न not? च and? अयुक्तस्य of the unsteady? भावना meditation? न not? च and? अभावयतः of the unmeditated? शान्तिः peace? अशान्तस्य of the peaceless? कुतः whence? सुखम् happiness.Commentary The man who cannot fix his mind in meditation cannot have knowledge of the Self. The unsteady man cannot practise meditation. He cannot have even intense devotion to Selfknowledge nor can he have burning longing for liberation or Moksha. He who does not practise meditation cannot possess peace of mind. How can the man who has no peace of mind enjoy happinessDesire or Trishna (thirsting for senseobjects) is the enemy of peace. There cannot be an iota or tinge of happiness for a man who is thirsting for sensual objects. The mind will be ever restless? and will be hankering for the objects. Only when this thirsting dies? does man enjoy peace. Only then can he meditate and rest in the Self.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',67,114,'2-67','इन्द्रियाणां हि चरतां यन्मनोऽनुविधीयते।

तदस्य हरति प्रज्ञां वायुर्नावमिवाम्भसि।।2.67।।','indriyāṇāṁ hi charatāṁ yan mano ’nuvidhīyate
tadasya harati prajñāṁ vāyur nāvam ivāmbhasi',to_json('indriyāṇām—of the senses; hi—indeed; charatām—roaming; yat—which; manaḥ—the mind; anuvidhīyate—becomes constantly engaged; tat—that; asya—of that; harati—carries away; prajñām—intellect; vāyuḥ—wind; nāvam—boat; iva—as; ambhasi—on the water'::text),'For the mind, which follows in the wake of the wandering senses, carries away his discrimination, as the wind carries away a boat on the waters.','Swami Sivananda','2.67 इन्द्रियाणाम् senses? हि for? चरताम् wandering? यत् which? मनः mind? अनुविधीयते follows? तत् that? अस्य his? हरति carries away? प्रज्ञाम् discrimination? वायुः the wind? नावम् boat? इव like? अम्भसि in the water.Commentary The mind which constantly dwells on the sensual objects and moves in company with the senses destroys altogether the discrimination of the man. Just as the wind carries away a boat from its course? so also the mind carries away the aspirant from his spiritual path and turns,him towards the objects of the senses.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',68,115,'2-68','तस्माद्यस्य महाबाहो निगृहीतानि सर्वशः।

इन्द्रियाणीन्द्रियार्थेभ्यस्तस्य प्रज्ञा प्रतिष्ठिता।।2.68।।','tasmād yasya mahā-bāho nigṛihītāni sarvaśhaḥ
indriyāṇīndriyārthebhyas tasya prajñā pratiṣhṭhitā',to_json('tasmāt—therefore; yasya—whose; mahā-bāho—mighty-armed one; nigṛihītāni—restrained; sarvaśhaḥ—completely; indriyāṇi—senses; indriya-arthebhyaḥ—from sense objects; tasya—of that person; prajñā—transcendental knowledge; pratiṣhṭhitā—remains fixed'::text),'Therefore, O mighty-armed Arjuna, his knowledge is steady whose senses are completely restrained from sense objects.','Swami Sivananda','2.68 तस्मात् therefore? यस्य whose? महाबाहो O mightyarmed? निगृहीतानि restrained? सर्वशः completely? इन्द्रियाणि the senses? इन्द्रियार्थेभ्यः from the senseobjects? तस्य his? प्रज्ञा knowledge? प्रतिष्ठिता is steady.Commentary When the senses are completely controlled? the mind cannot wander wildly in the sensual grooves. It becomes steady like the lamp in a windless place. The Yogi is now established in the Self and his knowledge is steady. (Cf.III.7).','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',69,116,'2-69','या निशा सर्वभूतानां तस्यां जागर्ति संयमी।

यस्यां जाग्रति भूतानि सा निशा पश्यतो मुनेः।।2.69।।','yā niśhā sarva-bhūtānāṁ tasyāṁ jāgarti sanyamī
yasyāṁ jāgrati bhūtāni sā niśhā paśhyato muneḥ',to_json('yā—which; niśhā—night; sarva-bhūtānām—of all living beings; tasyām—in that; jāgarti—is awake; sanyamī—self-controlled; yasyām—in which; jāgrati—are awake; bhūtāni—creatures; sā—that; niśhā—night; paśhyataḥ—see; muneḥ—sage'::text),'That which is night to all beings, in that the self-controlled man is awake; when all beings are awake, that is night for the sage who sees.','Swami Sivananda','2.69 या which? निशा night? सर्वभूतानाम् of all beings? तस्याम् in that? जागर्ति wakes? संयमी the selfcontrolled? यस्याम् in which? जाग्रति wake? भूतानि all beings? सा that? निशा night? पश्यतः (of the) seeing? मुनेः of the Muni.Commentary That which is real for the wordlyminded people is illusion for the sage? and vice versa. The sage lives in the Self. This is day for him. He is unconscious of the wordly phenomena. They are night for him? as it were. The ordinary man is unconscious of his real nature. Life in the spirit is night for him. He is experiencing the objects of sensual enjoyment. This is day for him. The Self is a nonentity for him For a sage this world is a nonentity.The wordlyminded people are in utter darkness as they have no knowledge of the Self. What is darkness for them is all light for the sage. The Self? Atman or Brahman is night for the worldlyminded persons. But the sage is fully awake. He is directly cognising the supreme Reality? the Light of lights. He is full of illumination and AtmaJnana or knowledge of the Self.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',70,117,'2-70','आपूर्यमाणमचलप्रतिष्ठं

समुद्रमापः प्रविशन्ति यद्वत्।

तद्वत्कामा यं प्रविशन्ति सर्वे

स शान्तिमाप्नोति न कामकामी।।2.70।।','āpūryamāṇam achala-pratiṣhṭhaṁ
samudram āpaḥ praviśhanti yadvat
tadvat kāmā yaṁ praviśhanti sarve
sa śhāntim āpnoti na kāma-kāmī',to_json('āpūryamāṇam—filled from all sides; achala-pratiṣhṭham—undisturbed; samudram—ocean; āpaḥ—waters; praviśhanti—enter; yadvat—as; tadvat—likewise; kāmāḥ—desires; yam—whom; praviśhanti—enter; sarve—all; saḥ—that person; śhāntim—peace; āpnoti—attains; na—not; kāma-kāmī—one who strives to satisfy desires'::text),'He attains peace into whom all desires enter, just as waters enter the ocean which, filled from all sides, remains unmoved; but not the man who is full of desires.','Swami Sivananda','2.70 आपूर्यमाणम् filled from all sides? अचलप्रतिष्ठम् based in stillness? समुद्रम् ocean? आपः water? प्रविशन्ति enter? यद्वत् as? तद्वत् so? कामाः desires? यम् whom? प्रविशन्ति enter? सर्वे all? सः he? शान्तिम् peace? आप्नोति attains? न not? कामकामी desirer of desires.Commentary Just as the ocean filled with waters from all sides remains unmoved? so also the sage who is resting in his own Svarupa or the Self is not a bit affected though desires of all sorts enter from all sides. The sage attains peace or liberation but not he who longs for objects of sensual enjoyment and entertains various desires. (Cf.XVIII.53?54).','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',71,118,'2-71','विहाय कामान्यः सर्वान्पुमांश्चरति निःस्पृहः।

निर्ममो निरहंकारः स शांतिमधिगच्छति।।2.71।।','vihāya kāmān yaḥ sarvān pumānśh charati niḥspṛihaḥ
nirmamo nirahankāraḥ sa śhāntim adhigachchhati',to_json('vihāya—giving up; kāmān—material desires; yaḥ—who; sarvān—all; pumān—a person; charati—lives; niḥspṛihaḥ—free from hankering; nirmamaḥ—without a sense of proprietorship; nirahankāraḥ—without egoism; saḥ—that person; śhāntim—perfect peace; adhigachchhati—attains'::text),'That person attains peace who, abandoning all desires, moves about without longing, without the sense of ownership, and without egoism.','Swami Sivananda','2.71 विहाय abandoning? कामान् desires? यः that? सर्वान् all? पुमान् man? चरति moves about? निःस्पृहः free from longing? निर्ममः devoid of mineness? निरहंकारः without egoism? सः he? शान्तिम् to peace? अधिगच्छति attains.Commentary That man who lives destitute of longing? abandoning all desires? without the senses of I and mine? who is satisfied with the bare necessities of life? who does not care even for those bare necessities of life? who has no attachment even for the bare necessities of life? attains Moksha or eternal peace. (Cf.II.55).','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',72,119,'2-72','एषा ब्राह्मी स्थितिः पार्थ नैनां प्राप्य विमुह्यति।

स्थित्वाऽस्यामन्तकालेऽपि ब्रह्मनिर्वाणमृच्छति।।2.72।।','eṣhā brāhmī sthitiḥ pārtha naināṁ prāpya vimuhyati
sthitvāsyām anta-kāle ’pi brahma-nirvāṇam ṛichchhati',to_json('eṣhā—such; brāhmī sthitiḥ—state of God-realization; pārtha—Arjun, the son of Pritha; na—never; enām—this; prāpya—having attained; vimuhyati—is deluded; sthitvā—being established; asyām—in this; anta-kāle—at the hour of death; api—even; brahma-nirvāṇam—liberation from Maya; ṛichchhati—attains'::text),'O son of Pritha, this is the eternal state, the Brahmic seat. Attaining this, one is not deluded. Being established in it, one attains oneness with Brahman even at the end of life.','Swami Sivananda','2.72 एषा this? ब्राह्मी of Brahmic? स्थितिः state? पार्थ O Partha? न not? एनाम् this? प्राप्य having obtained? विमुह्यति is deluded? स्थित्वा being established? अस्याम् in this? अन्तकाले at the end of life? अपि even? ब्रह्मनिर्वाणम् oneness with Brahman? ऋच्छति attains.Commentary The state described in the previous verse -- to renounce everything and to live in Brahman -- is the Brahmic state or the state of Brahman. If one attains to this state one is never deluded. He attains Moksha if he stays in that state even at the hour of his death. It is needless to say that he who gets establised in Brahman throughout his life attains to the state of Brahman or,BrahmaNirvana (Cf.VIII.5?6).Maharshi Vidyaranya says in his Panchadasi that Antakala here means the moment at which Avidya or mutual superimposition of the Self and the notSelf ends.Thus in the Upanishads of the glorious Bhagavad Gita? the science of the Eternal? the scripture of Yoga? the dialogue between Sri Krishna and Arjuna? ends the second discourse entitledThe Sankhya Yoga.,','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bjt10002u7eup0zze7nk',1,120,'3-1','अर्जुन उवाच

ज्यायसी चेत्कर्मणस्ते मता बुद्धिर्जनार्दन।

तत्किं कर्मणि घोरे मां नियोजयसि केशव।।3.1।।','arjuna uvācha
jyāyasī chet karmaṇas te matā buddhir janārdana
tat kiṁ karmaṇi ghore māṁ niyojayasi keśhava',to_json('arjunaḥ uvācha—Arjun said; jyāyasī—superior; chet—if; karmaṇaḥ—than fruitive action; te—by you; matā—is considered; buddhiḥ—intellect; janārdana—he who looks after the public, Krishna; tat—then; kim—why; karmaṇi—action; ghore—terrible; mām—me; niyojayasi—do you engage; keśhava—Krishna, the killer of the demon named Keshi;'::text),'Arjuna said: If Thou thinkest that knowledge is superior to action, O Krishna, why then, O Kesava, doest Thou ask me to engage in this terrible action?','Swami Sivananda','3.1 ज्यायसी superior? चेत् if? कर्मणः than action? ते by Thee? मता thought? बुद्धिः knowledge? जनार्दन O Janardana? तत् then? किम् why? कर्मणि in action? घोरे terrible? माम् me? नियोजयसि Thou engagest? केशव O Kesava.Commentary In verses 49? 50 and 51 of chapter II? Lord Krsihna has spoken very highly about Buddhi Yoga. He again asks Arjuna to fight. That is the reason why Arjuna is perplexed now.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bjt10002u7eup0zze7nk',2,121,'3-2','व्यामिश्रेणेव वाक्येन बुद्धिं मोहयसीव मे।

तदेकं वद निश्िचत्य येन श्रेयोऽहमाप्नुयाम्।।3.2।।','vyāmiśhreṇeva vākyena buddhiṁ mohayasīva me
tad ekaṁ vada niśhchitya yena śhreyo ’ham āpnuyām',to_json('vyāmiśhreṇa iva—by your apparently ambiguous; vākyena—words; buddhim—intellect; mohayasi—I am getting bewildered; iva—as it were; me—my; tat—therefore; ekam—one; vada—please tell; niśhchitya—decisively; yena—by which; śhreyaḥ—the highest good; aham—I; āpnuyām—may attain'::text),'With this seemingly perplexing speech, you seem to be confusing my understanding; therefore, tell me one certain way by which I may attain bliss.','Swami Sivananda','3.2 व्यामिश्रेण perplexing? इव as it were? वाक्येन with speech? बुद्धिम् understanding? मोहयसि (Thou) confusest? इव as it were? मे my? तत् that? एकम् one? वद tell? निश्चित्य for certain? येन by which? श्रेयः bliss (the good or the highest)? अहम् I? आप्नुयाम् may attain.Commentary Arjuna says to Lord Krishna? Tecah me one of the two? knowledge or action? by which I may attain to the highest good or bliss or Moksha. (Cf.V.I).','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bjt10002u7eup0zze7nk',3,122,'3-3','श्री भगवानुवाच

लोकेऽस्मिन्द्विविधा निष्ठा पुरा प्रोक्ता मयानघ।

ज्ञानयोगेन सांख्यानां कर्मयोगेन योगिनाम्।।3.3।।','śhrī bhagavān uvācha
loke’smin dvi-vidhā niṣhṭhā purā proktā mayānagha
jñāna-yogena sāṅkhyānāṁ karma-yogena yoginām',to_json('śhrī-bhagavān uvācha—the Blessed Lord said; loke—in the world; asmin—this; dvi-vidhā—two kinds of; niṣhṭhā—faith; purā—previously; proktā—explained; mayā—by me (Shree Krishna); anagha—sinless; jñāna-yogena—through the path of knowledge; sānkhyānām—for those inclined toward contemplation; karma-yogena—through the path of action; yoginām—of the yogis'::text),'The Blessed Lord said, "In this world, there is a twofold path, as I said before, O sinless one: the path of knowledge of the Sankhyas and the path of action of the Yogins."','Swami Sivananda','3.3 लोके in world? अस्मिन् in this? द्विविधा twofold? निष्ठा path? पुरा previously? प्रोक्ता said? मया by Me? अनघ O sinless one? ज्ञानयोगेन by the path of knowledge? सांख्यानाम् of the Sankhyas? कर्मयोगेन by the path of action? योगिनाम् of the Yogins.Commentary The path of knowledge of the Sankhyas (Jnana Yoga) was described by Lord Krishna in chapter II? verses 11 to 38 the path of action (Karma Yoga) from 40 to 53.Pura Prokta may also mean In the beginning of creation the twofold path was given by Me to this world.Those who are endowed with the four means and who have sharp? subtle intellect and bold understanding are fit for Jnana Yoga. Those who have a tendency or inclination for wok are fit for Karma Yoga. (The four means are discrimination? dispassion? sixfold virutes? and longing for liberation. The sixfold virtues are control of the mind? control of the senses? fortitude (endurance)? turning away from the objects of the world? faith and tranillity.)It is not possible for a man to practise the two Yogas simultaneously. Karma Yoga is a means to an end. It purifies the heart and prepares the aspirant for the reception of knowledge. The Karma Yogi should take up Jnana Yoga as soon as his heart is purified. Jnana Yoga takes the aspirant directly to the goal without any extraneous help. (Cf.V.5).','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bjt10002u7eup0zze7nk',4,123,'3-4','न कर्मणामनारम्भान्नैष्कर्म्यं पुरुषोऽश्नुते।

न च संन्यसनादेव सिद्धिं समधिगच्छति।।3.4।।','na karmaṇām anārambhān naiṣhkarmyaṁ puruṣho ’śhnute
na cha sannyasanād eva siddhiṁ samadhigachchhati',to_json('na—not; karmaṇām—of actions; anārambhāt—by abstaining from; naiṣhkarmyam—freedom from karmic reactions; puruṣhaḥ—a person; aśhnute—attains; na—not; cha—and; sannyasanāt—by renunciation; eva—only; siddhim—perfection; samadhigachchhati—attains'::text),'Man does not reach actionlessness by not performing actions; nor does he attain perfection by mere renunciation.','Swami Sivananda','3.4 न not? कर्मणाम् of actions? अनारम्भात् from nonperformance? नैष्कर्म्यम् actionlessness? पुरुषः man? अश्नुते reaches? न not? च and? संन्यसनात् from renunciation? एव only? सिद्धिम् perfection? समधिगच्छति attains.Commentary Actionlessness (Naishkarmyam) and perfection (Siddhi) are synonymous. The sage who has attained to perfection or reached the state of actionlessness rests in his own essential nature as ExistenceKnowledgeBliss Absolute (Satchidananda Svarupa). He has neither necessity nor desire for action as a means to an end. He has perfect satisfaction in the Self.One attains to the state of actionlessness by gaining the knowledge of the Self. If a man simply sits iet by abandoning action you cannot say that he has attained to the state of actionlessness. His mind will be planning? scheming and speculating. Thought is real action. The sage who is free from affirmative thoughts? wishes? and likes and dislikes? who has the knowledge of the Self can be said to have attained to the state of actionlessness.No one can reach perfection or freedom from action or knowledge of the Self by mere renunciation or by simply giving up activities without possessing the knowledge of the Self. (Cf.XVIII.49).','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bjt10002u7eup0zze7nk',5,124,'3-5','न हि कश्िचत्क्षणमपि जातु तिष्ठत्यकर्मकृत्।

कार्यते ह्यवशः कर्म सर्वः प्रकृतिजैर्गुणैः।।3.5।।','na hi kaśhchit kṣhaṇam api jātu tiṣhṭhatyakarma-kṛit
kāryate hyavaśhaḥ karma sarvaḥ prakṛiti-jair guṇaiḥ',to_json('na—not; hi—certainly; kaśhchit—anyone; kṣhaṇam—a moment; api—even; jātu—ever; tiṣhṭhati—can remain; akarma-kṛit—without action; kāryate—are performed; hi—certainly; avaśhaḥ—helpless; karma—work; sarvaḥ—all; prakṛiti-jaiḥ—born of material nature; guṇaiḥ—by the qualities'::text),'Verily, no one can remain for even a moment without performing action; for everyone is made to act helplessly, indeed, by the qualities born of Nature.','Swami Sivananda','3.5 नहि not? कश्चित् anyone? क्षणम् a moment? अपि even? जातु verily? तिष्ठति remains? अकर्मकृत् without performing action? कार्यते is made to do? हि for? अवशः helpless? कर्म action? सर्वः all? प्रकृतिजैः born of Prakriti? गुणैः by the alities.Commentary The Gunas (alities of Nature) are three? viz.? Sattva? Rajas and Tamas. Sattva is harmony or light or purity Rajas is passion or motion Tamas is inertia or darkness. Sattvic actions help a man to attain to Moksha. Rajasic and Tamasic actions bind a man to Samsara.These alities cannot affect a man who has knowledge of the Self. He has crossed over these alities. He has become a Gunatita (one who has transcended the alities of Nature). The ignorant man who has no knowledge of the Self and who is swayed by Avidya or nescience is driven helplessly to action by the Gunas. (Cf.IV.16?XVIII.11).','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bjt10002u7eup0zze7nk',6,125,'3-6','कर्मेन्द्रियाणि संयम्य य आस्ते मनसा स्मरन्।

इन्द्रियार्थान्विमूढात्मा मिथ्याचारः स उच्यते।।3.6।।','karmendriyāṇi sanyamya ya āste manasā smaran
indriyārthān vimūḍhātmā mithyāchāraḥ sa uchyate',to_json('karma-indriyāṇi—the organs of action; sanyamya—restrain; yaḥ—who; āste—remain; manasā—in the mind; smaran—to remember; indriya-arthān—sense objects; vimūḍha-ātmā—the deluded; mithyā-āchāraḥ—hypocrite; saḥ—they; uchyate—are called'::text),'He who, restraining the organs of action, sits thinking of the sense-objects in his mind, he of deluded understanding is called a hypocrite.','Swami Sivananda','3.6 कर्मेन्द्रियाणि organs of action? संयम्य restraining? यः who? आस्ते sits? मनसा by the mind? स्मरन् remembering? इन्द्रियार्थान् senseobjects? विमूढात्मा of deluded understanding? मिथ्याचारः hypocrite? सः he? उच्यते is called.Commentary The five organs of action? Karma Indriyas? are Vak (organ of speech)? Pani (hands)? Padam (feet)? Upastha (genitals) and Guda (anus). They are born of the Rajasic portion of the five Tanmatras or subtle elements Vak from the Akasa Tanmatra (ether)? Pani from the Vayu Tanmatra (air)? Padam from the Agni Tanmatra (fire)? Upastha from the Apas Tanmatra (water)? and Guda from the Prithivi Tanmatra (earth). That man who? restraining the organs of action? sits revolving in his mind thoughts regarding the objects of the senses is a man of sinful conduct. He is selfdeluded. He is a veritable hypocrite.The organs of action must be controlled. The thoughts should also be controlled. The mind should be firmly fixed on the Lord. Only then will you become a true Yogi. Only then will you attain to Selfrealisation.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bjt10002u7eup0zze7nk',7,126,'3-7','यस्त्विन्द्रियाणि मनसा नियम्यारभतेऽर्जुन।

कर्मेन्द्रियैः कर्मयोगमसक्तः स विशिष्यते।।3.7।।','yas tvindriyāṇi manasā niyamyārabhate ’rjuna
karmendriyaiḥ karma-yogam asaktaḥ sa viśhiṣhyate',to_json('yaḥ—who; tu—but; indriyāṇi—the senses; manasā—by the mind; niyamya—control; ārabhate—begins; arjuna—Arjun; karma-indriyaiḥ—by the working senses; karma-yogam—karm yog; asaktaḥ—without attachment; saḥ—they; viśhiṣhyate—are superior'::text),'But whoever, controlling the senses by the mind, O Arjuna, engages himself in Karma Yoga with the organs of action, without attachment, he excels.','Swami Sivananda','3.7 यः whose? तु but? इन्द्रियाणि the senses? मनसा by the mind? नियम्य controlling? आरभते commences? अर्जुन O Arjuna? कर्मेन्द्रियैः by the organs of action? कर्मयोगम् Karma Yoga? असक्तः unattached? सः he? विशिष्यते excels.Commentary If anyone performs actions with his organs of action (viz.? hands? feet? organ of speech? etc.) controlling the organs of knowledge by the mind? and without expectation of the fruits of the actions and without egoism? he is certainly more worthy than the other who is a hypocrite or a man of false conduct. (Cf.II.64?68IV.21).The five organs of knowledge are the eyes? the ears? the nose? the skin and the sense of taste (tongue).','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bjt10002u7eup0zze7nk',8,127,'3-8','नियतं कुरु कर्म त्वं कर्म ज्यायो ह्यकर्मणः।

शरीरयात्रापि च ते न प्रसिद्ध्येदकर्मणः।।3.8।।','niyataṁ kuru karma tvaṁ karma jyāyo hyakarmaṇaḥ
śharīra-yātrāpi cha te na prasiddhyed akarmaṇaḥ',to_json('niyatam—constantly; kuru—perform; karma—Vedic duties; tvam—you; karma—action; jyāyaḥ—superior; hi—certainly; akarmaṇaḥ—than inaction; śharīra—bodily; yātrā—maintenance; api—even; cha—and; te—your; na prasiddhyet—would not be possible; akarmaṇaḥ—inaction'::text),'Perform your bounden duty, for action is superior to inaction, and even the maintenance of the body would not be possible for you through inaction.','Swami Sivananda','3.8 नियतम् bounden (prescribed or obligatory)? कुरु perform? कर्म action? त्वम् thou? कर्म action? ज्यायः superior? हि for? अकर्मणः than inaction? शरीरयात्रा maintenance of the body? अपि even? च and? ते thy? न not? प्रसिद्ध्येत् would be possible? अकर्मणः by inaction.Commentary Niyatam Karma is an obligatory duty which one is bound to perform. Thenonperformance of the bounden duties causes demerit. The performance of the obligatory duties is not a means for the attainment of a specific result. The performance does not cause any merit.Living itself involves several natural and unavoidable actions which have to be performed by all. It is ignorance to say? I can live doing nothing.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bjt10002u7eup0zze7nk',9,128,'3-9','यज्ञार्थात्कर्मणोऽन्यत्र लोकोऽयं कर्मबन्धनः।

तदर्थं कर्म कौन्तेय मुक्तसंगः समाचर।।3.9।।','yajñārthāt karmaṇo ’nyatra loko ’yaṁ karma-bandhanaḥ
tad-arthaṁ karma kaunteya mukta-saṅgaḥ samāchara',to_json('yajña-arthāt—for the sake of sacrifice; karmaṇaḥ—than action; anyatra—else; lokaḥ—material world; ayam—this; karma-bandhanaḥ—bondage through one’s work; tat—that; artham—for the sake of; karma—action; kaunteya—Arjun, the son of Kunti; mukta-saṅgaḥ—free from attachment; samāchara—perform properly'::text),'The world is bound by actions other than those performed for the sake of sacrifice; do thou, therefore, O son of Kunti (Arjuna), perform actions for that sake alone, free from attachment.','Swami Sivananda','3.9 यज्ञार्थात् for the sake of sacrifice? कर्मणः of action? अन्यत्र otherwise? लोकः the world? अयम् this? कर्मबन्धनः bound by action? तदर्थम् for that sake? कर्म action? कौन्तेय O Kaunteya? मुक्तसंगः free from attachment? समाचार perform.Commentary Yajna means sacrifice or religious rite or any unselfish action done with a pure motive. It means also Isvara. The Taittiriya Samhita (of the Veda) says Yajna verily is Vishnu (174). If anyone does actions for the sake of the Lord? he is not bound. His heart is purified by performing actions for the sake of the Lord. Where this spirit of unselfishness does not govern the action? it will bind one to Samsara however good or glorious it may be. (Cf.II.48).','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bjt10002u7eup0zze7nk',10,129,'3-10','सहयज्ञाः प्रजाः सृष्ट्वा पुरोवाच प्रजापतिः।

अनेन प्रसविष्यध्वमेष वोऽस्त्विष्टकामधुक्।।3.10।।','saha-yajñāḥ prajāḥ sṛiṣhṭvā purovācha prajāpatiḥ
anena prasaviṣhyadhvam eṣha vo ’stviṣhṭa-kāma-dhuk',to_json('saha—along with; yajñāḥ—sacrifices; prajāḥ—humankind; sṛiṣhṭvā—created; purā—in beginning; uvācha—said; prajā-patiḥ—Brahma; anena—by this; prasaviṣhyadhvam—increase prosperity; eṣhaḥ—these; vaḥ—your; astu—shall be; iṣhṭa-kāma-dhuk—bestower of all wishes'::text),'The Creator, having in the beginning created mankind together with sacrifice, said, "By this shall you propagate; let this be the milch cow of your desires—the cow that yields all the desired objects."','Swami Sivananda','3.10 सहयज्ञाः together with sacrifice? प्रजाः mankind? सृष्ट्वा having created? पुरा in the beginning? उवाच said? प्रजापतिः Prajapati? अनेन by this? प्रसविष्यध्वम् shall ye propagate? एषः this? वः your? अस्तु let be? इष्टकामधुक् milch cow of desires.Commentary Prajapati is the Creator or Brahma. Kamadhuk is another name for the cow Kamadhenu. Kamadhenu is the cow of Indra from which everyone can milk whatever one desires. (Cf.VIII.4IX.2427X.25).','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bjt10002u7eup0zze7nk',11,130,'3-11','देवान्भावयतानेन ते देवा भावयन्तु वः।

परस्परं भावयन्तः श्रेयः परमवाप्स्यथ।।3.11।।','devān bhāvayatānena te devā bhāvayantu vaḥ
parasparaṁ bhāvayantaḥ śhreyaḥ param avāpsyatha',to_json('devān—celestial gods; bhāvayatā—will be pleased; anena—by these (sacrifices); te—those; devāḥ—celestial gods; bhāvayantu—will be pleased; vaḥ—you; parasparam—one another; bhāvayantaḥ—pleasing one another; śhreyaḥ—prosperity; param—the supreme; avāpsyatha—shall achieve'::text),'With this, nourish the gods, and may the gods nourish you; thus, nourishing each other, you shall attain the highest good.','Swami Sivananda','3.11 देवान् the gods? भावयत nourish (ye)? अनेन with this? ते those? देवाः gods? भावयन्तु may nourish? वः you? परस्परम् one another? भावयन्तः nourishing? श्रेयः good? परम् the highest? अवाप्स्यथ shall attain.Commentary Deva literally means the shining one. By this sacrifice you nourish the gods such as Indra. The gods shall nourish you with rain? etc. the highest good is the attainment of the knowledge of the Self which frees one from the round of births and deaths. The highest good may mean the attainment of heaven also. The fruit depends upon the motive of the aspirant.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bjt10002u7eup0zze7nk',12,131,'3-12','इष्टान्भोगान्हि वो देवा दास्यन्ते यज्ञभाविताः।

तैर्दत्तानप्रदायैभ्यो यो भुङ्क्ते स्तेन एव सः।।3.12।।','iṣhṭān bhogān hi vo devā dāsyante yajña-bhāvitāḥ
tair dattān apradāyaibhyo yo bhuṅkte stena eva saḥ',to_json('iṣhṭān—desired; bhogān—necessities of life; hi—certainly; vaḥ—unto you; devāḥ—the celestial gods; dāsyante—will grant; yajña-bhāvitāḥ—satisfied by sacrifice; taiḥ—by them; dattān—things granted; apradāya—without offering; ebhyaḥ—to them; yaḥ—who; bhuṅkte—enjoys; stenaḥ—thieves; eva—verily; saḥ—they'::text),'The gods, nourished by the sacrifice, will give you the desired objects. So, he who enjoys the objects given by the gods without offering anything in return is indeed a thief.','Swami Sivananda','3.12 इष्टान् desired? भोगान् objects? हि so? वः to you? देवाः the gods? दास्यन्ते will give? यज्ञभाविताः nourished by sacrifice? तैः by them? दत्तान् give? अप्रदाय without offering? एभ्यः to them? यः who? भुङ्क्ते enjoys? स्तेनः thief? एव verily? सः he.Commentary When the gods are pleased with you sacrifices? they will bestow on you all the desired objects such as children? cattle? property? etc. He who enjoys what has been given to him by the gods? i.e.? he who gratifies the cravings of his own body and the senses without offering anything to the gods in return is a veritable thief. He is really a dacoit of the property of the gods.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bjt10002u7eup0zze7nk',13,132,'3-13','यज्ञशिष्टाशिनः सन्तो मुच्यन्ते सर्वकिल्बिषैः।

भुञ्जते ते त्वघं पापा ये पचन्त्यात्मकारणात्।।3.13।।','yajña-śhiṣhṭāśhinaḥ santo muchyante sarva-kilbiṣhaiḥ
bhuñjate te tvaghaṁ pāpā ye pachantyātma-kāraṇāt',to_json('yajña-śhiṣhṭa—of remnants of food offered in sacrifice; aśhinaḥ—eaters; santaḥ—saintly persons; muchyante—are released; sarva—all kinds of; kilbiṣhaiḥ—from sins; bhuñjate—enjoy; te—they; tu—but; agham—sins; pāpāḥ—sinners; ye—who; pachanti—cook (food); ātma-kāraṇāt—for their own sake'::text),'The righteous who eat the remnants of the sacrifice are freed from all sins; but those sinful ones who cook food solely for their own sake indeed consume sin.','Swami Sivananda','3.13 यज्ञशिष्टाशिनः who eat the remnants of the sacrifice? सन्तः the righteous? मुच्यन्ते are freed? सर्वकिल्बिषैः from all sins? भुञ्जते eat? ते those? तु indeed? अघम् sin? पापाः sinful ones? ये who? पचन्ति cook? आत्मकारणात् for their own sake.Commentary Those who? after performing the five great sacrifices? eat the remnants of the food are freed from all the sins committed by these five agents of insect slaughter? viz.? (1) the pestle and mortar? (2) the grinding stone? (3) the fireplace? (4) the place where the waterpot is kept? and (5) the broom. These are the five places where injury to life is daily committed. The sins are washed away by the performance of the five MahaYajnas or great sacrifices which every Dvija(twicorn or the people belonging to the first three castes in Hindu society? especially the Brahmin) ought to perform1. DevaYajna Offering sacrifices to the gods which will satisfy them?2. BrahmaYajna or RishiYajna Teaching and reciting the scriptures which will satisfy Brahman and the Rishis?3. PitriYajna Offering libations of water to ones ancestors which will satisfy the manes?4. NriYajna The feeding of the hungry and the guests? and?5. BhutaYajna The feeding of the subhuman species? such as animals? birds? etc.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bjt10002u7eup0zze7nk',14,133,'3-14','अन्नाद्भवन्ति भूतानि पर्जन्यादन्नसम्भवः।

यज्ञाद्भवति पर्जन्यो यज्ञः कर्मसमुद्भवः।।3.14।।','annād bhavanti bhūtāni parjanyād anna-sambhavaḥ
yajñād bhavati parjanyo yajñaḥ karma-samudbhavaḥ',to_json('annāt—from food; bhavanti—subsist; bhūtāni—living beings; parjanyāt—from rains; anna—of food grains; sambhavaḥ—production; yajñāt—from the performance of sacrifice; bhavati—becomes possible; parjanyaḥ—rain; yajñaḥ—performance of sacrifice; karma—prescribed duties; samudbhavaḥ—born of'::text),'From food come forth beings; from rain, food is produced; from sacrifice arises rain, and sacrifice is born of action.','Swami Sivananda','3.14 अन्नात् from food? भवन्ति come forth? भूतानि beings? पर्जन्यात् from rain? अन्नसम्भवः production of food? यज्ञात् from sacrifice? भवति arises? पर्जन्यः rain? यज्ञः sacrifice? कर्मसमुद्भवः born of action.Commentary Here Yajna means Apurva or the subtle principle or the unseen form which a sacrifice assumes between the time of its performance and the time when its fruits manifest themselves.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bjt10002u7eup0zze7nk',15,134,'3-15','कर्म ब्रह्मोद्भवं विद्धि ब्रह्माक्षरसमुद्भवम्।

तस्मात्सर्वगतं ब्रह्म नित्यं यज्ञे प्रतिष्ठितम्।।3.15।।','karma brahmodbhavaṁ viddhi brahmākṣhara-samudbhavam
tasmāt sarva-gataṁ brahma nityaṁ yajñe pratiṣhṭhitam',to_json('karma—duties; brahma—in the Vedas; udbhavam—manifested; viddhi—you should know; brahma—The Vedas; akṣhara—from the Imperishable (God); samudbhavam—directly manifested; tasmāt—therefore; sarva-gatam—all-pervading; brahma—The Lord; nityam—eternally; yajñe—in sacrifice; pratiṣhṭhitam—established'::text),'Know that action comes from Brahma, and Brahma comes from the Imperishable. Therefore, the all-pervasive Brahma ever rests in sacrifice.','Swami Sivananda','3.15 कर्म action? ब्रह्मोद्भवम् arisen from Brahma? विद्धि know? ब्रह्म Brahma? अक्षरसमुद्भवम् arisen from the Imperishable? तस्मात् therefore? सर्वगतम् allpervading? ब्रह्म Brahma? नित्यम् ever? यज्ञे in sacrifice? प्रतिष्ठितम् (is) established.Commentary Brahma may mean Veda. Just as the breath comes out of a man? so also the Veda is the breath of the Imperishable or the Omniscient. The Veda ever rests in the sacrifice? i.e.? it deals chiefly with sacrifices and the ways of their performance. (Cf.IV.24 to 32).Karma Action? Brahmodbhavam arisen from the injunctions of the Vedas.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bjt10002u7eup0zze7nk',16,135,'3-16','एवं प्रवर्तितं चक्रं नानुवर्तयतीह यः।

अघायुरिन्द्रियारामो मोघं पार्थ स जीवति।।3.16।।','evaṁ pravartitaṁ chakraṁ nānuvartayatīha yaḥ
aghāyur indriyārāmo moghaṁ pārtha sa jīvati',to_json('evam—thus; pravartitam—set into motion; chakram—cycle; na—not; anuvartayati—follow; iha—in this life; yaḥ—who; agha-āyuḥ—sinful living; indriya-ārāmaḥ—for the delight of their senses; mogham—vainly; pārtha—Arjun, the son of Pritha; saḥ—they; jīvati—live'::text),'He who does not follow the wheel thus set in motion, who is of sinful life, rejoicing in the senses, lives in vain, O Arjuna.','Swami Sivananda','3.16 एवम् thus? प्रवर्तितम् set revolving? चक्रम् wheel? न not? अनुवर्तयति follows? इह here? यः who? अघायुः living in sin? इन्द्रियारामः rejoicing in the senses? मोघम् in vain? पार्थ O Partha? सः he? जीवति lives.Commentary This is the wheel of action set in motion by the Creator on the basis of the Veda and sacrifice.He who does not follow the wheel by studying the Vedas and performing the sacrifices prescribed therein but who indulges only in sensual pleasures lives in vain. He is wasting his life. He is leading a worthless life indeed.One who does not live in accordance with this law and who is selfish commits sin. He violates the law of the Creator and that is the worst sin.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bjt10002u7eup0zze7nk',17,136,'3-17','यस्त्वात्मरतिरेव स्यादात्मतृप्तश्च मानवः।

आत्मन्येव च सन्तुष्टस्तस्य कार्यं न विद्यते।।3.17।।','yas tvātma-ratir eva syād ātma-tṛiptaśh cha mānavaḥ
ātmanyeva cha santuṣhṭas tasya kāryaṁ na vidyate',to_json('yaḥ—who; tu—but; ātma-ratiḥ—rejoice in the self; eva—certainly; syāt—is; ātma-tṛiptaḥ—self-satisfied; cha—and; mānavaḥ—human being; ātmani—in the self; eva—certainly; cha—and; santuṣhṭaḥ—satisfied; tasya—his; kāryam—duty; na—not; vidyate—exist'::text),'But for that man who rejoices only in the Self, who is satisfied with the Self and is content in the Self alone, indeed there is nothing to do.','Swami Sivananda','3.17 यः who? तु but? आत्मरतिः who rejoices in the Self? एव only? स्यात् may be? आत्मतृप्तः satisfied in the Self? च and? मानवः the man? आत्मनि in the Self? एव only? च and? सन्तुष्टः contented? तस्य his? कार्यम् work to be done? न not? विद्यते is.Commentary The sage does not depend on external objects for his happiness. He is ite satisfied with the Self. He finds his joy? bliss and contentment within his own Self. For such a sage who has knowledge of the Self? there is nothing to do. He has already done all actions. He has satisfied all his desires. He has complete satisfaction. (Cf.II.55).','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bjt10002u7eup0zze7nk',18,137,'3-18','नैव तस्य कृतेनार्थो नाकृतेनेह कश्चन।

न चास्य सर्वभूतेषु कश्िचदर्थव्यपाश्रयः।।3.18।।','naiva tasya kṛitenārtho nākṛiteneha kaśhchana
na chāsya sarva-bhūteṣhu kaśhchid artha-vyapāśhrayaḥ',to_json('na—not; eva—indeed; tasya—his; kṛitena—by discharge of duty; arthaḥ—gain; na—not; akṛitena—without discharge of duty; iha—here; kaśhchana—whatsoever; na—never; cha—and; asya—of that person; sarva-bhūteṣhu—among all living beings; kaśhchit—any; artha—necessity; vyapāśhrayaḥ—to depend upon'::text),'For him, there is no interest whatsoever in what is done or not done; nor does he depend on any being for any purpose.','Swami Sivananda','3.18 न not? एव even? तस्य of hi? कृतेन by action? अर्थः concern? न not? अकृतेन by actions not done? इह here? कश्चन् any? न not? च and? अस्य of this man? सर्वभूतेषु in all beings? कश्चित् any? अर्थव्यपाश्रयः depending for any object.Commentary The sage who is thus rejoicing in the Self does not gain anything by doing any action. For him really no purpose is served by an action. No evil (Pratyavaya Dosha) can touch him from inaction. He does not lose anything from inaction. He need not depend upon anybody to gain a particular object. He need not exert himself to get the favour of anybody.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bjt10002u7eup0zze7nk',19,138,'3-19','तस्मादसक्तः सततं कार्यं कर्म समाचर।

असक्तो ह्याचरन्कर्म परमाप्नोति पूरुषः।।3.19।।','tasmād asaktaḥ satataṁ kāryaṁ karma samāchara
asakto hyācharan karma param āpnoti pūruṣhaḥ',to_json('tasmāt—therefore; asaktaḥ—without attachment; satatam—constantly; kāryam—duty; karma—action; samāchara—perform; asaktaḥ—unattached; hi—certainly; ācharan—performing; karma—work; param—the Supreme; āpnoti—attains; pūruṣhaḥ—a person'::text),'Therefore, without attachment, always perform the actions that should be done; for by performing actions without attachment, one reaches the Supreme.','Swami Sivananda','3.19 तस्मात् therefore? असक्तः without attachment? सततम् always? कार्यम् which should be done? कर्म action? समाचर perform? असक्तः without attachment? हि because? आचरन् performing? कर्म action? परम् the Supreme? आप्नोति attains? पूरुषः man.Commentary If you perform actions without attachment? for the sake of the Lord? you will attain to Selfrealisation through purity of heart. (Cf.II.64IV.19?23XVIII.49).','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bjt10002u7eup0zze7nk',20,139,'3-20','कर्मणैव हि संसिद्धिमास्थिता जनकादयः।

लोकसंग्रहमेवापि संपश्यन्कर्तुमर्हसि।।3.20।।','karmaṇaiva hi sansiddhim āsthitā janakādayaḥ
loka-saṅgraham evāpi sampaśhyan kartum arhasi',to_json('karmaṇā—by the performance of prescribed duties; eva—only; hi—certainly; sansiddhim—perfection; āsthitāḥ—attained; janaka-ādayaḥ—King Janak and other kings; loka-saṅgraham—for the welfare of the masses; eva api—only; sampaśhyan—considering; kartum—to perform; arhasi—you should;'::text),'Janaka and others attained perfection indeed through action alone; even with the intention of protecting the masses, you should perform action.','Swami Sivananda','3.20 कर्मणा by action? एव only? हि verily? संसिद्धिम् perfection? आस्थिताः attained? जनकादयः Janaka and others? लोकसंग्रहम् protection of the masses? एवापि only? संपश्यन् having in view? कर्तुम् to perform? अर्हसि thou shouldst.Commentary Samsiddhi is Moksha (perfection or liberation). Janaka? (Asvapati) and others had perfect knowledge of the Self? and yet they performed actions in order to set an example to the masses. They worked for the guidance of men.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bjt10002u7eup0zze7nk',21,140,'3-21','यद्यदाचरति श्रेष्ठस्तत्तदेवेतरो जनः।

स यत्प्रमाणं कुरुते लोकस्तदनुवर्तते।।3.21।।','yad yad ācharati śhreṣhṭhas tat tad evetaro janaḥ
sa yat pramāṇaṁ kurute lokas tad anuvartate',to_json('yat yat—whatever; ācharati—does; śhreṣhṭhaḥ—the best; tat tat—that (alone); eva—certainly; itaraḥ—common; janaḥ—people; saḥ—they; yat—whichever; pramāṇam—standard; kurute—perform; lokaḥ—world; tat—that; anuvartate—pursues'::text),'Whatever a great man does, others also do; whatever he establishes as the standard, the world follows.','Swami Sivananda','3.21 यद्यत् whatsoever? आचरति does? श्रेष्ठः the best? तत्तत् that? एव only? इतरः the other? जनः people? सः he (that great man)? यत् what? प्रमाणम् standard (authority? demonstration)? कुरुते does? लोकः the world (people)? तत् that? अनुवर्तते follows.Commentary Man is a social animal. He is an imitating animal too. He takes his ideas of right and wrong from those whom he regards as his moral superior. Whatever a great man follows? the same is considered as an authority by his followers. They try to follow him. They endeavour to walk in his footsteps.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bjt10002u7eup0zze7nk',22,141,'3-22','न मे पार्थास्ति कर्तव्यं त्रिषु लोकेषु किञ्चन।

नानवाप्तमवाप्तव्यं वर्त एव च कर्मणि।।3.22।।','na me pārthāsti kartavyaṁ triṣhu lokeṣhu kiñchana
nānavāptam avāptavyaṁ varta eva cha karmaṇi',to_json('na—not; me—mine; pārtha—Arjun; asti—is; kartavyam—duty; triṣhu—in the three; lokeṣhu—worlds; kiñchana—any; na—not; anavāptam—to be attained; avāptavyam—to be gained; varte—I am engaged; eva—yet; cha—also; karmaṇi—in prescribed duties'::text),'There is nothing in the three worlds, O Arjuna, that needs to be done by Me, nor is there anything unattained that needs to be attained; yet I engage Myself in action.','Swami Sivananda','3.22 न not? मे my? पार्थ O Partha? अस्ति is? कर्तव्यम् to be done (duty)? त्रिषु in the three? लोकेषु worlds? किञ्चन anything? न not? अनवाप्तम् unattained? अवाप्तव्यम् to be attained? वर्ते am? एव also? च and? कर्मणि in action.Commentary I am the Lord of the universe and therefore I have no personal grounds to engage. Myself in action. I have nothing to achieve as I have all divine wealth? as the wealth of the universe is Mine? and yet I engage Myself in action.Why do you not follow My example Why do you not endeavour to prevent the masses from following the wrong path by setting an example yourself If you set an example? people will follow you as you are a leader with noble alities.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bjt10002u7eup0zze7nk',23,142,'3-23','यदि ह्यहं न वर्तेयं जातु कर्मण्यतन्द्रितः।

मम वर्त्मानुवर्तन्ते मनुष्याः पार्थ सर्वशः।।3.23।।','yadi hyahaṁ na varteyaṁ jātu karmaṇyatandritaḥ
mama vartmānuvartante manuṣhyāḥ pārtha sarvaśhaḥ',to_json('yadi—if; hi—certainly; aham—I; na—not; varteyam—thus engage; jātu—ever; karmaṇi—in the performance of prescribed duties; atandritaḥ—carefully; mama—my; vartma—path; anuvartante—follow; manuṣhyāḥ—all men; pārtha—Arjun, the son of Pritha; sarvaśhaḥ—in all respects'::text),'For, should I not ever engage myself in action, unwearied, people would in every way follow my path, O Arjuna.','Swami Sivananda','3.23 यदि if? हि surely? अहम् I? न not? वर्तेयम् engage Myself in action? जातु ever? कर्मणि in action? अतन्द्रितः unwearied? मम My? वर्त्म path? अनुवर्तन्ते follow? मनुष्याः men? पार्थ O Partha? सर्वशः in every way.Commentary If I remain inactive? people also will imitate Me and keep iet. They will all become Tamasic and pass into a state of inertia.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bjt10002u7eup0zze7nk',24,143,'3-24','उत्सीदेयुरिमे लोका न कुर्यां कर्म चेदहम्।

सङ्करस्य च कर्ता स्यामुपहन्यामिमाः प्रजाः।।3.24।।','utsīdeyur ime lokā na kuryāṁ karma ched aham
sankarasya cha kartā syām upahanyām imāḥ prajāḥ',to_json('utsīdeyuḥ—would perish; ime—all these; lokāḥ—worlds; na—not; kuryām—I perform; karma—prescribed duties; chet—if; aham—I; sankarasya—of uncultured population; cha—and; kartā—responsible; syām—would be; upahanyām—would destroy; imāḥ—all these; prajāḥ—living entities'::text),'These worlds would perish if I did not perform action; I would be the author of confusion of castes and destruction of these beings.','Swami Sivananda','3.24 उत्सीदेयुः would perish? इमे these? लोकाः worlds? न not? कुर्याम् would do? कर्म action? चेत् if? अहम् I? सङ्करस्य of confusion of castes? च and? कर्ता author? स्याम् would be? उपहन्याम् would destroy? इमाःthese? प्रजाः beings.Commentary If I did not engage in action? people would also be inactive. They would not do their duties according to the Varnasrama Dharma (code of morals governing their own order and stage of life). Hence confusion of castes would arise. I would have to destroy these beings.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bjt10002u7eup0zze7nk',25,144,'3-25','सक्ताः कर्मण्यविद्वांसो यथा कुर्वन्ति भारत।

कुर्याद्विद्वांस्तथासक्तश्िचकीर्षुर्लोकसंग्रहम्।।3.25।।','saktāḥ karmaṇyavidvānso yathā kurvanti bhārata
kuryād vidvāns tathāsaktaśh chikīrṣhur loka-saṅgraham',to_json('saktāḥ—attached; karmaṇi—duties; avidvānsaḥ—the ignorant; yathā—as much as; kurvanti—act; bhārata—scion of Bharat (Arjun); kuryāt—should do; vidvān—the wise; tathā—thus; asaktaḥ—unattached; chikīrṣhuḥ—wishing; loka-saṅgraham—welfare of the world'::text),'As the ignorant act out of attachment to action, O Bharata, so should the wise act without attachment, wishing for the welfare of the world.','Swami Sivananda','3.25 सक्ताः attached? कर्मणि to action? अविद्वांसः the ignorant? यथा as? कुर्वन्ति act? भारत O Bharata? कुर्यात् should act? विद्वान् the wise? तथा so? असक्तः unattached? चिकीर्षुः wishing? लोकसंग्रहम् the welfare of the world.Commentary The ignorant man works in expectation of fruits. He says? I will do such and such work and will get such and such fruit. But the wise man who knows the Self? serves not for his own end. He should so act that the world? following his example? would attain peace? harmony? purity of heart? divine light and knowledge. A wise man is one who knows the Self. (Cf.II.64III.19XVIII.49).','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bjt10002u7eup0zze7nk',26,145,'3-26','न बुद्धिभेदं जनयेदज्ञानां कर्मसङ्गिनाम्।

जोषयेत्सर्वकर्माणि विद्वान् युक्तः समाचरन्।।3.26।।','na buddhi-bhedaṁ janayed ajñānāṁ karma-saṅginām
joṣhayet sarva-karmāṇi vidvān yuktaḥ samācharan',to_json('na—not; buddhi-bhedam—discord in the intellects; janayet—should create; ajñānām—of the ignorant; karma-saṅginām—who are attached to fruitive actions; joṣhayet—should inspire (them) to perform; sarva—all; karmāṇi—prescribed; vidvān—the wise; yuktaḥ—enlightened; samācharan—performing properly'::text),'Let no wise man unsettle the minds of ignorant people who are attached to action; he should engage them in all actions, himself fulfilling them with devotion.','Swami Sivananda','3.26 न not? बुद्धिभेदम् unsettlement in the mind? जनयेत् should produce? अज्ञानाम् of the ignorant? कर्मसङ्गिनाम् of the persons attached to actions? जोषयेत् should engage? सर्वकर्माणि all actions? विद्वान् the wise? युक्तः balanced? समाचरन् performing.Commentary An ignorant may says to himelf? I shall do this action and thery enjoy its fruit. A wise man should not unsettle his belief. On the contrary he himself should set an example by performing his duties diligently but without attachment. The wise man should also persuade the ignorant never to neglect their duties. If need be? he should place before them in vivid colours the happiness they would enjoy here and hereafter by discharging such duties. When their hearts get purified in course of time? the wise man could sow the seeds of Karma Yoga (selfless service without deire) in them.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bjt10002u7eup0zze7nk',27,146,'3-27','प्रकृतेः क्रियमाणानि गुणैः कर्माणि सर्वशः।

अहङ्कारविमूढात्मा कर्ताऽहमिति मन्यते।।3.27।।','prakṛiteḥ kriyamāṇāni guṇaiḥ karmāṇi sarvaśhaḥ
ahankāra-vimūḍhātmā kartāham iti manyate',to_json('prakṛiteḥ—of material nature; kriyamāṇāni—carried out; guṇaiḥ—by the three modes; karmāṇi—activities; sarvaśhaḥ—all kinds of; ahankāra-vimūḍha-ātmā—those who are bewildered by the ego and misidentify themselves with the body; kartā—the doer; aham—I; iti—thus; manyate—thinks'::text),'All actions are wrought in all cases by the qualities of Nature alone. He whose mind is deluded by egoism thinks, "I am the doer."','Swami Sivananda','3.27 प्रकृतेः of nature? क्रियमाणानि are performed? गुणैः by the alities? कर्माणि actions? सर्वशः in all cases? अहङ्कारविमूढात्मा one whose mind is deluded by egosim? कर्ता doer? अहम् I? इति thus? मन्यते thinks.Commentary Prakriti or Pradhana or Nature is that state in which the three Gunas? viz.? Sattva? Rajas and Tamas exist in a state of eilibrium. When this eilibrium is disturbed? creation begins body? senses? mind? etc.? are formed. The man who is deluded by egoism identifies the Self with the body? mind? the life force and the senses and ascribes to the Self all the attributes of the body and the senses. He? therefore? thinks through ignorance? I am the doer. In reality the Gunas of Nature perform all actions. (Cf.III.29V.9IX.9?10XIII.21?24?30?32XVIII.13?14).','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bjt10002u7eup0zze7nk',28,147,'3-28','तत्त्ववित्तु महाबाहो गुणकर्मविभागयोः।

गुणा गुणेषु वर्तन्त इति मत्वा न सज्जते।।3.28।।','tattva-vit tu mahā-bāho guṇa-karma-vibhāgayoḥ
guṇā guṇeṣhu vartanta iti matvā na sajjate',to_json('tattva-vit—the knower of the Truth; tu—but; mahā-bāho—mighty-armed one; guṇa-karma—from guṇas and karma; vibhāgayoḥ—distinguish; guṇāḥ—modes of material nature in the shape of the senses, mind, etc; guṇeṣhu—modes of material nature in the shape of objects of perception; vartante—are engaged; iti—thus; matvā—knowing; na—never; sajjate—becomes attached'::text),'But he who knows the Truth, O mighty-armed Arjuna, about the divisions of the qualities and their functions, knowing that the Gunas, as senses, move amidst the Gunas, as the sense-objects, is not attached.','Swami Sivananda','3.28 तत्त्ववित् the knower of the Truth? तु but? महाबाहो O mightyarmed? गुणकर्मविभागयोः of the divisions of alities and functions? गुणाः the alities (in the shape of senses)? गुणेषु amidst the alities (in the shape of objects)? वर्तन्ते remain? इति thus? मत्वा knowing? न not? सज्जते is attached.Commentary He who knows the truth that the Self is entirely distinct from the three Gunas and actions does not become attached to the actions. He who knows the truth about the classification of the Gunas and their respective functions understands that the alities as senseorgans move amidst the alities as senseobjects. Therefore he is not attached to the actions. He knows? I am Akarta -- I am not the doer. (Cf.XIV.23).','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bjt10002u7eup0zze7nk',29,148,'3-29','प्रकृतेर्गुणसम्मूढाः सज्जन्ते गुणकर्मसु।

तानकृत्स्नविदो मन्दान्कृत्स्नविन्न विचालयेत्।।3.29।।','prakṛiter guṇa-sammūḍhāḥ sajjante guṇa-karmasu
tān akṛitsna-vido mandān kṛitsna-vin na vichālayet',to_json('prakṛiteḥ—of material nature; guṇa—by the modes of material nature; sammūḍhāḥ—deluded; sajjante—become attached; guṇa-karmasu—to results of actions; tān—those; akṛitsna-vidaḥ—persons without knowledge; mandān—the ignorant; kṛitsna-vit—persons with knowledge; na vichālayet—should not unsettle'::text),'Those deluded by the qualities of Nature are attached to the functions of the qualities. The man of perfect knowledge should not unsettle the foolish one who is of imperfect knowledge.','Swami Sivananda','3.29 प्रकृतेः of nature? गुणसंमूढाः persons deluded by the Gunas? सज्जन्ते are attached? गुणकर्मसु in the functions of the alities? तान् those? अकृत्स्नविदः of imperfect knowledge? मन्दान् the foolish (thedullwitted)? कृत्स्नवित् man of perfect knowledge? न not? विचालयेत् should unsettle.Commentary The ignorant people do action with the expectation of fruits. The wise people who have the knowledge of the Self should not distract the faith or conviction or belief of such ignorant persons. If they unsettle their minds they will give up actions and become victims of inertia. They will lead an idle life. They should be encouraged by the wise to do actions of the Sakama type (actions for the sake of their fruits) in the beginning. The wise ones should turn the minds of the ignorant by giving them gradual instructions on Karma Yoga (Yoga of selfless? desireless action) and its benefits? viz.? purification of the heart that leads to the attainment of Selfrealisation.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bjt10002u7eup0zze7nk',30,149,'3-30','मयि सर्वाणि कर्माणि संन्यस्याध्यात्मचेतसा।

निराशीर्निर्ममो भूत्वा युध्यस्व विगतज्वरः।।3.30।।','mayi sarvāṇi karmāṇi sannyasyādhyātma-chetasā
nirāśhīr nirmamo bhūtvā yudhyasva vigata-jvaraḥ',to_json('mayi—unto me; sarvāṇi—all; karmāṇi—works; sannyasya—renouncing completely; adhyātma-chetasā—with the thoughts resting on God; nirāśhīḥ—free from hankering for the results of the actions; nirmamaḥ—without ownership; bhūtvā—so being; yudhyasva—fight; vigata-jvaraḥ—without mental fever'::text),'Renouncing all actions in Me, with the mind centered on the Self, free from hope and egoism, and from mental fever, fight thou.','Swami Sivananda','3.30 मयि in Me? सर्वाणि all? कर्माणि actions? संन्यस्य renouncing? अध्यात्मचेतसा with the mind centred in the Self? निराशीः free from hope? निर्ममः free from egoism? भूत्वा having become युध्यस्व fight (thou)? विगतज्वरः free from (mental) fever.Commentary Surrender all the actions to Me with the thought? I perform all actions for the sake of the Lord.Fever means grief? sorrow. (Cf.V.10XVIII.66).','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bjt10002u7eup0zze7nk',31,150,'3-31','ये मे मतमिदं नित्यमनुतिष्ठन्ति मानवाः।

श्रद्धावन्तोऽनसूयन्तो मुच्यन्ते तेऽपि कर्मभिः।।3.31।।','ye me matam idaṁ nityam anutiṣhṭhanti mānavāḥ
śhraddhāvanto ’nasūyanto muchyante te ’pi karmabhiḥ',to_json('ye—who; me—my; matam—teachings; idam—these; nityam—constantly; anutiṣhṭhanti—abide by; mānavāḥ—human beings; śhraddhā-vantaḥ—with profound faith; anasūyantaḥ—free from cavilling; muchyante—become free; te—those; api—also; karmabhiḥ—from the bondage of karma'::text),'Those who constantly practice this teaching of Mine with faith and without caviling, they too are freed from actions.','Swami Sivananda','3.31 ये those who? मे My? मतम् teaching? इदम् this? नित्यम् constantly? अनुतिष्ठन्ति practise? मानवाः men? श्रद्धावन्तः full of faith? अनसूयन्तः not cavilling? मुच्यन्ते are freed? ते they? अपि also? कर्मभिः from actions.Commentary Sraddha is a mental attitude. It means faith. It is faith in ones own Self? in the scriptures and in the teachings of the spiritual preceptor. It is compund of the higher emotion of faith? reverence and humility.','Swami Sivananda',now(),now())
ON CONFLICT (slug) DO UPDATE SET
  sanskrit            = EXCLUDED.sanskrit,
  transliteration     = EXCLUDED.transliteration,
  "wordByWord"        = EXCLUDED."wordByWord",
  translation         = EXCLUDED.translation,
  "translationAuthor" = EXCLUDED."translationAuthor",
  commentary          = EXCLUDED.commentary,
  "commentaryAuthor"  = EXCLUDED."commentaryAuthor",
  "updatedAt"         = now();