-- Batch 1 (verses 51-100)
INSERT INTO "Verse" (id,"chapterId",number,"globalNumber",slug,sanskrit,transliteration,"wordByWord",translation,"translationAuthor",commentary,"commentaryAuthor","createdAt","updatedAt")
VALUES
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',4,51,'2-4','अर्जुन उवाच

कथं भीष्ममहं संख्ये द्रोणं च मधुसूदन।

इषुभिः प्रतियोत्स्यामि पूजार्हावरिसूदन।।2.4।।','arjuna uvācha
kathaṁ bhīṣhmam ahaṁ sankhye droṇaṁ cha madhusūdana
iṣhubhiḥ pratiyotsyāmi pūjārhāvari-sūdana',to_json('arjunaḥ uvācha—Arjun said; katham—how; bhīṣhmam—Bheeshma; aham—I; sankhye—in battle; droṇam—Dronacharya; cha—and; madhu-sūdana—Shree Krishn, slayer of the Madhu demon; iṣhubhiḥ—with arrows; pratiyotsyāmi—shall I shoot; pūjā-arhau—worthy of worship; ari-sūdana—destroyer of enemies'::text),'Arjuna said, "O Madhusudana, how can I fight in battle with arrows against Bhishma and Drona, who are worthy of being worshipped, O destroyer of enemies?"','Swami Sivananda','2.4 कथम् how? भीष्मम् Bhishma? अहम् I? संख्ये in battle? द्रोणम् Drona? च and? मधुसूदन O Madhusudana? इषुभिः with arrows? प्रतियोत्स्यामि shall fight? पूजार्हौ worthy to be worshipped? अरिसूदन O destroyer of enemies.No commentary.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',5,52,'2-5','गुरूनहत्वा हि महानुभावान्

श्रेयो भोक्तुं भैक्ष्यमपीह लोके।

हत्वार्थकामांस्तु गुरूनिहैव

भुञ्जीय भोगान् रुधिरप्रदिग्धान्।।2.5।।','gurūnahatvā hi mahānubhāvān
śhreyo bhoktuṁ bhaikṣhyamapīha loke
hatvārtha-kāmāṁstu gurūnihaiva
bhuñjīya bhogān rudhira-pradigdhān',to_json('gurūn—teachers; ahatvā—not killing; hi—certainly; mahā-anubhāvān—noble elders; śhreyaḥ—better; bhoktum—to enjoy life; bhaikṣhyam—by begging; api—even; iha loke—in this world; hatvā—killing; artha—gain; kāmān—desiring; tu—but; gurūn—noble elders; iha—in this world; eva—certainly; bhuñjīya—enjoy; bhogān—pleasures; rudhira—blood; pradigdhān—tainted with'::text),'Better it is, indeed, in this world to accept alms than to slay the most noble teachers. But if I were to kill them, even in this world, all my enjoyments of wealth and fulfilled desires would be stained with their blood.','Swami Sivananda','2.5 गुरून् the Gurus (teachers)? अहत्वा instead of slaying? हि indeed? महानुभावान् most noble? श्रेयः better? भोक्तुम् to eat? भैक्ष्यम् alms? अपि even? इह here? लोके in the world? हत्वा having slain? अर्थकामान् desirous of wealth? तु indeed? गुरून् Gurus? इह here? एव also? भुञ्जीय enjoy? भोगान् enjoyments? रुधिरप्रदिग्धान् stained with blood.No commentary.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',6,53,'2-6','न चैतद्विद्मः कतरन्नो गरीयो

यद्वा जयेम यदि वा नो जयेयुः।

यानेव हत्वा न जिजीविषाम

स्तेऽवस्थिताः प्रमुखे धार्तराष्ट्राः।।2.6।।','na chaitadvidmaḥ kataranno garīyo
yadvā jayema yadi vā no jayeyuḥ
yāneva hatvā na jijīviṣhāmas
te ’vasthitāḥ pramukhe dhārtarāṣhṭrāḥ',to_json('na—not; cha—and; etat—this; vidmaḥ—we know; katarat—which; naḥ—for us; garīyaḥ—is preferable; yat vā—whether; jayema—we may conquer; yadi—if; vā—or; naḥ—us; jayeyuḥ—they may conquer; yān—whom; eva—certainly; hatvā—after killing; na—not; jijīviṣhāmaḥ—we desire to live; te—they; avasthitāḥ—are standing; pramukhe—before us; dhārtarāṣhṭrāḥ—the sons of Dhritarashtra'::text),'I can hardly tell which would be better, that we should conquer them or that they should conquer us. Even the sons of Dhritarashtra, whom we do not wish to slay, stand facing us.','Swami Sivananda','2.6 न not? च and? एतत् this? विद्मः (we) know? कतरत् which? नः for us? गरीयः better? यत् that? वा or? जयेम we should coner? यदि if? वा or? नः us? जयेयुः they should coner? यान् whom? एव even? हत्वा having slain? न not? जिजीविषामः we wish to live? ते those? अवस्थिताः (are) standing? प्रमुखे in face? धार्तराष्ट्राः sons of Dhritarashtra.No commentary.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',7,54,'2-7','कार्पण्यदोषोपहतस्वभावः

पृच्छामि त्वां धर्मसंमूढचेताः।

यच्छ्रेयः स्यान्निश्िचतं ब्रूहि तन्मे

शिष्यस्तेऽहं शाधि मां त्वां प्रपन्नम्।।2.7।।','kārpaṇya-doṣhopahata-svabhāvaḥ
pṛichchhāmi tvāṁ dharma-sammūḍha-chetāḥ
yach-chhreyaḥ syānniśhchitaṁ brūhi tanme
śhiṣhyaste ’haṁ śhādhi māṁ tvāṁ prapannam',to_json('kārpaṇya-doṣha—the flaw of cowardice; upahata—besieged; sva-bhāvaḥ—nature; pṛichchhāmi—I am asking; tvām—to you; dharma—duty; sammūḍha—confused; chetāḥ—in heart; yat—what; śhreyaḥ—best; syāt—may be; niśhchitam—decisively; brūhi—tell; tat—that; me—to me; śhiṣhyaḥ—disciple; te—your; aham—I; śhādhi—please instruct; mām—me; tvām—unto you; prapannam—surrendered'::text),'My heart is overpowered by the taint of pity; my mind is confused as to my duty. I ask Thee: Tell me decisively what is good for me. I am Thy disciple; instruct me, who has taken refuge in Thee.','Swami Sivananda','2.7 कार्पण्यदोषोपहतस्वभावः with nature overpowered by the taint of pity? पृच्छामि I ask? त्वाम् Thee? धर्मसंमूढचेताः with a mind in confusion about duty? यत् which? श्रेयः good? स्यात् may be? निश्चितम् decisively? ब्रूहि say? तत् that? मे for me? शिष्यः disciple? ते Thy? अहम् I? शाधि teach? माम् me? त्वाम् to Thee? प्रपन्नम् taken refuge.No commentary.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',8,55,'2-8','न हि प्रपश्यामि ममापनुद्या

द्यच्छोकमुच्छोषणमिन्द्रियाणाम्।

अवाप्य भूमावसपत्नमृद्धम्

राज्यं सुराणामपि चाधिपत्यम्।।2.8।।','na hi prapaśhyāmi mamāpanudyād
yach-chhokam uchchhoṣhaṇam-indriyāṇām
avāpya bhūmāv-asapatnamṛiddhaṁ
rājyaṁ surāṇāmapi chādhipatyam',to_json('na—not; hi—certainly; prapaśhyāmi—I see; mama—my; apanudyāt—drive away; yat—which; śhokam—anguish; uchchhoṣhaṇam—is drying up; indriyāṇām—of the senses; avāpya—after achieving; bhūmau—on the earth; asapatnam—unrivalled; ṛiddham—prosperous; rājyam—kingdom; surāṇām—like the celestial gods; api—even; cha—also; ādhipatyam—sovereignty'::text),'I do not see that this sorrow that burns up my senses would be removed, even if I were to attain prosperous and unrivaled dominion on earth or lordship over the gods.','Swami Sivananda','2.8 न हि not? प्रपश्यामि I see? मम my? अपनुद्यात् would remove? यत् that? शोकम् grief? उच्छोषणम् drying up? इन्द्रियाणाम् of my senses? अवाप्य having obtained? भूमौ on the earth? असपत्नम् unrivalled? ऋद्धम् prosperous? राज्यम् dominion? सुराणाम् over the gods? अपि even? च and? आधिपत्यम् lordship.No commentary.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',9,56,'2-9','सञ्जय उवाच

एवमुक्त्वा हृषीकेशं गुडाकेशः परन्तप।

न योत्स्य इति गोविन्दमुक्त्वा तूष्णीं बभूव ह।।2.9।।','sañjaya uvācha
evam-uktvā hṛiṣhīkeśhaṁ guḍākeśhaḥ parantapa
na yotsya iti govindam uktvā tūṣhṇīṁ babhūva ha',to_json('sañjayaḥ uvācha—Sanjay said; evam—thus; uktvā—having spoken; hṛiṣhīkeśham—to Shree Krishna, the master of the mind and senses; guḍākeśhaḥ—Arjun, the conquerer of sleep; parantapaḥ—Arjun, the chastiser of the enemies; na yotsye—I shall not fight; iti—thus; govindam—Krishna, the giver of pleasure to the senses; uktvā—having addressed; tūṣhṇīm—silent; babhūva—became ha'::text),'Sanjaya said: Having spoken thus to Hrishikesha, the Lord of the senses, Arjuna, the conqueror of sleep and destroyer of foes, said, "I will not fight," and became silent.','Swami Sivananda','2.9 एवम् thus? उक्त्वा having spoken? हृषीकेशम् to Hrishikesha? गुडाकेशः Arjuna (the coneror of sleep)? परन्तप destroyer of foes? न योत्स्ये I will not fight? इति thus? गोविन्दम् to Govinda? उक्त्वा having said? तूष्णीम् silent? बभूव ह became.No commentary.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',10,57,'2-10','तमुवाच हृषीकेशः प्रहसन्निव भारत।

सेनयोरुभयोर्मध्ये विषीदन्तमिदं वचः।।2.10।।','tam-uvācha hṛiṣhīkeśhaḥ prahasanniva bhārata
senayorubhayor-madhye viṣhīdantam-idaṁ vachaḥ',to_json('tam—to him; uvācha—said; hṛiṣhīkeśhaḥ—Shree Krishna, the master of mind and senses; prahasan—smilingly; iva—as if; bhārata—Dhritarashtra, descendant of Bharat; senayoḥ—of the armies; ubhayoḥ—of both; madhye—in the midst of; viṣhīdantam—to the grief-stricken; idam—this; vachaḥ—words'::text),'To him who was despondent in the midst of the two armies, Krishna, smiling, O Bharata, spoke these words.','Swami Sivananda','2.10 तम् to him? उवाच spoke? हृषीकेशः Hrishikesha? प्रहसन् smiling? इव as it were? भारत O Bharata? सेनयोः of the armies? उभयोः (of) both? मध्ये in the middle? विषीदन्तम् despondent? इदम् this? वचः word.No commentary.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',11,58,'2-11','श्री भगवानुवाच

अशोच्यानन्वशोचस्त्वं प्रज्ञावादांश्च भाषसे।

गतासूनगतासूंश्च नानुशोचन्ति पण्डिताः।।2.11।।','śhrī bhagavān uvācha
aśhochyān-anvaśhochas-tvaṁ prajñā-vādānśh cha bhāṣhase
gatāsūn-agatāsūnśh-cha nānuśhochanti paṇḍitāḥ',to_json('śhrī-bhagavān uvācha—the Supreme Lord said; aśhochyān—not worthy of grief; anvaśhochaḥ—are mourning; tvam—you; prajñā-vādān—words of wisdom; cha—and; bhāṣhase—speaking; gata āsūn—the dead; agata asūn—the living; cha—and; na—never; anuśhochanti—lament; paṇḍitāḥ—the wise'::text),'The Blessed Lord said, "You have grieved for those who should not be grieved for; yet, you speak words of wisdom. The wise grieve neither for the living nor for the dead."','Swami Sivananda','2.11 अशोच्यान् those who should not be grieved for? अन्वशोचः hast grieved? त्वम् thou? प्रज्ञावादान् words of wisdom? च and? भाषसे speakest? गतासून् the dead? अगतासून् the living? च and? न अनुशोचन्ति grieve not? पण्डिताः the wise.Commentary -- The philosophy of the Gita begins from this verse.Bhishma and Drona deserve no grief because they are eternal in their real nature and they are virtuous men who possess very good conduct. Though you speak words of wisdom? you are unwise because you grieve for those who are really eternal and who deserve no grief. They who are endowed with the knowledge of the Self are wise men. They will not grieve for the living or for the dead because they know well that the Self is immortal and that It is unborn. They also know that there is no such a thing as death? that it is a separation of the astral body from the physical? that death is nothing more than a disintegration of matter and that the five elements of which the body is composed return to their source. Arjuna had forgotten the eternal nature of the Soul and the changing nature of the body. Because of his ignorance? he began to act as if the temporary relations with kinsmen? teachers? etc.? were permanent. He forgot that his relations with this world in his present life were the results of past actions. These? when exhausted? end all relationship and new ones ones crop up when one takes on another body.The result of past actions is known as karm and that portion of the karma which gave rise to the present incarnation is known as prarabdha karma.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',12,59,'2-12','न त्वेवाहं जातु नासं न त्वं नेमे जनाधिपाः।

न चैव न भविष्यामः सर्वे वयमतः परम्।।2.12।।','na tvevāhaṁ jātu nāsaṁ na tvaṁ neme janādhipāḥ
na chaiva na bhaviṣhyāmaḥ sarve vayamataḥ param',to_json('na—never; tu—however; eva—certainly; aham—I; jātu—at any time; na—nor; āsam—exist; na—nor; tvam—you; na—nor; ime—these; jana-adhipāḥ—kings; na—never; cha—also; eva—indeed; na bhaviṣhyāmaḥ—shall not exist; sarve vayam—all of us; ataḥ—from now; param—after'::text),'Nor, at any time, was I not, nor thou, nor these rulers of men; nor, verily, shall we ever cease to be hereafter.','Swami Sivananda','2.12 न not? तु indeed? एव also? अहम् I? जातु at any time? न not? आसम् was? न not? त्वम् thou? न not? इमे these? जनाधिपाः rulers of men? न not? च and? एव also? न not? भविष्यामः shall be? सर्वे all? वयम् we? अतः from this time? परम् after.Commentary -- Lord Krishna speaks here of the immortality of the Soul or the imperishable nature of the Self (Atman). The Soul exists in the three periods of time (past? present and future). Man continues to exist even after the death of the physical body. There is life beyond.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',13,60,'2-13','देहिनोऽस्मिन्यथा देहे कौमारं यौवनं जरा।

तथा देहान्तरप्राप्तिर्धीरस्तत्र न मुह्यति।।2.13।।','dehino ’smin yathā dehe kaumāraṁ yauvanaṁ jarā
tathā dehāntara-prāptir dhīras tatra na muhyati',to_json('dehinaḥ—of the embodied; asmin—in this; yathā—as; dehe—in the body; kaumāram—childhood; yauvanam—youth; jarā—old age; tathā—similarly; deha-antara—another body; prāptiḥ—achieves; dhīraḥ—the wise; tatra—thereupon; na muhyati—are not deluded'::text),'Just as the embodied soul passes through childhood, youth, and old age in this body, so too does it pass into another body; the steadfast one does not grieve over this.','Swami Sivananda','2.13 देहिनः of the embodied (soul)? अस्मिन् in this? यथा as? देहे in body? कौमारम् childhood? यौवनम् youth? जरा old age? तथा so also? देहान्तरप्राप्तिः the attaining of another body? धीरः the firm? तत्र thereat? न not? मुह्यति grieves.Commentary -- Just as there is no interruption in the passing of childhood into youth and youth into old age in this body? so also there is no interruption by death in the continuity of the ego. The Self is not dead at the termination of the stage? viz.? childhood. It is certainly not born again at the beginning of the second stage? viz.? youth. Just as the Self passes unchanged from childhood to youth and from yourth to old age? so also the Self passes unchanged from one body into,another. Therefore? the wise man is not at all distressed about it.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',14,61,'2-14','मात्रास्पर्शास्तु कौन्तेय शीतोष्णसुखदुःखदाः।

आगमापायिनोऽनित्यास्तांस्तितिक्षस्व भारत।।2.14।।','mātrā-sparśhās tu kaunteya śhītoṣhṇa-sukha-duḥkha-dāḥ
āgamāpāyino ’nityās tans-titikṣhasva bhārata',to_json('mātrā-sparśhāḥ—contact of the senses with the sense objects; tu—indeed; kaunteya—Arjun, the son of Kunti; śhīta—winter; uṣhṇa—summer; sukha—happiness; duḥkha—distress; dāḥ—give; āgama—come; apāyinaḥ—go; anityāḥ—non-permanent; tān—them; titikṣhasva—tolerate; bhārata—descendant of the Bharat'::text),'The contact of the senses with the objects, O son of Kunti, which causes heat and cold, pleasure and pain, has a beginning and an end; they are impermanent; endure them bravely, O Arjuna.','Swami Sivananda','2.14 मात्रास्पर्शाः contacts of senses with objects? तु indeed? कौन्तेय O Kaunteya (son of Kunti)? शीतोष्णसुखदुःखदाः producers of cold and heat? pleasure and pain? आगमापायिनः with beginning and end? अनित्याः impermanent? तान् them? तितिक्षस्व bear (thou)? भारत O Bharata.Commentary -- Cold is pleasant at one time and painful at another. Heat is pleasant in winter but painful in summer. The same object that gives pleasure at one time gives pain at another time. So the sensecontacts that give rise to the sensations of heat and cold? pleasure and pain come and go. Therefore? they are impermanent in nature. The objects come in contact with the senses or the Indriyas? viz.? skin? ear? eye? nose? etc.? and the sensations are carried by the nerves to the mind which has its seat in the brain. It is the mind that feels pleasure and pain. One should try to bear patiently heat and cold? pleasure and pain and develop a balanced state of mind. (Cf.V.22)','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',15,62,'2-15','यं हि न व्यथयन्त्येते पुरुषं पुरुषर्षभ।

समदुःखसुखं धीरं सोऽमृतत्वाय कल्पते।।2.15।।','yaṁ hi na vyathayantyete puruṣhaṁ puruṣharṣhabha
sama-duḥkha-sukhaṁ dhīraṁ so ’mṛitatvāya kalpate',to_json('yam—whom; hi—verily; na—not; vyathayanti—distressed; ete—these; puruṣham—person; puruṣha-ṛiṣhabha—the noblest amongst men, Arjun; sama—equipoised; duḥkha—distress; sukham—happiness; dhīram—steady; saḥ—that person; amṛitatvāya—for liberation; kalpate—becomes eligible'::text),'That firm man, whom surely these afflictions do not, O chief among men, to whom pleasure and pain are the same, is fit for attaining immortality.','Swami Sivananda','2.15 यम् whom? हि surely? न व्यथयन्ति afflict not? एते these? पुरुषम् man? पुरुषर्षभ chief among men? समदुःखसुखम् same in pleasure and pain? धीरम् firm man? सः he? अमृतत्वाय for immortality? कल्पते is fit.Commentary -- Dehadhyasa or identification of the Self with the body is the cause of pleasure and pain. The more you are able to identify yourself with the immortal? allpervading Self? the less will you be affected by the pairs of opposites (Dvandvas? pleasure and pain? etc.)Titiksha or the power of endurance develops the willpower. Calm endurance in pleasure and pain? and heat and cold is one of the alifications of an aspirant on the path of Jnana Yoga. It is one of the Shatsampat or sixfold virtues. It is a condition of right knowledge. Titiksha by itself cannot give you Moksha or liberation? but still? when coupled with discrimination and dispassion? it becomes a means to the attainment of Immortality or knowledge of the Self. (Cf.XVII.53)','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',16,63,'2-16','नासतो विद्यते भावो नाभावो विद्यते सतः।

उभयोरपि दृष्टोऽन्तस्त्वनयोस्तत्त्वदर्शिभिः।।2.16।।','nāsato vidyate bhāvo nābhāvo vidyate sataḥ
ubhayorapi dṛiṣhṭo ’nta stvanayos tattva-darśhibhiḥ',to_json('na—no; asataḥ—of the temporary; vidyate—there is; bhāvaḥ—is; na—no; abhāvaḥ—cessation; vidyate—is; sataḥ—of the eternal; ubhayoḥ—of the two; api—also; dṛiṣhṭaḥ—observed; antaḥ—conclusion; tu—verily; anayoḥ—of these; tattva—of the truth; darśhibhiḥ—by the seers'::text),'The unreal has no being; there is no non-being of the real; the truth about both has been seen by the knowers of the truth (or the seers of the essence).','Swami Sivananda','2.16 न not? असतः of the unreal? विद्यते is? भावः being? न not? अभावः nonbeing? विद्यते is? सतः of the real? उभयोः of the two? अपि also? दृष्टः (has been) seen? अन्तः the final truth? तु indeed? अनयोः of these? तत्त्वदर्शिभिः by the knowers of the Truth.Commentary -- The changeless? homogeneous Atman or the Self always exists. It is the only solid Reality. This phenomenal world of names and forms is ever changing. Hence it is unreal. The sage or the Jivanmukta is fully aware that the Self always exists and that this world is like a mirage. Through his Jnanachakshus or the eye of intuition? he directly cognises the Self. This world vanishes for him like the snake in the rope? after it has been seen that only the rope exists. He rejects the names and forms and takes the underlying Essence in all the names and forms? viz.? AstiBhatiPriya or Satchidananda or ExistenceKnowledgeBliss Absolute. Hence he is a Tattvadarshi or a knower of the Truth or the Essence.What is changing must be unreal. What is constant or permanent must be real.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',17,64,'2-17','अविनाशि तु तद्विद्धि येन सर्वमिदं ततम्।

विनाशमव्ययस्यास्य न कश्चित् कर्तुमर्हति।।2.17।।','avināśhi tu tadviddhi yena sarvam idaṁ tatam
vināśham avyayasyāsya na kaśhchit kartum arhati',to_json('avināśhi—indestructible; tu—indeed; tat—that; viddhi—know; yena—by whom; sarvam—entire; idam—this; tatam—pervaded; vināśham—destruction; avyayasya—of the imperishable; asya—of it; na kaśhchit—no one; kartum—to cause; arhati—is able'::text),'Know that to be indestructible, by which all this is pervaded. No one can cause the destruction of that, the Imperishable.','Swami Sivananda','',NULL,now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',18,65,'2-18','अन्तवन्त इमे देहा नित्यस्योक्ताः शरीरिणः।

अनाशिनोऽप्रमेयस्य तस्माद्युध्यस्व भारत।।2.18।।','antavanta ime dehā nityasyoktāḥ śharīriṇaḥ
anāśhino ’prameyasya tasmād yudhyasva bhārata',to_json('anta-vantaḥ—having an end; ime—these; dehāḥ—material bodies; nityasya—eternally; uktāḥ—are said; śharīriṇaḥ—of the embodied soul; anāśhinaḥ—indestructible; aprameyasya—immeasurable; tasmāt—therefore; yudhyasva—fight; bhārata—descendant of Bharat, Arjun'::text),'These bodies of the embodied Self, which are eternal, indestructible, and immeasurable, are said to have an end. Therefore, fight, O Arjuna.','Swami Sivananda','2.18 अन्तवन्तः having an end? इमे these? देहाः bodies? नित्यस्य of the everlasting? उक्ताः are said? शरीरिणः of the embodied? अनाशिनः of the indestructible? अप्रमेयस्य of the immesaurable? तस्मात् therefore? युध्यस्व fight? भारत O Bharata.Commentary -- Lord Krishna explains to Arjuna the nature of the allpervading? immortal Self in a variety of ways and thus induces him to fight by removing his delusion? grief and despondency which are born of ignorance.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',19,66,'2-19','य एनं वेत्ति हन्तारं यश्चैनं मन्यते हतम्।

उभौ तौ न विजानीतो नायं हन्ति न हन्यते।।2.19।।','ya enaṁ vetti hantāraṁ yaśh chainaṁ manyate hatam
ubhau tau na vijānīto nāyaṁ hanti na hanyate',to_json('yaḥ—one who; enam—this; vetti—knows; hantāram—the slayer; yaḥ—one who; cha—and; enam—this; manyate—thinks; hatam—slain; ubhau—both; tau—they; na—not; vijānītaḥ—in knowledge; na—neither; ayam—this; hanti—slays; na—nor; hanyate—is killed'::text),'He who takes the Self to be the slayer and he who thinks it is slain, neither of them knows. It does not slay, nor is it slain.','Swami Sivananda','2.19 यः he who? एनम् this (Self)? वेत्ति knows? हन्तारम् slayer? यः he who? च and? एनम् this? मन्यते thinks? हतम् slain? उभौ both? तौ those? न not? विजानीतः know? न not? अयम् this? हन्ति slays? न not? हन्यते is slain.Commentary -- The Self is nondoer (Akarta) and as It is immutable? It is neither the agent nor the object of the act of slaying. He who thinks I slay or I am slain with the body or the Ahamkara (ego)? he does not really comprehend the true nature of the Self. The Self is indestructible. It exists in the three periods of time. It is Sat (Existence). When the body is destroyed? the Self is not destroyed. The body has to undergo change in any case. It is inevitable. But the Self is not at all affected by it. Verses 19? 20? 21? 23 and 24 speak of the immortality of the Self or Atman. (Cf.XVIII.17)','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',20,67,'2-20','न जायते म्रियते वा कदाचि

न्नायं भूत्वा भविता वा न भूयः।

अजो नित्यः शाश्वतोऽयं पुराणो

न हन्यते हन्यमाने शरीरे।।2.20।।','na jāyate mriyate vā kadāchin
nāyaṁ bhūtvā bhavitā vā na bhūyaḥ
ajo nityaḥ śhāśhvato ’yaṁ purāṇo
na hanyate hanyamāne śharīre',to_json('na jāyate—is not born; mriyate—dies; vā—or; kadāchit—at any time; na—not; ayam—this; bhūtvā—having once existed; bhavitā—will be; vā—or; na—not; bhūyaḥ—further; ajaḥ—unborn; nityaḥ—eternal; śhāśhvataḥ—immortal; ayam—this; purāṇaḥ—the ancient; na hanyate—is not destroyed; hanyamāne—is destroyed; śharīre—when the body'::text),'It is not born, nor does it ever die; after having been, it again does not cease to be; unborn, eternal, changeless, and ancient, it is not killed when the body is killed.','Swami Sivananda','2.20 न not? जायते is born? म्रियते dies? वा or? कदाचित् at any time? न not? अयम् this (Self)? भूत्वा having been? भविता will be? वा or? न not? भूयः (any) more? अजः unborn? नित्यः eternal? शाश्वतः changeless? अयम् this? पुराणः ancient? न not? हन्यते is killed? हन्यमाने being killed? शरीरे in body.Commentary This Self (Atman) is destitute of the six types of transformation or BhavaVikaras such as birth? existence? growth? transformation? decline and death. As It is indivisible (Akhanda). It does not diminish in size. It neither grows nor does It decline. It is ever the same. Birth and death are for the physical body only. Birth and death cannot touch the immortal? allpervading Self.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',21,68,'2-21','वेदाविनाशिनं नित्यं य एनमजमव्ययम्।

कथं स पुरुषः पार्थ कं घातयति हन्ति कम्।।2.21।।','vedāvināśhinaṁ nityaṁ ya enam ajam avyayam
kathaṁ sa puruṣhaḥ pārtha kaṁ ghātayati hanti kam',to_json('veda—knows; avināśhinam—imperishable; nityam—eternal; yaḥ—who; enam—this; ajam—unborn; avyayam—immutable; katham—how; saḥ—that; puruṣhaḥ—person; pārtha—Parth; kam—whom; ghātayati—causes to be killed; hanti—kills; kam—whom'::text),'Whoever knows it to be indestructible, eternal, unborn, and inexhaustible, how can that person slay, O Arjuna, or cause to be slain?','Swami Sivananda','2.21 वेद knows? अविनाशिनम् indestructible? नित्यम् eternal? यः who? एनम् this (Self)? अजम् unborn? अव्ययम् inexhaustible? कथम् how? सः he (that)? पुरुषः man? पार्थ O Partha (son of Pritha)? कम् whom? घातयति causes to be slain? हन्ति kills? कम् whom.Commentary The enlightened sage who knows the immutable and indestructible Self through direct cognition or spiritual Anubhava (experience) cannot do the act of slaying. He cannot cause another to slay also.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',22,69,'2-22','वासांसि जीर्णानि यथा विहाय

नवानि गृह्णाति नरोऽपराणि।

तथा शरीराणि विहाय जीर्णा

न्यन्यानि संयाति नवानि देही।।2.22।।','vāsānsi jīrṇāni yathā vihāya
navāni gṛihṇāti naro ’parāṇi
tathā śharīrāṇi vihāya jīrṇānya
nyāni sanyāti navāni dehī',to_json('vāsānsi—garments; jīrṇāni—worn-out; yathā—as; vihāya—sheds; navāni—new; gṛihṇāti—accepts; naraḥ—a person; aparāṇi—others; tathā—likewise; śharīrāṇi—bodies; vihāya—casting off; jirṇāni—worn-out; anyāni—other; sanyāti—enters; navāni—new; dehī—the embodied soul'::text),'Just as a man casts off worn-out clothes and puts on new ones, so too the embodied Self casts off worn-out bodies and enters others that are new.','Swami Sivananda','2.22 वासांसि clothes? जीर्णानि worn out? यथा as? विहाय having cast away? नवानि new? गृह्णाति takes? नरः man? अपराणि others? तथा so? शरीराणि bodies? विहाय having cast away? जीर्णानि wornout? अन्यानि others? संयाति enters? नवानि new? देही the embodied (one).No commentary.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',23,70,'2-23','नैनं छिन्दन्ति शस्त्राणि नैनं दहति पावकः।

न चैनं क्लेदयन्त्यापो न शोषयति मारुतः।।2.23।।','nainaṁ chhindanti śhastrāṇi nainaṁ dahati pāvakaḥ
na chainaṁ kledayantyāpo na śhoṣhayati mārutaḥ',to_json('na—not; enam—this soul; chhindanti—shred; śhastrāṇi—weapons; na—nor; enam—this soul; dahati—burns; pāvakaḥ—fire; na—not; cha—and; enam—this soul; kledayanti—moisten; āpaḥ—water; na—nor; śhoṣhayati—dry; mārutaḥ—wind'::text),'Weapons cannot cut it, fire cannot burn it, water cannot wet it, wind cannot dry it.','Swami Sivananda','2.23 न not? एनम् this (Self)? छिन्दन्ति cut? शस्त्राणि weapons? न not? एनम् this? दहति burns? पावकः fire? न not?,च and? एनम् this? क्लेदयन्ति wet? आपः waters? न not? शोषयति dries? मारुतः wind.Commentary The Self is indivisible. It has no parts. It is extremely subtle. It is infinite. Therefore? sword cannot cut It fire cannot burn It water cannot wet It wind cannot dry It.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',24,71,'2-24','अच्छेद्योऽयमदाह्योऽयमक्लेद्योऽशोष्य एव च।

नित्यः सर्वगतः स्थाणुरचलोऽयं सनातनः।।2.24।।','achchhedyo ’yam adāhyo ’yam akledyo ’śhoṣhya eva cha
nityaḥ sarva-gataḥ sthāṇur achalo ’yaṁ sanātanaḥ',to_json('achchhedyaḥ—unbreakable; ayam—this soul; adāhyaḥ—incombustible; ayam—this soul; akledyaḥ—cannot be dampened; aśhoṣhyaḥ—cannot be dried; eva—indeed; cha—and; nityaḥ—everlasting; sarva-gataḥ—all-pervading; sthāṇuḥ—unalterable; achalaḥ—immutable; ayam—this soul; sanātanaḥ—primordial'::text),'This Self cannot be cut, burned, wetted, nor dried up; it is eternal, all-pervasive, stable, immovable, and ancient.','Swami Sivananda','2.24 अच्छेद्यः cannot be cut? अयम् this (Self)? अदाह्यः cannot be burnt? अयम् this? अक्लेद्यः cannot be wetted? अशोष्यः cannot be died? एव also? च and? नित्यः eternal? सर्वगतः allpervading? स्थाणुः stable? अचलः immovable? अयम् this? सनातनः ancient.Commentary The Self is very subtle. It is beyond the reach of speech and mind. It is very difficult to understand this subtle Self. So Lord Krishna explains the nature of the immortal Self in a variety of ways with various illustrations and examples? so that It can be grasped by the people.Sword cannot cut this Self. It is eternal. Because It is eternal? It is allpervading. Because It is allpervading? It is stable like a stature. Because It is stable? It is immovable. It is everlasting. Therefore? It is not produced out of any cause. It is not new. It is ancient.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',25,72,'2-25','अव्यक्तोऽयमचिन्त्योऽयमविकार्योऽयमुच्यते।

तस्मादेवं विदित्वैनं नानुशोचितुमर्हसि।।2.25।।','avyakto ’yam achintyo ’yam avikāryo ’yam uchyate
tasmādevaṁ viditvainaṁ nānuśhochitum arhasi',to_json('avyaktaḥ—unmanifested; ayam—this soul; achintyaḥ—inconceivable; ayam—this soul; avikāryaḥ—unchangeable; ayam—this soul; uchyate—is said; tasmāt—therefore; evam—thus; viditvā—having known; enam—this soul; na—not; anuśhochitum—to grieve; arhasi—befitting'::text),'This Self is said to be unmanifested, unthinkable, and unchangeable. Therefore, knowing this to be so, you should not grieve.','Swami Sivananda','2.25 अव्यक्तः unmanifested? अयम् this (Self)? अचिन्त्यः unthinkable? अयम् this? अविकार्यः unchangeable? अयम् this? उच्यते is said? तस्मात् therefore? एवम् thus? विदित्वा having known? एनम् this? न not? अनुशोचितुम् to grieve? अर्हसि (thou) oughtest.Commentary The Self is not an object of perception. It can hardly be seen by the physical eyes. Therefore? the Self is unmanifested. That which is seen by the eyes becomes an object of thought. As the Self cannot be perceived by the eyes? It is unthinkable. Milk when mixed with buttermilk changes its form. The Self cannot change Its form like milk. Hence? It is changeless and immutable. Therefore? thus understanding the Self? thou shouldst not mourn. Thou shouldst not think also that thou art their slayer and that they are killed by thee.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',26,73,'2-26','अथ चैनं नित्यजातं नित्यं वा मन्यसे मृतम्।

तथापि त्वं महाबाहो नैवं शोचितुमर्हसि।।2.26।।','atha chainaṁ nitya-jātaṁ nityaṁ vā manyase mṛitam
tathāpi tvaṁ mahā-bāho naivaṁ śhochitum arhasi',to_json('atha—if, however; cha—and; enam—this soul; nitya-jātam—taking constant birth; nityam—always; vā—or; manyase—you think; mṛitam—dead; tathā api—even then; tvam—you; mahā-bāho—mighty-armed one, Arjun; na—not; evam—like this; śhochitum—grieve; arhasi—befitting'::text),'But even if thou thinkest of It as constantly being born and constantly dying, even then, O mighty-armed one, thou shouldst not grieve.','Swami Sivananda','2.26 अथ now? च and? एनम् this (Self)? नित्यजातम् constantly born? नित्यम् constantly? वा or? मन्यसे thinkest? मृतम् dead? तथापि even then? त्वम् thou? महाबाहो mightyarmed? न not? एवम् thus? शोचितुम् to grieve? अर्हसि (thou) oughtest.Commentary Lord Krishna here? for the sake of argument? takes up the popular supposition. Granting that the Self is again and again born whenever a body comes into being? and again and again dies whenever the body dies? O mightyarmed (O Arjuna of great valour and strength)? thou shouldst not grieve thus? because birth is inevitable to want is dead and death is inevitable to what is born. This is the inexorable or unrelenting Law of Nature.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',27,74,'2-27','जातस्य हि ध्रुवो मृत्युर्ध्रुवं जन्म मृतस्य च।

तस्मादपरिहार्येऽर्थे न त्वं शोचितुमर्हसि।।2.27।।','jātasya hi dhruvo mṛityur dhruvaṁ janma mṛitasya cha
tasmād aparihārye ’rthe na tvaṁ śhochitum arhasi',to_json('jātasya—for one who has been born; hi—for; dhruvaḥ—certain; mṛityuḥ—death; dhruvam—certain; janma—birth; mṛitasya—for the dead; cha—and; tasmāt—therefore; aparihārye arthe—in this inevitable situation; na—not; tvam—you; śhochitum—lament; arhasi—befitting'::text),'For the born, death is certain, and for the dead, birth is certain; therefore, you should not grieve over the inevitable.','Swami Sivananda','2.27 जातस्य of the born? हि for? ध्रुवः certain? मृत्युः death? ध्रुवम् certain? जन्म birth? मृतस्य of the dead? च and? तस्मात् therefore? अपरिहार्ये inevritable? अर्थे in matter? न not? त्वम् thou? शोचितुम् to grieve? अर्हसि (thou) oughtest.Commentary Birth is sure to happen to that which is dead death is sure to happen to what which is born. Birth and death are certainly unavoidable. Therefore? you should not grieve over an inevitable matter.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',28,75,'2-28','अव्यक्तादीनि भूतानि व्यक्तमध्यानि भारत।

अव्यक्तनिधनान्येव तत्र का परिदेवना।।2.28।।','avyaktādīni bhūtāni vyakta-madhyāni bhārata
avyakta-nidhanānyeva tatra kā paridevanā',to_json('avyakta-ādīni—unmanifest before birth; bhūtāni—created beings; vyakta—manifest; madhyāni—in the middle; bhārata—Arjun, scion of Bharat; avyakta—unmanifest; nidhanāni—on death; eva—indeed; tatra—therefore; kā—why; paridevanā—grieve'::text),'Beings are unmanifest in their beginning, manifest in their middle state, O Arjuna, and unmanifest again in their end. What is there to grieve about?','Swami Sivananda','2.28 अव्यक्तादीनि unmanifested in the beginning? भूतानि beings? व्यक्तमध्यानि manifested in their middle state? भारत O Bharata? अव्यक्तनिधनानि unmanifested again in the end? एव also? तत्र there? का what? परिदेवना grief.Commentary The physical body is a combination of the five elements. It is seen by the physical eyes only after the five elements have entered into such combination. After death? the body disintegrates and the five elements go back to their source it cannot be seen. Therefore? the body can be seen only in the middle state. The relationship as son? friend? teacher? father? mother? wife? brother and sister is formed through the body on account of attachment and Moha (delusion). Just as planks unite and separate in a river? just as pilgrims unite and separate in a public inn? so also fathers? mothers? sons and brothers unite and separate in this world. This world is a very big public inn. People unite and separate.There is no pot in the beginning and in the end. Even if you see the pot in the middle? you should think and feel that it is illusory and does not really exist. So also there is no body in the beginning and in the end. That which does not exist in the beginning and in the end must be illusory in the middle also. You must think and feel that the body does not really exist in the middle as well.He who thus understands the nature of the body and all human relationships based on it? will not grieve.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',29,76,'2-29','आश्चर्यवत्पश्यति कश्चिदेन

माश्चर्यवद्वदति तथैव चान्यः।

आश्चर्यवच्चैनमन्यः श्रृणोति

श्रुत्वाप्येनं वेद न चैव कश्चित्।।2.29।।','āśhcharya-vat paśhyati kaśhchid enan
āśhcharya-vad vadati tathaiva chānyaḥ
āśhcharya-vach chainam anyaḥ śhṛiṇoti
śhrutvāpyenaṁ veda na chaiva kaśhchit',to_json('āśhcharya-vat—as amazing; paśhyati—see; kaśhchit—someone; enam—this soul; āśhcharya-vat—as amazing; vadati—speak of; tathā—thus; eva—indeed; cha—and; anyaḥ—other; āśhcharya-vat—similarly amazing; cha—also; enam—this soul; anyaḥ—others; śhṛiṇoti—hear; śhrutvā—having heard; api—even; enam—this soul; veda—understand; na—not; cha—and; eva—even; kaśhchit—some'::text),'One sees this (the Self) as a wonder; another speaks of it as a wonder; another hears of it as a wonder; yet, having heard, none understands it at all.','Swami Sivananda','2.29 आश्चर्यवत् as a wonder? पश्यति sees? कश्चित् sone one? एनम् this (Self)? आश्चर्यवत् as a wonder? वदति speaks of? तथा so? एव also? च and? अन्यः another? आश्चर्यवत् as a wonder? च and? एनम् this? अन्यः another? श्रृणोति hears? श्रुत्वा having heard? अपि even? एनम् this? वेद knows? न not? च and? एव also? कश्चित् any one.Commentary The verse may also be interpreted in this manner. He that sees? hears and speaks of the Self is a wonderful man. Such a man is very rare. He is one among many thousands. Thus the Self is very hard to understand.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',30,77,'2-30','देही नित्यमवध्योऽयं देहे सर्वस्य भारत।

तस्मात्सर्वाणि भूतानि न त्वं शोचितुमर्हसि।।2.30।।','dehī nityam avadhyo ’yaṁ dehe sarvasya bhārata
tasmāt sarvāṇi bhūtāni na tvaṁ śhochitum arhasi',to_json('dehī—the soul that dwells within the body; nityam—always; avadhyaḥ—immortal; ayam—this soul; dehe—in the body; sarvasya—of everyone; bhārata—descendant of Bharat, Arjun; tasmāt—therefore; sarvāṇi—for all; bhūtāni—living entities; na—not; tvam—you; śhochitum—mourn; arhasi—should'::text),'This indweller in the body of everyone is ever indestructible, O Arjuna; therefore, you should not grieve for any creature.','Swami Sivananda','2.30 देही indweller? नित्यम् always? अवध्यः indestructible? अयम् this? देहे in the body? सर्वस्य of all? भारत O Bharata? तस्मात् therefore? सर्वाणि (for) all? भूतानि creatures? न not? त्वम् thou? शोचितुम् to grieve? अर्हसि (thou) shouldst.Commentary The body of any creature may be destroyed but the Self cannot be killed. Therefore you should not grieve regarding any creature whatever? Bhishma or anybody else.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',31,78,'2-31','स्वधर्ममपि चावेक्ष्य न विकम्पितुमर्हसि।

धर्म्याद्धि युद्धाछ्रेयोऽन्यत्क्षत्रियस्य न विद्यते।।2.31।।','swa-dharmam api chāvekṣhya na vikampitum arhasi
dharmyāddhi yuddhāch chhreyo ’nyat kṣhatriyasya na vidyate',to_json('swa-dharmam—one’s duty in accordance with the Vedas; api—also; cha—and; avekṣhya—considering; na—not; vikampitum—to waver; arhasi—should; dharmyāt—for righteousness; hi—indeed; yuddhāt—than fighting; śhreyaḥ—better; anyat—another; kṣhatriyasya—of a warrior; na—not; vidyate—exists'::text),'Further, having regard to your duty, you should not waver, for there is nothing higher for a Kshatriya than a righteous war.','Swami Sivananda','2.31 स्वधर्मम् own duty? अपि also? च and? अवेक्ष्य looking at? न not? विकम्पितुम् to waver? अर्हसि (thou) oughtest? धर्म्यात् than righteous? हि indeed? युद्धात् than war? श्रेयः higher? अन्यत् other? क्षत्रियस्य of a Kshatriya? न not? विद्यते is.Commentary Lord Krishna now gives to Arjuna wordly reasons for fighting. Up to this time? He talked to Arjuna on the immortality of the Self and gave him philosophical reasons. Now He says to Arjuna? O Arjuna Fighting is a Kshatriyas own duty. You ought not to swerve from that duty. To a Kshatriyta (one born in the warrior or ruling class) nothing is more welcome than a righteous war. A warrior should fight.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',32,79,'2-32','यदृच्छया चोपपन्नं स्वर्गद्वारमपावृतम्।

सुखिनः क्षत्रियाः पार्थ लभन्ते युद्धमीदृशम्।।2.32।।','yadṛichchhayā chopapannaṁ swarga-dvāram apāvṛitam
sukhinaḥ kṣhatriyāḥ pārtha labhante yuddham īdṛiśham',to_json('yadṛichchhayā—unsought; cha—and; upapannam—come; swarga—celestial abodes; dvāram—door; apāvṛitam—wide open; sukhinaḥ—happy; kṣhatriyāḥ—warriors; pārtha—Arjun, the son of Pritha; labhante—obtain; yuddham—war; īdṛiśham—such'::text),'Happy are the Kshatriyas, O Arjuna! who are called to fight in such a battle that comes of its own accord as an open door to heaven.','Swami Sivananda','2.32 यदृच्छया of itself? च and? उपपन्नम् come? स्वर्गद्वारम् the gate of heaven? अपावृतम् opened? सुखिनः happy? क्षत्रियाः Kshatriyas? पार्थ O Partha? लभन्ते obtain? युद्धम् battle? ईदृशम् such.Commentary The scriptures declare that if a Kshatriya dies for a righteous cause on the battlefield? he at once goes to heaven.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',33,80,'2-33','अथ चैत्त्वमिमं धर्म्यं संग्रामं न करिष्यसि।

ततः स्वधर्मं कीर्तिं च हित्वा पापमवाप्स्यसि।।2.33।।','atha chet tvam imaṁ dharmyaṁ saṅgrāmaṁ na kariṣhyasi
tataḥ sva-dharmaṁ kīrtiṁ cha hitvā pāpam avāpsyasi',to_json('atha chet—if, however; tvam—you; imam—this; dharmyam saṅgrāmam—righteous war; na—not; kariṣhyasi—act; tataḥ—then; sva-dharmam—one’s duty in accordance with the Vedas; kīrtim—reputation; cha—and; hitvā—abandoning; pāpam—sin; avāpsyasi—will incur'::text),'But if you will not fight this righteous war, then having abandoned your own duty and reputation, you will incur sin.','Swami Sivananda','2.33 अथ चेत् but if? त्वम् thou? इमम् this? धर्म्यम् righteous? संग्रामम् warfare? न not? करिष्यसि will do? ततः,then? स्वधर्मम् own duty? कीर्तिम् fame? च and? हित्वा having abandoned? पापम् sin? अवाप्स्यसि shall incur.Commentary The Lord reminds Arjuna of the fame he had already earned and which he would now lose if he refused to fight. Arjuna had acired great fame by fighting with Lord Siva. Arjuna proceeded on a pilgrimage to the Himalayas. He fought with Siva Who appeared in the guise of a mountaineer (Kirata) and got from Him the Pasupatastra? a celestial weapon.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',34,81,'2-34','अकीर्तिं चापि भूतानि कथयिष्यन्ति तेऽव्ययाम्।

संभावितस्य चाकीर्तिर्मरणादतिरिच्यते।।2.34।।','akīrtiṁ chāpi bhūtāni
kathayiṣhyanti te ’vyayām
sambhāvitasya chākīrtir
maraṇād atirichyate',to_json('akīrtim—infamy; cha—and; api—also; bhūtāni—people; kathayiṣhyanti—will speak; te—of your; avyayām—everlasting; sambhāvitasya—of a respectable person; cha—and; akīrtiḥ—infamy; maraṇāt—than death; atirichyate—is greater'::text),'People will also recount your everlasting dishonor; and for one who has been honored, dishonor is worse than death.','Swami Sivananda','2.34 अकीर्तिम् dishonour? च and? अपि also? भूतानि beings? कथयिष्यन्ति will tell? ते thy? अव्ययाम् everlasting? संभावितस्य of the honoured? च and? अकीर्तिः dishonour? मरणात् than death? अतिरिच्यते exceeds.Commentary The world also will ever recount thy infamy which will survive thee for a long time. Death is really preferable to disgrace to one who has been honoured as a great hero and mighty warrior with noble alities.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',35,82,'2-35','भयाद्रणादुपरतं मंस्यन्ते त्वां महारथाः।

येषां च त्वं बहुमतो भूत्वा यास्यसि लाघवम्।।2.35।।','bhayād raṇād uparataṁ mansyante tvāṁ mahā-rathāḥ
yeṣhāṁ cha tvaṁ bahu-mato bhūtvā yāsyasi lāghavam',to_json('bhayāt—out of fear; raṇāt—from the battlefield; uparatam—have fled; maṁsyante—will think; tvām—you; mahā-rathāḥ—warriors who could single handedly match the strength of ten thousand ordinary warriors; yeṣhām—for whom; cha—and; tvam—you; bahu-mataḥ—high esteemed; bhūtvā—having been; yāsyasi—you will loose; lāghavam—decreased in value'::text),'The great chariot-warriors will think that you have withdrawn from the battle out of fear, and you will be held in low esteem by those who have held you in high regard.','Swami Sivananda','2.35 भयात् from fear? रणात् from the battle? उपरतम् withdrawn? मंस्यन्ते will think? त्वाम् thee? महारथाः the great carwarriors? येषाम् of whom? च and? त्वम् thou? बहुमतः much thought of? भूत्वा having been? यास्यसि will receive? लाघवम् lightness.Commentary Duryodhana and others will certainly think that you have fled from the battle from fear of Karna and others? but not through compassion and reverence for elders and teachers. Duryodhana and others who have shown great esteem to you on account of your chivalry? bravery and other noble alities? will think very lightly of you and treat you with contempt.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',36,83,'2-36','अवाच्यवादांश्च बहून् वदिष्यन्ति तवाहिताः।

निन्दन्तस्तव सामर्थ्यं ततो दुःखतरं नु किम्।।2.36।।','avāchya-vādānśh cha bahūn vadiṣhyanti tavāhitāḥ
nindantastava sāmarthyaṁ tato duḥkhataraṁ nu kim',to_json('avāchya-vādān—using harsh words; cha—and; bahūn—many; vadiṣhyanti—will say; tava—your; ahitāḥ—enemies; nindantaḥ—defame; tava—your; sāmarthyam—might; tataḥ—than that; duḥkha-taram—more painful; nu—indeed; kim—what'::text),'Your enemies, scoffing at your power, will speak many abusive words—what could be more painful than this?','Swami Sivananda','2.36 अवाच्यवादान् words that are improper to be spoken? च and? बहून् many? वदिष्यन्ति will say? तव thy? अहिताः enemies? निन्दन्तः cavilling? तव thy? सामर्थ्यम् power? ततः than this? दुःखतरम् more painful? नु indeed? किम् what.Commentary There is really no pain more unbearable and tormenting that that of slander thus incurred.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',37,84,'2-37','हतो वा प्राप्स्यसि स्वर्गं जित्वा वा भोक्ष्यसे महीम्।

तस्मादुत्तिष्ठ कौन्तेय युद्धाय कृतनिश्चयः।।2.37।।','hato vā prāpsyasi swargaṁ jitvā vā bhokṣhyase mahīm
tasmād uttiṣhṭha kaunteya yuddhāya kṛita-niśhchayaḥ',to_json('hataḥ—slain; vā—or; prāpsyasi—you will attain; swargam—celestial abodes; jitvā—by achieving victory; vā—or; bhokṣhyase—you shall enjoy; mahīm—the kingdom on earth; tasmāt—therefore; uttiṣhṭha—arise; kaunteya—Arjun, the son of Kunti; yuddhāya—for fight; kṛita-niśhchayaḥ—with determination'::text),'Slain, you will obtain heaven; victorious, you will enjoy the earth; therefore, stand up, O son of Kunti, resolved to fight.','Swami Sivananda','2.37 हतः slain? वा or? प्राप्स्यसि (thou) wilt obtain? स्वर्गम् heaven? जित्वा having conered? वा or? भोक्ष्यसे (thou) wilt enjoy? महीम् the earth? तस्मात् therefore? उत्तिष्ठ stand up? कौन्तेय O son of Kunti? युद्धाय for fight? कृतनिश्चयः resolved.Commentary In either case you will be benefited. Therefore? stand up with the firm resolution I will coner the enemy or die.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',38,85,'2-38','सुखदुःखे समे कृत्वा लाभालाभौ जयाजयौ।

ततो युद्धाय युज्यस्व नैवं पापमवाप्स्यसि।।2.38।।','sukha-duḥkhe same kṛitvā lābhālābhau jayājayau
tato yuddhāya yujyasva naivaṁ pāpam avāpsyasi',to_json('sukha—happiness; duḥkhe—in distress; same kṛitvā—treating alike; lābha-alābhau—gain and loss; jaya-ajayau—victory and defeat; tataḥ—thereafter; yuddhāya—for fighting; yujyasva—engage; na—never; evam—thus; pāpam—sin; avāpsyasi—shall incur'::text),'Having made pleasure and pain, gain and loss, victory and defeat equal, engage in battle for the sake of battle; thus, you shall not incur sin.','Swami Sivananda','2.38 सुखदुःखे pleasure and pain? समे same? कृत्वा having made? लाभालाभौ gain and loss? जयाजयौ victory and defeat? ततः then? युद्धाय for battle? युज्यस्व engage thou? न not? एवम् thus? पापम् sin? अवाप्स्यसि shalt incur.Commentary This is the Yoga of eanimity or the doctrine of poise in action. If anyone does any action with the above mental attitude or balanced state of mind he will not reap the fruits of his action. Such an action will lead to the purification of his heart and freedom from birth and death. One has to develop such a balanced state of mind through continous struggle and vigilant efforts.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',39,86,'2-39','एषा तेऽभिहिता सांख्ये बुद्धिर्योगे त्विमां श्रृणु।

बुद्ध्यायुक्तो यया पार्थ कर्मबन्धं प्रहास्यसि।।2.39।।','eṣhā te ’bhihitā sānkhye
buddhir yoge tvimāṁ śhṛiṇu
buddhyā yukto yayā pārtha
karma-bandhaṁ prahāsyasi',to_json('eṣhā—hitherto; te—to you; abhihitā—explained; sānkhye—by analytical knowledge; buddhiḥ yoge—by the yog of intellect; tu—indeed; imām—this; śhṛiṇu—listen; buddhyā—by understanding; yuktaḥ—united; yayā—by which; pārtha—Arjun, the son of Pritha; karma-bandham—bondage of karma; prahāsyasi—you shall be released from'::text),'This, which has been taught to you, is wisdom concerning Sankhya. Now listen to wisdom concerning Yoga, endowed with which, O Arjuna, you shall cast off the bonds of action.','Swami Sivananda','2.39 एषा this? ते to thee? अभिहिता (is) declared? सांख्ये in Sankhya? बुद्धिः wisdom? योगे in the Yoga? तु indeed? इमाम् this? श्रृणु hear? बुद्ध्या with wisdom? युक्तः endowed with? यया which? पार्थ O Partha? कर्मबन्धम् bondage of Karma? प्रहास्यसि (thou) shalt cast off.Commentary Lord Krishna taught Jnana (knowledge) to Arjuna till now. (Sankhya Yoga is the path of Vedanta or Jnana Yoga? which treats of the nature of the Atman or the Self and the methods to attain Selfrealisation. It is not the Sankhya philosophy of sage Kapila.) He is now giving to teach Arjuna the technie or secret of Karma Yoga endowed with which he (or anybody else) can break through the bonds of Karma. The Karma Yogi should perform work without expectation of fruits of his actions? without the idea of agency (or the notin I do this)? without attachment? after annihilating or going beyond all the pairs of opposites such as heat and cold? gain and loss? victoyr and defeat? etc. Dharma and Adharma? or merit and demerit will not touch that Karma Yogi who works without attachment and egoism. The Karma Yogi consecrates all his works and their fruits as offerings unto the Lord (Isvararpanam) and thus obtains the grace of the Lord (Isvaraprasada).','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',40,87,'2-40','नेहाभिक्रमनाशोऽस्ति प्रत्यवायो न विद्यते।

स्वल्पमप्यस्य धर्मस्य त्रायते महतो भयात्।।2.40।।','nehābhikrama-nāśho ’sti pratyavāyo na vidyate
svalpam apyasya dharmasya trāyate mahato bhayāt',to_json('na—not; iha—in this; abhikrama—efforts; nāśhaḥ—loss; asti—there is; pratyavāyaḥ—adverse result; na—not; vidyate—is; su-alpam—a little; api—even; asya—of this; dharmasya—occupation; trāyate—saves; mahataḥ—from great; bhayāt—danger'::text),'In this, there is no loss of effort, nor is there any harm produced, nor any transgression. Even a little of this knowledge protects one from great fear.','Swami Sivananda','2.40 न not? इह in this? अभिक्रमनाशः loss of effort? अस्ति is? प्रत्यवायः production of contrary results? न not? विद्यते is? स्वल्पम् very little? अपि even? अस्य of this? धर्मस्य duty? त्रायते protects? महतः (from) great? भयात् fear.Commentary If a religious ceremony is left uncompleted? it is a wastage as the performer cannot realise the fruits. But it is not so in the case of Karma Yoga because every action causes immediate purification of the heart.In agriculture there is uncertainty. The farmer may till the land? plough and sow the seed but he may not get a crop if there is no rain. This is not so in Karma Yoga. There is no uncertainty at all. Further? there is no chance of any harm coming out of it. In the case of medical treatment great harm will result from the doctors injudicious treatment if he uses a wrong medicine. But it is not so in the case of Karma Yoga. Anything done? however little it may be? in this path of Yoga? the Yoga of action? saves one from great fear of being caught in the wheel of birth and death. Lord Krishna here extols Karma Yoga in order to create interest in Arjuna in this Yoga.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',41,88,'2-41','व्यवसायात्मिका बुद्धिरेकेह कुरुनन्दन।

बहुशाखा ह्यनन्ताश्च बुद्धयोऽव्यवसायिनाम्।।2.41।।','vyavasāyātmikā buddhir ekeha kuru-nandana
bahu-śhākhā hyanantāśh cha buddhayo ’vyavasāyinām',to_json('vyavasāya-ātmikā—resolute; buddhiḥ—intellect; ekā—single; iha—on this path; kuru-nandana—descendent of the Kurus; bahu-śhākhāḥ—many-branched; hi—indeed; anantāḥ—endless; cha—also; buddhayaḥ—intellect; avyavasāyinām—of the irresolute'::text),'Here, O joy of the Kurus, there is only one single-pointed determination; many-branched and endless are the thoughts of the indecisive.','Swami Sivananda','2.41 व्यवसायात्मिका onepointed? बुद्धिः determination? एका single? इह here? कुरुनन्दन O joy of the Kurus? बहुशाखाः manybranched? हि indeed? अनन्ताः endless? च and? बुद्धयः thoughts? अव्यवसायिनाम् of the irresoulte.Commentary Here? in this path to Bliss there is only one thought of a resolute nature there is singleminded determination. This single thought arises from the right source of knowledge. The student of Yoga collects all the dissipated rays of the mind. He gathers all of them through discrimination? dispassion and concentration. He is free from wavering or vacillation of the mind.The worldlyminded man who is suck in the mire of Samsara has no singleminded determination. He entertains countless thoughts. His mind is always unsteady and vacillating.If thoughts cease? Samsara also ceases. Mind generates endless thoughts and this world comes into being. Thoughts? and names and forms are inseparable. If the thoughts are controlled? the mind is controlled and the Yogi is liberated.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',42,89,'2-42','यामिमां पुष्पितां वाचं प्रवदन्त्यविपश्चितः।

वेदवादरताः पार्थ नान्यदस्तीति वादिनः।।2.42।।','yāmimāṁ puṣhpitāṁ vāchaṁ pravadanty-avipaśhchitaḥ
veda-vāda-ratāḥ pārtha nānyad astīti vādinaḥ
 kāmātmānaḥ swarga-parā janma-karma-phala-pradām
kriyā-viśheṣha-bahulāṁ bhogaiśhwarya-gatiṁ prati',to_json('yām imām—all these; puṣhpitām—flowery; vācham—words; pravadanti—speak; avipaśhchitaḥ—those with limited understanding; veda-vāda-ratāḥ—attached to the flowery words of the Vedas; pārtha—Arjun, the son of Pritha; na anyat—no other; asti—is; iti—thus; vādinaḥ—advocate;
 kāma-ātmānaḥ—desirous of sensual pleasure; swarga-parāḥ—aiming to achieve the heavenly planets; janma-karma-phala—high birth and fruitive results; pradāṁ—awarding; kriyā-viśheṣha—pompous ritualistic ceremonies; bahulām—various; bhoga—gratification; aiśhwarya—luxury; gatim—progress; prati—toward'::text),'The unwise, taking pleasure in the eulogizing words of the Vedas, utter flowery speech, saying, "There is nothing else," O Arjuna.','Swami Sivananda','2.42 याम which? इमाम् this? पुष्पिताम् flowery? वाचम् speech? प्रवदन्ति utter? अविपश्चितः the unwise? वेदवादरताः takign pleasure in the eulogising words of the Vedas? पार्थ O Partha? न not? अन्यत् other? अस्ति is? इति thus? वादिनः saying.Commentary Unwise people who are lacking in discrimination lay great stress upon the Karma Kanda or the ritualistic portion of the Vedas? which lays down specific rules for specific actions for,the attainment of specific fruits and ectol these actions and rewards unduly. They are highly enamoured of such Vedic passages which prescribe ways for the attainment of heavenly enjoyments. They say that there is nothing else beyond the sensual enjoyments in Svarga (heaven) which can be obtained by performing the rites of the Karma Kanda of the Vedas.There are two main divisions of the Vedas -- Karma Kanda (the section dealing with action) and Jnana Kanda (the section dealing with knowledge). The Karma Kanda comprises the Brahmanas and the Samhitas. This is the authority for the Purvamimamsa school founded by Jaimini. The followers of this school deal with rituals and prescribe many of them for attaining enjoyments and power here and happiness in heaven. They regard this as the ultimate object of human existence. Ordinary people are attracted by their panegyrics. The Jnana Kanda comprises the Aranyakas and the Upanishads which deal with the nature of Brahman or the Supreme Self.Life in heaven is also transitory. After the fruits of the good actions are exhausted? one has to come back to this earthplane. Liberatio or Moksha can only be attained by knowledge of the Self but not by performing a thousand and one sacrifices.Lord Krishna assigns a comparatively inferior position to the doctrine of the Mimamsakas of performing Vedic sacrifices for obtaining heaven? power and lordship in this world as they cannot give us final liberation.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',43,90,'2-43','कामात्मानः स्वर्गपरा जन्मकर्मफलप्रदाम्।

क्रियाविशेषबहुलां भोगैश्वर्यगतिं प्रति।।2.43।।','kāmātmānaḥ svarga-parā 

 janma-karma-phala-pradām

 kriyā-viśeṣa-bahulāṁ

 bhogaiśvarya-gatiṁ prati',to_json('kāmaātmānaḥ—desirous   of  sense   gratification;  svarga-parāḥ—aiming to  achieve heavenly    planets;    janma-karma-phala-pradām—resulting  in  fruitive    action, good        birth,     etc.;      kriyā-viśeṣa—pompous       ceremonies;        bahulām—various; bhoga—sense       enjoyment;     aiśvarya—opulence;     gatim—progress;    prati—towards.'::text),'Full of desires, with heaven as their goal, (they speak words that are directed to ends) leading to new births as the result of their works, and prescribe various methods abounding in specific actions, for the attainment of pleasure and power.','Swami Sivananda','2.43 कामात्मानः full of desires? स्वर्गपराः with heaven as their highest goal? जन्मकर्मफलप्रदाम् leading to (new) births as the result of their works? क्रियाविशेषबहुलाम् exuberant with various specifi actions? भोगैश्वर्यगतिम् प्रति for the attainment of pleasure and lordship.No commentary.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',44,91,'2-44','भोगैश्वर्यप्रसक्तानां तयापहृतचेतसाम्।

व्यवसायात्मिका बुद्धिः समाधौ न विधीयते।।2.44।।','bhogaiśwvarya-prasaktānāṁ tayāpahṛita-chetasām
vyavasāyātmikā buddhiḥ samādhau na vidhīyate',to_json('bhoga—gratification; aiśhwarya—luxury; prasaktānām—whose minds are deeply attached; tayā—by that; apahṛita-chetasām—bewildered in intellect; vyavasāya-ātmikā—resolute; buddhiḥ—intellect; samādhau—fulfilment; na—never; vidhīyate—occurs'::text),'For those who are attached to pleasure and power, whose minds are drawn away by such teachings, their determinate reason is not formed which is steadily bent on meditation and Samadhi (superconscious state).','Swami Sivananda','2.44 भोगैश्वर्यप्रसक्तानाम् of the people deeply attached to pleasure and lordship? तया by that? अपहृतचेतसाम् whose minds are drawn away? व्यवसायात्मिका determinate? बुद्धिः reason? समाधौ in Samadhi? न not? विधीयते is fixed.Commentary Those who cling to pleasure and power cannot have steadiness of mind. They cannot concentrate or meditate. They are ever busy in planning projects for the acisition of wealth and power. Their minds are ever restless. They have no poised understanding.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',45,92,'2-45','त्रैगुण्यविषया वेदा निस्त्रैगुण्यो भवार्जुन।

निर्द्वन्द्वो नित्यसत्त्वस्थो निर्योगक्षेम आत्मवान्।।2.45।।','trai-guṇya-viṣhayā vedā nistrai-guṇyo bhavārjuna
nirdvandvo nitya-sattva-stho niryoga-kṣhema ātmavān',to_json('trai-guṇya—of the three modes of material nature; viṣhayāḥ—subject matter; vedāḥ—Vedic scriptures; nistrai-guṇyaḥ—above the three modes of material nature, transcendental; bhava—be; arjuna—Arjun; nirdvandvaḥ—free from dualities; nitya-sattva-sthaḥ—eternally fixed in truth; niryoga-kṣhemaḥ—unconcerned about gain and preservation; ātma-vān—situated in the self'::text),'The Vedas deal with the three attributes; be thou above these three attributes. O Arjuna, free yourself from the pairs of opposites and ever remain in the quality of Sattva, freed from acquisition and preservation, and be established in the Self.','Swami Sivananda','2.45 त्रैगुण्यविषयाः deal with the three attributes? वेदाः the Vedas? निस्त्रैगुण्यः without these three attributes? भव be? अर्जुन O Arjuna निर्द्वन्द्वः free from the pairs of opposites? नित्यसत्त्वस्थः ever remaining in the Sattva (goodness)? निर्योगक्षेमः free from (the thought of) acisition and preservation? आत्मवान् established in the Self.Commentary Guna means attribute or ality. It is substance as well as ality. Nature (Prakriti) is made up of three Gunas? viz.? Sattva (purity? light or harmony)? Rajas (passion or motion) and Tamas (darkness or inertia). The pairs of opposites are heat and cold? pleasure and pain? gain and loss? victory and defeat? honour and dishonour? praise and censure. He who is anxious about new acuqisitions or about the preservation of his old possessions cannot have peace of mind. He is ever restless. He cannot concentrate or meditate on the Self. He cannot practise virtue. Therefore? Lord Krishna advises Arjuna that he should be free from the thought of acisition and preservation of things. (Cf.IX.20?21).','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',46,93,'2-46','यावानर्थ उदपाने सर्वतः संप्लुतोदके।

तावान्सर्वेषु वेदेषु ब्राह्मणस्य विजानतः।।2.46।।','yāvān artha udapāne sarvataḥ samplutodake
tāvānsarveṣhu vedeṣhu brāhmaṇasya vijānataḥ',to_json('yāvān—whatever; arthaḥ—purpose; uda-pāne—a well of water; sarvataḥ—in all respects; sampluta-udake—by a large lake; tāvān—that many; sarveṣhu—in all; vedeṣhu—Vedas; brāhmaṇasya—one who realizes the Absolute Truth; vijānataḥ—who is in complete knowledge'::text),'To the Brahmana who has known the Self, all the Vedas are of as much use as a reservoir of water would be in a place where there is a flood.','Swami Sivananda','2.46 यावान् as much? अर्थः use? उदपाने in a reservoir? सर्वतः everywhere? संप्लुतोदके being flooded? तावान्,so much (use)? सर्वेषु in all? वेदेषु in the Vedas? ब्राह्मणस्य of the Brahmana? विजानतः of the knowing.Commentary Only for a sage who has realised the Self? the Vedas are of no use? because he is in possession of the infinite knowledge of the Self. This does not? however? mean that the Vedas are useless. They are useful for the neophytes or the aspirants who have just started on the spiritual path.All the transient pleasures derivable from the proper performance of all actions enjoined in the Vedas are comprehended in the infinite bliss of Selfknowledge.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',47,94,'2-47','कर्मण्येवाधिकारस्ते मा फलेषु कदाचन।

मा कर्मफलहेतुर्भूर्मा ते सङ्गोऽस्त्वकर्मणि।।2.47।।','karmaṇy-evādhikāras te mā phaleṣhu kadāchana
mā karma-phala-hetur bhūr mā te saṅgo ’stvakarmaṇi',to_json('karmaṇi—in prescribed duties; eva—only; adhikāraḥ—right; te—your; mā—not; phaleṣhu—in the fruits; kadāchana—at any time; mā—never; karma-phala—results of the activities; hetuḥ—cause; bhūḥ—be; mā—not; te—your; saṅgaḥ—attachment; astu—must be; akarmaṇi—in inaction'::text),'Your right is only to work, but not to its results; do not let the results of action be your motive, nor let your attachment be to inaction.','Swami Sivananda','2.47 कर्मणि in work? एव only? अधिकारः right? ते thy? मा not? फलेषु in the fruits? कदाचन  at any time? मा not? कर्मफलहेतुः भूः let not the fruits of action be thy motive? मा not? ते thy? सङ्गः attachment? अस्तु let (there) be? अकर्मणि in inaction.Commentary When you perform actions have no desire for the fruits thereof under any circumstances. If you thirst for the fruits of your actions? you will have to take birth again and again to enjoy them. Action done with expectation of fruits (rewards) brings bondage. If you do not thirst for them? you get purification of heart and you will get knowledge of the Self through purity of heart and through the knowledge of the Self you will be freed from the round of births and deaths.Neither let thy attachment be towards inaction thinking what is the use of doing actions when I cannot get any reward for themIn a broad sense Karma means action. It also means duty which one has to perform according to his caste or station of life. According to the followers of the Karma Kanda of the Vedas (the Mimamsakas) Karma means the rituals and sacrifices prescribed in the Vedas. It has a deep meaning also. It signifies the destiny or the storehouse of tendencies of a man which give rise to his future birth.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',48,95,'2-48','योगस्थः कुरु कर्माणि सङ्गं त्यक्त्वा धनञ्जय।

सिद्ध्यसिद्ध्योः समो भूत्वा समत्वं योग उच्यते।।2.48।।','yoga-sthaḥ kuru karmāṇi saṅgaṁ tyaktvā dhanañjaya
siddhy-asiddhyoḥ samo bhūtvā samatvaṁ yoga uchyate',to_json('yoga-sthaḥ—being steadfast in yog; kuru—perform; karmāṇi—duties; saṅgam—attachment; tyaktvā—having abandoned; dhanañjaya—Arjun; siddhi-asiddhyoḥ—in success and failure; samaḥ—equipoised; bhūtvā—becoming; samatvam—equanimity; yogaḥ—Yog; uchyate—is called'::text),'Perform action, O Arjuna, being steadfast in Yoga, abandoning attachment and balanced in success and failure; evenness of mind is called Yoga.','Swami Sivananda','2.48 योगस्थः steadfast in Yoga? कुरु perform? कर्माणि actions? सङ्गम् attachment? त्यक्त्वा having abandoned? धनञ्जय O Dhananjaya? सिद्ध्यसिद्ध्योः in success and failure? समः the smae? भूत्वा having become? समत्वम् evenness of mind? योगः Yoga? उच्यते is called.Commentary Dwelling in union with the Divine perform actions merely for Gods sake with a balanced mind in success and failure. Eilibrium is Yoga. The attainment of the knowledge of the Self through purity of heart obtained by doing actions without expectation of fruits is success (Siddhi). Failure is the nonattainment of knowledge by doing actions with expectation of fruit. (Cf.III.9IV.14IV.20).','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',49,96,'2-49','दूरेण ह्यवरं कर्म बुद्धियोगाद्धनञ्जय।

बुद्धौ शरणमन्विच्छ कृपणाः फलहेतवः।।2.49।।','dūreṇa hy-avaraṁ karma buddhi-yogād dhanañjaya
buddhau śharaṇam anvichchha kṛipaṇāḥ phala-hetavaḥ',to_json('dūreṇa—(discrad) from far away; hi—certainly; avaram—inferior; karma—reward-seeking actions; buddhi-yogāt—with the intellect established in Divine knowledge; dhanañjaya—Arjun; buddhau—divine knowledge and insight; śharaṇam—refuge; anvichchha—seek; kṛipaṇāḥ—miserly; phala-hetavaḥ—those seeking fruits of their work'::text),'Far lower than the Yoga of wisdom is action, O Arjuna. Seek thou refuge in wisdom; wretched are those whose motive is the fruit.','Swami Sivananda','2.49 दूरेण by far? हि indeed? अवरम् inferior? कर्म action or work? बुद्धियोगात् than the Yoga of wisdom? धनञ्जय O Dhananjaya? बुद्धौ in wisdom? शरणम् refuge? अन्विच्छ seek? कृपणाः wretched? फलहेतवः seekers after fruits.Commentary Action done with evenness of mind is Yoga of wisdom. The yogi who is established in the Yoga of widdom is not affected by success or failure. He does not seek fruits of his actions. He has poised reason. His reason is rooted in the Self. Action performed by one who expects fruits for his actions? is far inferior to the Yoga of wisdom wherein the seeker does not seek fruits because the former leads to bondage and is the cause of birth and death. (Cf.VIII.18).','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',50,97,'2-50','बुद्धियुक्तो जहातीह उभे सुकृतदुष्कृते।

तस्माद्योगाय युज्यस्व योगः कर्मसु कौशलम्।।2.50।।','buddhi-yukto jahātīha ubhe sukṛita-duṣhkṛite
tasmād yogāya yujyasva yogaḥ karmasu kauśhalam',to_json('buddhi-yuktaḥ—endowed with wisdom; jahāti—get rid of; iha—in this life; ubhe—both; sukṛita-duṣhkṛite—good and bad deeds; tasmāt—therefore; yogāya—for Yog; yujyasva—strive for; yogaḥ—yog is; karmasu kauśhalam—the art of working skillfully'::text),'Endowed with wisdom and evenness of mind, one casts off in this life both good and evil deeds; therefore, devote yourself to Yoga; Yoga is skill in action.','Swami Sivananda','2.50 बुद्धियुक्तः endowed with wisdom? जहाति casts off? इह in this life? उभे both? सुकृतदुष्कृते good and evil deeds? तस्मात् therefore? योगाय to Yoga? युज्यस्व devote thyself? योगः Yoga? कर्मसु in actions? कौशलम् skill.Commentary Work performed with motive towards fruits only can bind a man. It will bring the fruits and the performer of the action will have to take birth again in this mortal world to enjoy them. If work is performed with evennes of mind (the Yoga of wisdom? i.e.? united to pure Buddhi? intelligence or reason) with the mind resting in the Lord? it will not bind him it will not bring any fruit it is no work at all. Actions which are of a binding nature lose that nature when performed with eanimity of mind? or poised reason. The Yogi of poised reason attributes all actions to the Divine Actor within (Isvara or God).','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',51,98,'2-51','कर्मजं बुद्धियुक्ता हि फलं त्यक्त्वा मनीषिणः।

जन्मबन्धविनिर्मुक्ताः पदं गच्छन्त्यनामयम्।।2.51।।','karma-jaṁ buddhi-yuktā hi phalaṁ tyaktvā manīṣhiṇaḥ
janma-bandha-vinirmuktāḥ padaṁ gachchhanty-anāmayam',to_json('karma-jam—born of fruitive actions; buddhi-yuktāḥ—endowed with equanimity of intellect; hi—as; phalam—fruits; tyaktvā—abandoning; manīṣhiṇaḥ—the wise; janma-bandha-vinirmuktāḥ—freedom from the bondage of life and death; padam—state; gachchhanti—attain; anāmayam—devoid of sufferings'::text),'The wise, possessing knowledge, having abandoned the fruits of their actions, and being freed from the bonds of birth, go to the place which is beyond all evil.','Swami Sivananda','2.51 कर्मजम् actionborn? बुद्धियुक्ताः possessed of knowledsge? हि indeed? फलम् the fruit? त्यक्त्वा having abandoned? मनीषिणः the wise? जन्मबन्धविनिर्मुक्ताः freed from the fetters of birth? पदम् the abode? गच्छन्ति go? अनामयम् beyond evil.Commentary Clinging to the fruits of actions is the cause of rirth. Man takes a body to enjoy them. If anyone performs actions for the sake of God in fulfilment of His purpose without desire for the fruits? he is released from the bonds of birth and attains to the blissful state or the immortal abode.Sages who possess evenness of mind abandon the fruits of their actions and thus escape from good and bad actions.Buddhi referred to in the three verses 49? 50 and 51 may be the wisdom of the Sankhyas? i.e.? the knowledge of the Self or AtmaJnana which dawns when the mind is purified by Karma Yoga.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',52,99,'2-52','यदा ते मोहकलिलं बुद्धिर्व्यतितरिष्यति।

तदा गन्तासि निर्वेदं श्रोतव्यस्य श्रुतस्य च।।2.52।।','yadā te moha-kalilaṁ buddhir vyatitariṣhyati
tadā gantāsi nirvedaṁ śhrotavyasya śhrutasya cha',to_json('yadā—when; te—your; moha—delusion; kalilam—quagmire; buddhiḥ—intellect; vyatitariṣhyati—crosses; tadā—then; gantāsi—you shall acquire; nirvedam—indifferent; śhrotavyasya—to what is yet to be heard; śhrutasya—to what has been heard; cha—and'::text),'When your intellect passes beyond the mire of delusion, then you will attain indifference to what has been heard and what has yet to be heard.','Swami Sivananda','2.52 यदा when? ते thy? मोहकलिलम् mire of delusion? बुद्धिः intellect? व्यतितरिष्यति crosses beyond? तदा then? गन्तासि thou shalt attain? निर्वेदम् to indifference? श्रोतव्यस्य of what has to be heard? श्रुतस्य what has been heard? च and.Commentary The mire of delusion is the identification of the Self with the notself. The sense of discrimination between the Self and the notSelf is confounded by the mire of delusion and the mind runs towards the sensual objects and the body is takes as the pure Self. When you attain purity of mind? you will attain to indifference regarding things heard and yet to be heard. They will appear to you to be of no use. You will not care a bit for them. You will entertain disgust for them. (Cf.XVI.24).','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bi850001u7eu6wpz6gtz',53,100,'2-53','श्रुतिविप्रतिपन्ना ते यदा स्थास्यति निश्चला।

समाधावचला बुद्धिस्तदा योगमवाप्स्यसि।।2.53।।','śhruti-vipratipannā te yadā sthāsyati niśhchalā
samādhāv-achalā buddhis tadā yogam avāpsyasi',to_json('śhruti-vipratipannā—not allured by the fruitive sections of the Vedas; te—your; yadā—when; sthāsyati—remains; niśhchalā—steadfast; samādhau—in divine consciousness; achalā—steadfast; buddhiḥ—intellect; tadā—at that time; yogam—Yog; avāpsyasi—you will attain'::text),'When your intellect, which is perplexed by the Vedic texts you have read, stands immovable and steady in the Self, then you will attain Self-realization.','Swami Sivananda','2.53 श्रुतिविप्रतिपन्ना perplexed by what hast heard? ते thy? यदा when? स्थास्यति shall stand? निश्चला immovable? समाधौ in the Self? अचला steady? बुद्धिः intellect? तदा then? योगम् Selfrealisation? अवाप्स्यसि (thou) shalt attain.Commentary When your intellect which is tossed about by the conflict of opinions regarding the Pravritti Marga (the path of action) and the Nivritti Marga (the path of retirement or renunciation) has become immovable without distraction and doubt and firmly established in the Self? then thou shalt attain Selfrealisation or knowledge of the Self (AtmaJnana).','Swami Sivananda',now(),now())
ON CONFLICT (slug) DO UPDATE SET
  sanskrit            = EXCLUDED.sanskrit,
  transliteration     = EXCLUDED.transliteration,
  "wordByWord"        = EXCLUDED."wordByWord",
  translation         = EXCLUDED.translation,
  "translationAuthor" = EXCLUDED."translationAuthor",
  commentary          = EXCLUDED.commentary,
  "commentaryAuthor"  = EXCLUDED."commentaryAuthor",
  "updatedAt"         = now();