-- Batch 8 (verses 401-450)
INSERT INTO "Verse" (id,"chapterId",number,"globalNumber",slug,sanskrit,transliteration,"wordByWord",translation,"translationAuthor",commentary,"commentaryAuthor","createdAt","updatedAt")
VALUES
(gen_random_uuid(),'cmpl2bv1g0009u7eu38y5s294',29,401,'10-29','अनन्तश्चास्मि नागानां वरुणो यादसामहम्।

पितृ़णामर्यमा चास्मि यमः संयमतामहम्।।10.29।।','anantaśh chāsmi nāgānāṁ varuṇo yādasām aham
pitṝīṇām aryamā chāsmi yamaḥ sanyamatām aham',to_json('anantaḥ—Anant; cha—and; asmi—I am; nāgānām—amongst snakes; varuṇaḥ—the celestial god of the ocean; yādasām—amongst aquatics; aham—I; pitṝīṇām—amongst the departed ancestors; aryamā—Aryama; cha—and; asmi—am; yamaḥ—the celestial god of death; sanyamatām—amongst dispensers of law; aham—I'::text),'I am Ananta among the Nagas; I am Varuna among water-deities; Aryaman among the Manes; I am Yama among the governors.','Swami Sivananda','10.29 अनन्तः Ananta? च and? अस्मि (I) am? नागानाम् among Nagas? वरुणः Varuna? यादसाम् among watergods? अहम् I? पितृ़णाम् among the Pitris or ancestors? अर्यमा Aryaman? च and? अस्मि (I) am? यमः Yama? संयमताम् among governors? अहम् I.Commentary Ananta is the king of hooded serpents or cobras. He is firecoloured.Varuna is the king of the watergods.Waterdeities The gods connected with waters.Aryaman is the king of the manes.I am Yama? the witness of the acts of all living beings? who keeps account of the good and bad actions of the people.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bv1g0009u7eu38y5s294',30,402,'10-30','प्रह्लादश्चास्मि दैत्यानां कालः कलयतामहम्।

मृगाणां च मृगेन्द्रोऽहं वैनतेयश्च पक्षिणाम्।।10.30।।','prahlādaśh chāsmi daityānāṁ kālaḥ kalayatām aham
mṛigāṇāṁ cha mṛigendro ’haṁ vainateyaśh cha pakṣhiṇām',to_json('prahlādaḥ—Prahlad; cha—and; asmi—I am; daityānām—of the demons; kālaḥ—time; kalayatām—of all that controls; aham—I; mṛigāṇām—amongst animals; cha—and; mṛiga-indraḥ—the lion; aham—I; vainateyaḥ—Garud; cha—and; pakṣhiṇām—amongst birds'::text),'And I am Prahlada among the demons, I am Time among reckoners, I am the lion among beasts, and Vainateya (Garuda) among birds.','Swami Sivananda','10.30 प्रह्लादः Prahlada? च and? अस्मि (I) am? दैत्यानाम् among demons? कालः time? कलयताम् among reckoners? अहम् I? मृगाणाम् among beasts? च and? मृगेन्द्रः lion? अहम् I? वैनतेयः son of Vinata (Garuda)? च and? पक्षिणाम् among birds.Commentary Prahlada? though he was the son of a demon (Hiranyakasipu)? was a great devotee of the Lord.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bv1g0009u7eu38y5s294',31,403,'10-31','पवनः पवतामस्मि रामः शस्त्रभृतामहम्।

झषाणां मकरश्चास्मि स्रोतसामस्मि जाह्नवी।।10.31।।','pavanaḥ pavatām asmi rāmaḥ śhastra-bhṛitām aham
jhaṣhāṇāṁ makaraśh chāsmi srotasām asmi jāhnavī',to_json('pavanaḥ—the wind; pavatām—of all that purifies; asmi—I am; rāmaḥ—Ram; śhastra-bhṛitām—of the carriers of weapons; aham—I am; jhaṣhāṇām—of all acquatics; makaraḥ—crocodile; cha—also; asmi—I am; srotasām—of flowing rivers; asmi—I am; jāhnavī—the Ganges'::text),'Among the purifiers, I am the wind; among the warriors, I am Rama; among the fishes, I am the shark; among the streams, I am the Ganga.','Swami Sivananda','10.31 पवनः the wind? पवताम् among purifiers or the speeders? अस्मि (I) am? रामः Rama? शस्त्रभृताम् among wielders of weapons (warriors)? अहम् I? झषाणाम् among fishes? मकरः Makara (shark)? च and? अस्मि (I) am? स्रोतसाम् among streams? अस्मि (I) am? जाह्नवी the Ganga.Commentary The holy river Ganga (spelt Ganges in English) was swallowed by Jahnu when she was being brought down by Bhagiratha from heaven. Hence the name Jahnavi for Ganga.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bv1g0009u7eu38y5s294',32,404,'10-32','सर्गाणामादिरन्तश्च मध्यं चैवाहमर्जुन।

अध्यात्मविद्या विद्यानां वादः प्रवदतामहम्।।10.32।।','sargāṇām ādir antaśh cha madhyaṁ chaivāham arjuna
adhyātma-vidyā vidyānāṁ vādaḥ pravadatām aham',to_json('sargāṇām—of all creations; ādiḥ—the beginning; antaḥ—end; cha—and; madhyam—middle; cha—and; eva—indeed; aham—I; arjuna—Arjun; adhyātma-vidyā—science of spirituality; vidyānām—amongst sciences; vādaḥ—the logical conclusion; pravadatām—of debates; aham—I'::text),'Among creations I am the beginning, the middle, and the end, O Arjuna; among the sciences, I am the science of the Self; and I am the logic among controversialists.','Swami Sivananda','10.32 सर्गाणाम् among creations? आदिः the beginning? अन्तः the end? च and? मध्यम् the middle? च and? एव also? अहम् I? अर्जुन O Arjuna? अध्यात्मविद्या the science of the Self? विद्यानाम् among sciences? वादः logic? प्रवदताम् among controversialists? अहम् I.Commentary I am the metaphysics among all sciences. I am knowledge of the Self among all branches of knowledge. I am the argument of dators. I am the logic of disputants. I am the speech of orators.In verse 20 above the Lord says? I am the beginning? the middle and the end of the whole movable and immovable creation. Here the whole creation in general is referred to.As the knowledge of the Self leads to the attainment of the final beatitude of life or salvation? it is the chief among all branches of knowledge.Pravadatam By the word controversialists? we should here understand the various kinds of people using various kinds of argumentation in logic such as Vada? Jalpa and Vitanda. Yada is a way of arguing by which one gets at the truth of a certain estion. The aspirants who are free from RagaDvesha and jealousy raise amongst themselves estions and answers and enter into discussions on philosophical problems in order to ascertain and understand the nature of the Truth. They do not argue in order to gain victory over one another. This is Vada. Jalpa is wrangling in which one asserts his own opinion and refutes that of his opponent. Vitanda is idle carping at the arguments of ones opponents. No attempt is made to establish the other side of the estion. In Jalpa and Vitanda one tries to defeat another. There is desire for victory.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bv1g0009u7eu38y5s294',33,405,'10-33','अक्षराणामकारोऽस्मि द्वन्द्वः सामासिकस्य च।

अहमेवाक्षयः कालो धाताऽहं विश्वतोमुखः।।10.33।।','अहमेवाक्षय: कालो धाताहं विश्वतोमुख: || 33||

akṣharāṇām a-kāro ’smi dvandvaḥ sāmāsikasya cha
aham evākṣhayaḥ kālo dhātāhaṁ viśhvato-mukhaḥ',to_json('akṣharāṇām—amongst all letters; a-kāraḥ—the beginning letter “A”; asmi—I am; dvandvaḥ—the dual; sāmāsikasya—amongst grammatical compounds; cha—and; aham—I; eva—only; akṣhayaḥ—endless; kālaḥ—time; dhātā—amongst the creators; aham—I; viśhwataḥ-mukhaḥ—Brahma'::text),'Among the letters of the alphabet, I am the letter ''A'' and the dual among compounds. I am verily the inexhaustible and everlasting time; I am the dispenser of the fruits of actions, having faces in all directions.','Swami Sivananda','10.33 अक्षराणाम् among letters? अकारः the letter A? अस्मि (I) am? द्वन्द्वः the dual? सामासिकस्य among all compounds? च and? अहम् I? एव verily? अक्षयः the inexhaustible or everlasting? कालः time? धाता the dispenser? अहम् I? विश्वतोमुखः the Allfaced (or having faces in all directions).Commentary Among the alphabets I am the letter A. Among the various kinds of compounds used in Sanskrit language I am the Dvandva (union of the two)? the copulative.Time here refers to the moment? the ultimate element of time or to Paramesvara? the Supreme Lord Who is the time of even time? since He is beyond time.As the Supreme Being is allpervading it is said that He has faces in all directions.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bv1g0009u7eu38y5s294',34,406,'10-34','मृत्युः सर्वहरश्चाहमुद्भवश्च भविष्यताम्।

कीर्तिः श्रीर्वाक्च नारीणां स्मृतिर्मेधा धृतिः क्षमा।।10.34।।','mṛityuḥ sarva-haraśh chāham udbhavaśh cha bhaviṣhyatām
kīrtiḥ śhrīr vāk cha nārīṇāṁ smṛitir medhā dhṛitiḥ kṣhamā',to_json('mṛityuḥ—death; sarva-haraḥ—all-devouring; cha—and; aham—I; udbhavaḥ—the origin; cha—and; bhaviṣhyatām—those things that are yet to be; kīrtiḥ—fame; śhrīḥ—prospective; vāk—fine speech; cha—and; nārīṇām—amongst feminine qualities; smṛitiḥ—memory; medhā—intelligence; dhṛitiḥ—courage; kṣhamā—forgiveness'::text),'And I am the all-devouring Death, and the source of prosperity for those who are to be prosperous; among the feminine qualities, I am fame, prosperity, speech, memory, intelligence, firmness, and forgiveness.','Swami Sivananda','10.34 मृत्युः death? सर्वहरः alldevouring? च and? अहम् I? उद्भवः the prosperity? च and? भविष्यताम् of those who are to be prosperous? कीर्तिः frame? श्रीः prosperity? वाक् speech? च and? नारीणाम् of the feminine? स्मृतिः the memory? मेधा intelligence? धृतिः firmness? क्षमा forgiveness.Commentary I am also the allsnatching death that destroys everything. Death is of two kinds? viz.? he who seizes wealth and he who seizes life. Of them he who seizes life is the allseizer and,hence he is called Sarvaharah. I am he.Or? there is another interpretation. I am the Supreme Lord Who is the allseizer? because I destroy everything at the time of the cosmic dissolution.I am the origin of all the beings to be born in the future. I am the prosperity and the means of achieving it of those who are fit to attain it.Beauty is Sri. Lustre is Sri. I am fame? the best of the feminine alities. People who have attained slight fame think that they have achieved great success in life and that they have become very big or great men. I am speech which adorns the throne of justice. I am memory which recalls objects and pleasures of the past.The power of the mind which enables one to hold the teachings of the scriptures is Medha. Firmness or Dhriti is the power to keep the body and the senses steady even amidst various kinds of sufferings. The power to keep oneself unattached even while doing actions is Dhriti. It also means courage. Kshama also means endurance.Fame? prosperity? memory? intelligence and firmness are the daughters of Daksha. They had been given in marriage to Dhrama and so they are all called Dharmapatnis.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bv1g0009u7eu38y5s294',35,407,'10-35','बृहत्साम तथा साम्नां गायत्री छन्दसामहम्।

मासानां मार्गशीर्षोऽहमृतूनां कुसुमाकरः।।10.35।।','bṛihat-sāma tathā sāmnāṁ gāyatrī chhandasām aham
māsānāṁ mārga-śhīrṣho ’ham ṛitūnāṁ kusumākaraḥ',to_json('bṛihat-sāma—the Brihatsama; tathā—also; sāmnām—amongst the hymns in the Sama Veda; gāyatrī—the Gayatri mantra; chhandasām—amongst poetic meters; aham—I; māsānām—of the twelve months; mārga-śhīrṣhaḥ—the month of November-December; aham—I; ṛitūnām—of all seasons; kusuma-ākaraḥ—spring'::text),'Among the hymns, I am the Brihatsaman; among meters, I am Gayatri; among months, I am Margasirsha; among seasons, I am the flowery season.','Swami Sivananda','10.35 बृहत्साम Brihatsaman? तथा also? साम्नाम् among Sama hymns? गायत्री Gayatri? छन्दसाम् among metres? अहम् I? मासानाम् among months? मार्गशीर्षः Margasirsha? अहम् I? ऋतूनाम् among seasons? कुसुमाकरः the flowery season (spring).Commentary Brihatsaman is the chief of the hymns of the SamaVeda. Brihat means big.Margasirsha From the middle of December to the middle of January. This has a temperate climate. In olden days it was usual to start with this month in counting the months of the year. The first place was given to this month.Kusumakara The beautiful flowery season? the spring.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bv1g0009u7eu38y5s294',36,408,'10-36','द्यूतं छलयतामस्मि तेजस्तेजस्विनामहम्।

जयोऽस्मि व्यवसायोऽस्मि सत्त्वं सत्त्ववतामहम्।।10.36।।','dyūtaṁ chhalayatām asmi tejas tejasvinām aham
jayo ’smi vyavasāyo ’smi sattvaṁ sattvavatām aham',to_json('dyūtam—gambling; chhalayatām—of all cheats; asmi—I am; tejaḥ—the splendor; tejasvinām—of the splendid; aham—I; jayaḥ—victory; asmi—I am; vyavasāyaḥ—firm resolve; asmi—I am; sattvam—virtue; sattva-vatām—of the virtuous; aham—I'::text),'I am the gambling of the deceitful; I am the splendor of the splendid; I am victory; I am the resolve of the resolute; I am the goodness of the good.','Swami Sivananda','10.36 द्यूतम् the gambling? छलयताम् of the fraudulent? अस्मि (I) am? तेजः splendour? तेजस्विनाम् of the splendid? अहम् I? जयः victory? अस्मि (I) am? व्यवसायः determination? अस्मि (I) am? सत्त्वम् the goodness? सत्त्ववताम् of the good? अहम् I.Commentary Of the methods of defrauding others I am gambling such as diceplay. Gambling is My manifestation. I am the power of the powerful. I am the victoyr of the victorious. I am the effort of those who make that effort.I am Sattva which assumes the forms of Dharma (virtue)? Jnana (knowledge)? Vairagya (dispassion)? and Aisvarya (wealth or lordship) in Sattvic persons.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bv1g0009u7eu38y5s294',37,409,'10-37','वृष्णीनां वासुदेवोऽस्मि पाण्डवानां धनंजयः।

मुनीनामप्यहं व्यासः कवीनामुशना कविः।।10.37।।','vṛiṣhṇīnāṁ vāsudevo ’smi pāṇḍavānāṁ dhanañjayaḥ
munīnām apyahaṁ vyāsaḥ kavīnām uśhanā kaviḥ',to_json('vṛiṣhṇīnām—amongst the descendants of Vrishni; vāsudevaḥ—Krishna, the son of Vasudev; asmi—I am; pāṇḍavānām—amongst the Pandavas; dhanañjayaḥ—Arjun, the conqueror of wealth; munīnām—amongst the sages; api—also; aham—I; vyāsaḥ—Ved Vyas; kavīnām—amongst the great thinkers; uśhanā—Shukracharya; kaviḥ—the thinker'::text),'Among the Vrishnis, I am Vaasudeva; among the Pandavas, I am Arjuna; among the sages, I am Vyasa; among the poets, I am Usanas, the poet.','Swami Sivananda','10.37 वृष्णीनाम among the Vrishnis? वासुदेवः Vaasudeva? अस्मि (I) am? पाण्डवानाम् among the Pandavas? धनञ्जयः Dhananjaya? मुनीनाम् among the sages? अपि also? अहम् I? व्यासः Vyasa? कवीनाम् among poets? उशनाः Usanas? कविः the poet.Commentary Vrishnis are Yadavas or the descendants of Yadu. I am the foremost among them.Usanas is Sukracharya? the preceptor of the demons.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bv1g0009u7eu38y5s294',38,410,'10-38','दण्डो दमयतामस्मि नीतिरस्मि जिगीषताम्।

मौनं चैवास्मि गुह्यानां ज्ञानं ज्ञानवतामहम्।।10.38।।','daṇḍo damayatām asmi nītir asmi jigīṣhatām
maunaṁ chaivāsmi guhyānāṁ jñānaṁ jñānavatām aham',to_json('daṇḍaḥ—punishment; damayatām—amongst means of preventing lawlessness; asmi—I am; nītiḥ—proper conduct; asmi—I am; jigīṣhatām—amongst those who seek victory; maunam—silence; cha—and; eva—also; asmi—I am; guhyānām—amongst secrets; jñānam—wisdom; jñāna-vatām—in the wise; aham—I'::text),'Of those who punish, I am the scepter; among those who seek victory, I am statesmanship; and among secrets, I am silence; I am knowledge among knowers.','Swami Sivananda','10.38 दण्डः the sceptre? दमयताम् among punishers? अस्मि (I) am? नीतिः statesmanship? अस्मि (I) am? जिगीषताम् among thoese who seek victory? मौनम् silence? च and? एव also? अस्मि (I) am? गुह्यानाम् among secrets? ज्ञानम् the knowledge? ज्ञानवताम् among the knowers? अहम् I.Commentary Niti Diplomacy? polity.Maunam The silence produced by constant meditation on Brahman or the Self.Jnanam Knowledge of the Self.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bv1g0009u7eu38y5s294',39,411,'10-39','यच्चापि सर्वभूतानां बीजं तदहमर्जुन।

न तदस्ति विना यत्स्यान्मया भूतं चराचरम्।।10.39।।','yach chāpi sarva-bhūtānāṁ bījaṁ tad aham arjuna
na tad asti vinā yat syān mayā bhūtaṁ charācharam',to_json('yat—which; cha—and; api—also; sarva-bhūtānām—of all living beings; bījam—generating seed; tat—that; aham—I; arjuna—Arjun; na—not; tat—that; asti—is; vinā—without; yat—which; syāt—may exist; mayā—me; bhūtam—creature; chara-acharam—moving and nonmoving'::text),'And whatever is the seed of all beings, that too am I, O Arjuna; there is no being, be it moving or unmoving, that can exist without Me.','Swami Sivananda','10.39 यत् which? च and? अपि also? सर्वभूतानाम् among all beings? बीजम् seed? तत् that? अहम् I? अर्जुन O Arjuna? न not? तत् that? अस्ति is? विना without? यत् which? स्यात् may be? मया by Me? भूतम् being? चराचरम् moving or unmoving.Commentary I am the primeval seed from which all creation has come into existence. I am the seed of everything. I am the Self of everything. Nothing can exist without Me. Everything is of My nature. I am the essence of everything. Without Me all things would be mere void. I am the soul of everything.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bv1g0009u7eu38y5s294',40,412,'10-40','नान्तोऽस्ति मम दिव्यानां विभूतीनां परंतप।

एष तूद्देशतः प्रोक्तो विभूतेर्विस्तरो मया।।10.40।।','nānto ’sti mama divyānāṁ vibhūtīnāṁ parantapa
eṣha tūddeśhataḥ prokto vibhūter vistaro mayā',to_json('na—not; antaḥ—end; asti—is; mama—my; divyānām—divine; vibhūtīnām—manifestations; parantapa—Arjun, the conqueror of the enemies; eṣhaḥ—this; tu—but; uddeśhataḥ—just one portion; proktaḥ—declared; vibhūteḥ—of (my) glories; vistaraḥ—the breath of the topic; mayā—by me'::text),'There is no end to My divine glories, O Arjuna, but this is a brief statement by Me of the particulars of My divine glory.','Swami Sivananda','10.40 न not? अन्तः end? अस्ति is? मम My? दिव्यानाम् of divine? विभूतीनाम् glories? परंतप O scorcher of foes? एषः this? तु indeed? उद्देशतः briefly? प्रोक्तः has been stated? विभूतेः of glory? विस्तरः particulars? मया by Me.Commentary It is impossible for anyone to describe or know the exact extent of the divine gloreis of the Lord. There is no limit to His powers or glories. What could be expressed of Him is nothing when compared to His infinte glories.Parantapa Scorcher of foes -- he who burns the internal enemies? lust? anger? greed? deluion? etc.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bv1g0009u7eu38y5s294',41,413,'10-41','यद्यद्विभूतिमत्सत्त्वं श्रीमदूर्जितमेव वा।

तत्तदेवावगच्छ त्वं मम तेजोंऽशसंभवम्।।10.41।।','yad yad vibhūtimat sattvaṁ śhrīmad ūrjitam eva vā
tat tad evāvagachchha tvaṁ mama tejo ’nśha-sambhavam',to_json('yat yat—whatever; vibhūtimat—opulent; sattvam—being; śhrī-mat—beautiful; ūrjitam—glorious; eva—also; vā—or; tat tat—all that; eva—only; avagachchha—know; tvam—you; mama—my; tejaḥ-anśha-sambhavam—splendor; anśha—a part; sambhavam—born of'::text),'Whatever being there is glorious, prosperous, or powerful, know that to be a manifestation of a part of My splendor.','Swami Sivananda','10.41 यत् यत् whatever? विभूतिमत् glorious? सत्त्वम् being? श्रीमत् prosperous? ऊर्जितम् powerful? एव also? वा or? तत् तत् that? एव only? अवगच्छ know? त्वम् thou? मम My? तेजोंऽशसंभवम् a manifestation of a part of My splendour.No Commentary.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bv1g0009u7eu38y5s294',42,414,'10-42','अथवा बहुनैतेन किं ज्ञातेन तवार्जुन।

विष्टभ्याहमिदं कृत्स्नमेकांशेन स्थितो जगत्।।10.42।।','atha vā bahunaitena kiṁ jñātena tavārjuna
viṣhṭabhyāham idaṁ kṛitsnam ekānśhena sthito jagat',to_json('athavā—or; bahunā—detailed; etena—by this; kim—what; jñātena tava—can be known by you; arjuna—Arjun; viṣhṭabhya—pervade and support; aham—I; idam—this; kṛitsnam—entire; eka—by one; anśhena—fraction; sthitaḥ—am situated; jagat—creation'::text),'But, of what avail is the knowledge of all these details to you, O Arjuna? I exist, supporting this whole world with one part of Myself.','Swami Sivananda','10.42 अथवा or? बहुना (by) many? एतेन (by) this? किम् what? ज्ञातेन known? तव to thee? अर्जुन O Arjuna? विष्टभ्य supporting? अहम् I? इदम् this? कृत्स्नम् all? एकांशेन by one part? स्थितः exist? जगत् the world.Commentary The Lord concludes Having established or pervaded this whole world with one fragment of Myself? I remain.This verse is based on the declaration in the Purusha Sukta (RigVeda10.90.3) that One arter of Him is all the cosmos the three arters are the divine transcendent Reality.I exist supporting this whole world by one part? by one limit? or by one foot. One part of Myself constitutes all beings.All beings form His foot (Taittiriya Aranyaka 3.12). The whole world is one Pada or foot of the Lord. Amsa (part) or Pada (foot) is mere Kalpana or imagination or account of our own ignorance,or limiting adjunct. In reality Brahman is without any such parts or limbs and is formless.Arjuna has now a knowledge of the glories of the Lord. He is fit to behold the magnificent cosmic form of the Lord. Lord Krishna prepares Arjuna for this grand vision by giving him a description of His glories.Arjuna says O Lord? I now realise that the whole world is filled by Thee. I now wish to behold the whole universe in Thee with my eye of intuition.Thus in the Upanishads of the glorious Bhagavad Gita? the science of the Eternal? the scripture of Yoga? the dialogue between Sri Krishna and Arjuna? ends the tenth discourse entitledThe Yoga of the Divine Glories.,','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bwmb000au7eu6fmf61a0',1,415,'11-1','अर्जुन उवाच

मदनुग्रहाय परमं गुह्यमध्यात्मसंज्ञितम्।

यत्त्वयोक्तं वचस्तेन मोहोऽयं विगतो मम।।11.1।।','arjuna uvācha
mad-anugrahāya paramaṁ guhyam adhyātma-sanjñitam
yat tvayoktaṁ vachas tena moho ’yaṁ vigato mama',to_json('arjunaḥ uvācha—Arjun said; mat-anugrahāya—out of compassion to me; paramam—supreme; guhyam—confidential; adhyātma-sanjñitam—about spiritual knowledge; yat—which; tvayā—by you; uktam—spoken; vachaḥ—words; tena—by that; mohaḥ—illusion; ayam—this; vigataḥ—is dispelled; mama—my'::text),'Arjuna said, By this explanation of the highest secret concerning the Self which Thou hast spoken, for the sake of blessing me, my delusion has been dispelled.','Swami Sivananda','11.1 मदनुग्रहाय for the sake of blessing me? परमम् the highest? गुह्यम् the secret? अध्यात्मसंज्ञितम् called Adhyatma? यत् which? त्वया by Thee? उक्तम् spoken? वचः word? तेन by that? मोहः delusion? अयम् this? विगतः gone? मम my.Commentary After hearing the glories of the Lord? Arjuna has an intense longing to have the wonderful vision of the Cosmic Form with his own eyes. His bewilderment and delusion have now vanished.Adhyatma That which treats of the discrimination between the Self and the notSelf metaphysics.I was worried about the sin involved in killing my relations and preceptors. I had the ideas? I am the agent in killing them they are to be killed by me.This delusion has vanished now after receiving Thy most profound and valuable instructions. Thou hast dispelled this delusion of ignorance from me.The vision of the Cosmic Form is not the ultimate goal. If that were so? the Gita would have ended with this chapter. The vision of the Cosmic Form is also one more in a series of graded experiences. It is a terrible experience too. That is the reason why Arjuna said to the Lord? stammering with fear What an awful form Thou hast I have seen that which none hath seen before. My heart is glad? yet faileth me on account of fear. Show me? O God? Thine other form again. O God of gods? support of all the worlds? let me see Thy form with the diadem? and with the mace and discus in Thy hands. Again I wish to see Thee as before assume Thy fourarmed form? O Lord of thousand arms and of forms innumerable.Arjuna heard the Lords statement? viz.? Having pervaded this whole universe with one fragment of Myself? I remain. This induced him to have the vision of the Lords Cosmic Form. He says? O Lord of compassion? Thou hast taught me the spiritual wisdom which can hardly be found in the Vedas. Thou hast saved me. My delusion has disappeared. Thou hast disclosed to me the nature of the Supreme Self? the secrets of Nature and Thy divine glories. My greatest ambition at the present moment is that I should behold with my own eyes Thy entire Cosmic Form.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bwmb000au7eu6fmf61a0',2,416,'11-2','भवाप्ययौ हि भूतानां श्रुतौ विस्तरशो मया।

त्वत्तः कमलपत्राक्ष माहात्म्यमपि चाव्ययम्।।11.2।।','bhavāpyayau hi bhūtānāṁ śhrutau vistaraśho mayā
tvattaḥ kamala-patrākṣha māhātmyam api chāvyayam',to_json('bhava—appearance; apyayau—disappearance; hi—indeed; bhūtānām—of all living beings; śhrutau—have heard; vistaraśhaḥ—in detail; mayā—by me; tvattaḥ—from you; kamala-patra-akṣha—lotus-eyed one; māhātmyam—greatness; api—also; cha—and; avyayam—eternal'::text),'The origin and destruction of beings have been heard in detail from You, O lotus-eyed Lord, and also Your inexhaustible greatness.','Swami Sivananda','11.2 भवाप्ययौ the origin and the dissolution? हि indeed? भूतानाम् of beings? श्रुतौ hav been heard? विस्तरशः in detail? मया by me? त्वत्तः from Thee? कमलपत्राक्ष O lotuseyed? माहात्म्यम् greatness? अपि also? च and? अव्ययम् inexhaustible.Commentary Kamalapatraksha Lotuseyed or having eyes like lotuspetals. Kamalapatra also means knowledge of the Self. He who can be obtained by knowledge of the Self is Kamalapatraksha.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bwmb000au7eu6fmf61a0',3,417,'11-3','एवमेतद्यथात्थ त्वमात्मानं परमेश्वर।

द्रष्टुमिच्छामि ते रूपमैश्वरं पुरुषोत्तम।।11.3।।','evam etad yathāttha tvam ātmānaṁ parameśhvara
draṣhṭum ichchhāmi te rūpam aiśhwaraṁ puruṣhottama',to_json('evam—thus; etat—this; yathā—as; āttha—have spoken; tvam—you; ātmānam—yourself; parama-īśhvara—Supreme Lord; draṣhṭum—to see; ichchhāmi—I desire; te—your; rūpam—form; aiśhwaram—divine; puruṣha-uttama—Shree Krishna, the Supreme Divine Personality'::text),'Now, O Supreme Lord, as Thou hast thus described Thyself, O Supreme Person, I wish to behold Thy divine form.','Swami Sivananda','11.3 एवम् thus? एतत् this? यथा as? आत्थ hast declared? त्वम् Thou? आत्मानम् Thyself? परमेश्वर O Supreme Lord? द्रष्टुम् to see? इच्छामि (I) desire? ते Thy? रूपम् form? ऐश्वरम् sovereign? पुरुषोत्तम O Supreme Purusha.Commentary Some commentators take the two halves of this verse as two independent sentences and interpret it thusSo it is? O Supreme Lord? as Thou hast declared Thyself to be. (But still) I desire to see Thy form as Isvara? O Supreme Person.Rupamaisvaram Thy form as Isvara? that of Vishnu as possessed of infinite knowledge? sovereignty? power? strength? prowess and splendour.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bwmb000au7eu6fmf61a0',4,418,'11-4','मन्यसे यदि तच्छक्यं मया द्रष्टुमिति प्रभो।

योगेश्वर ततो मे त्वं दर्शयाऽत्मानमव्ययम्।।11.4।।','manyase yadi tach chhakyaṁ mayā draṣhṭum iti prabho
yogeśhvara tato me tvaṁ darśhayātmānam avyayam',to_json('manyase—you think; yadi—if; tat—that; śhakyam—possible; mayā—by me; draṣhṭum—to behold; iti—thus; prabho—Lord; yoga-īśhvara—Lord of all mystic powers; tataḥ—then; me—to me; tvam—you; darśhaya—reveal; ātmānam—yourself; avyayam—imperishable'::text),'If Thou, O Lord, thinkest it possible for me to see it, do Thou, then, O Lord of the Yogis, show me Thy imperishable Self.','Swami Sivananda','11.4 मन्यसे Thou thinkest? यदि if? तत् that? शक्यम् possible? मया by me? द्रष्टुम् to see? इति thus? प्रभो O Lord? योगेश्वर O Lord of Yogins? ततः then? मे me? त्वम् Thou? दर्शय show? आत्मानम् (Thy) Self? अव्ययम् imperishable.Commentary Arjuna is very keen and eager to see the Cosmic Form of the Lord. He prays to Him to grant him the vision. This supreme vision can be obtained only through His grace.Yogesvara also means the Lord of Yoga. A Yogi is one who is endowed with the eight psychic powers (Siddhis). The Lord of the Yogins is Yogesvara. And? Yoga is identity of the individual soul with the Absolute. He who is able to bestow this realisation of identity on the deserving spiritual aspirant is Yogesvara.He Who is able to create? preserve? destroy? veil and graciously release is the Lord. (These five actions? Panchakriyas? are known respectively as Srishti? Sthiti? Samhara? Tirodhana and Anugraha.)','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bwmb000au7eu6fmf61a0',5,419,'11-5','श्री भगवानुवाच

पश्य मे पार्थ रूपाणि शतशोऽथ सहस्रशः।

नानाविधानि दिव्यानि नानावर्णाकृतीनि च।।11.5।।','śhrī-bhagavān uvācha
paśhya me pārtha rūpāṇi śhataśho ’tha sahasraśhaḥ
nānā-vidhāni divyāni nānā-varṇākṛitīni cha',to_json('śhrī-bhagavān uvācha—the Supreme Lord said; paśhya—behold; me—my; pārtha—Arjun, the son of Pritha; rūpāṇi—forms; śhataśhaḥ—by the hundreds; atha—and; sahasraśhaḥ—thousands; nānā-vidhāni—various; divyāni—divine; nānā—various; varṇa—colors; ākṛitīni—shapes; cha—and'::text),'The Blessed Lord said, "Behold, O Arjuna, forms of Mine, by the hundreds and thousands, of different sorts, divine, and of various colors and shapes."','Swami Sivananda','11.5 पश्य behold? मे My? पार्थ O Partha? रूपाणि forms? शतशः by hundreds? अथ and? सहस्रशः by thousands? नानाविधानि of different sorts? दिव्यानि divine? नानावर्णाकृतीनि of various colours and shapes? च and.Commentary Divyani Divine supernatural.Satasah? Sahasrasah By the hundreds and thousands -- countless.O Arjuna? I want you to behold the Cosmic Form. All beings and entities are there. The fat and the lean? the short and the tall? the red and the black? the active and the passive? the rich and the poor? the intelligent and the dull? the healthy and the sick? the noisy and the silent? those that are awake? those that are asleep? the beautiful and the ugly? and all grades of beings with their distinctive marks are all there. The blueness of the sky? the yellowness of the silk? the redness of the twilight? the blackness of the coal? the whiteness of the snow? and the greenness of the leaves will be seen by you. You will also behold the objects of various shapes.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bwmb000au7eu6fmf61a0',6,420,'11-6','पश्यादित्यान्वसून्रुद्रानश्िवनौ मरुतस्तथा।

बहून्यदृष्टपूर्वाणि पश्याऽश्चर्याणि भारत।।11.6।।','paśhyādityān vasūn rudrān aśhvinau marutas tathā
bahūny adṛiṣhṭa-pūrvāṇi paśhyāśhcharyāṇi bhārata',to_json('paśhya—behold; ādityān—the (twelve) sons of Aditi; vasūn—the (eight) Vasus; rudrān—the (eleven) Rudras; aśhvinau—the (twin) Ashvini Kumars; marutaḥ—the (forty-nine) Maruts; tathā—and; bahūni—many; adṛiṣhṭa—never revealed; pūrvāṇi—before; paśhya—behold; āśhcharyāṇi—marvels; bhārata—Arjun, scion of the Bharatas'::text),'Behold the Adityas, the Vasus, the Rudras, the two Asvins, and the Maruts; behold many wonders never before seen, O Arjuna.','Swami Sivananda','11.6 पश्य behold? आदित्यान् the Adityas? वसून् the Vasus? रुद्रान् the Rudras? अश्िवनौ the (two) Asvins? मरुतः the Maruts? तथा also? बहूनि many? अदृष्टपूर्वाणि never seen before? पश्य see? आश्चर्याणि wonders? भारत O Bharata.Commentary Adityas? Vasus? Rudras and Maruts have already been described in the previous chapter.Not these alone Behold also many other wonders never seen before by you or anybody else in this world.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bwmb000au7eu6fmf61a0',7,421,'11-7','इहैकस्थं जगत्कृत्स्नं पश्याद्य सचराचरम्।

मम देहे गुडाकेश यच्चान्यद्द्रष्टुमिच्छसि।।11.7।।','ihaika-sthaṁ jagat kṛitsnaṁ paśhyādya sa-charācharam
mama dehe guḍākeśha yach chānyad draṣhṭum ichchhasi',to_json('iha—here; eka-stham—assembled together; jagat—the universe; kṛitsnam—entire; paśhya—behold; adya—now; sa—with; chara—the moving; acharam—the non- moving; mama—my; dehe—in this form; guḍākeśha—Arjun, the conqueror of sleep; yat—whatever; cha—also; anyat—else; draṣhṭum—to see; ichchhasi—you wish'::text),'Now, behold, O Arjuna, in this My body, the entire universe centered in one, including the moving and the unmoving, and whatever else you desire to see.','Swami Sivananda','11.7 इह in this? एकस्थम् centred in one? जगत् the universe? कृत्स्नम् whole? पश्य behold? अद्य now? सचराचरम् with the moving and the unmoving? मम My? देहे in body? गुडाकेश O Gudakesa? यत् whatever? च and? अन्यत् other? द्रष्टुम् to see? इच्छसि (thou) desirest.Commentary Anyat Other whatever else. Your success or defeat in the war? about which you,have entertained a doubt. (Cf.II.6)','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bwmb000au7eu6fmf61a0',8,422,'11-8','न तु मां शक्यसे द्रष्टुमनेनैव स्वचक्षुषा।

दिव्यं ददामि ते चक्षुः पश्य मे योगमैश्वरम्।।11.8।।','na tu māṁ śhakyase draṣhṭum anenaiva sva-chakṣhuṣhā
divyaṁ dadāmi te chakṣhuḥ paśhya me yogam aiśhwaram',to_json('na—not; tu—but; mām—me; śhakyase—you can; draṣhṭum—to see; anena—with these; eva—even; sva-chakṣhuṣhā—with your physical eyes; divyam—divine; dadāmi—I give; te—to you; chakṣhuḥ—eyes; paśhya—behold; me—my; yogam aiśhwaram—majestic opulence'::text),'But you are not able to behold Me with these your own eyes; I give you the divine eye; behold My lordly Yoga.','Swami Sivananda','11.8 न not? तु but? माम् Me? शक्यसे (thou) canst? द्रष्टुम् to see? अनेन with this? एव even? स्वचक्षुषा with own eyes? दिव्यम् divine? ददामि (I) give? ते (to) thee? चक्षुः the eye? पश्य behold? मे My? योगम् Yoga? ऐश्वरम् lordly.Commentary No fleshly eyes can behold Me in My Cosmic Form. One can see It through the divine eye or the eye of intuition. It should not be confused with seeing through the eye or the mind. It is an inner experience.Lord Krishna says to Arjuna I give thee the divine eye? by which you will be able to behold My sovereign form. By it see My marvellous power of Yoga.Anena With this the fleshly eye or the physical eye? the earthly eye. (Cf.VII.25IX.5X.7)','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bwmb000au7eu6fmf61a0',9,423,'11-9','सञ्जय उवाच

एवमुक्त्वा ततो राजन्महायोगेश्वरो हरिः।

दर्शयामास पार्थाय परमं रूपमैश्वरम्।।11.9।।','sañjaya uvācha
evam uktvā tato rājan mahā-yogeśhvaro hariḥ
darśhayām āsa pārthāya paramaṁ rūpam aiśhwaram',to_json('sañjayaḥ uvācha—Sanjay said; evam—thus; uktvā—having spoken; tataḥ—then; rājan—King; mahā-yoga-īśhvaraḥ—the Supreme Lord of Yog; hariḥ—Shree Krishna; darśhayām āsa—displayed; pārthāya—to Arjun; paramam—divine; rūpam aiśhwaram—opulence'::text),'Sanjaya said, Having thus spoken, O king, the great Lord of Yoga, Hari (Krishna), showed Arjuna His supreme form as the Lord.','Swami Sivananda','11.9 एवम् thus? उक्त्वा having spoken? ततः then? राजन् O king? महायोगेश्वरः the great Lord of Yoga? हरिः Hari? दर्शयामास showed? पार्थाय to Arjuna? परमम् Supreme? रूपम् form? ऐश्वरम् Sovereign.Commentary King This verse is addressed by Sanjaya to Dhritarashtra.Supreme Form The Cosmic Form.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bwmb000au7eu6fmf61a0',10,424,'11-10','अनेकवक्त्रनयनमनेकाद्भुतदर्शनम्।

अनेकदिव्याभरणं दिव्यानेकोद्यतायुधम्।।11.10।।','aneka-vaktra-nayanam anekādbhuta-darśhanam
aneka-divyābharaṇaṁ divyānekodyatāyudham',to_json('aneka—many; vaktra—faces; nayanam—eyes; aneka—many; adbhuta—wonderful; darśhanam—had a vision of; aneka—many; divya—divine; ābharaṇam—ornaments; divya—divine; aneka—many; udyata—uplifted; āyudham—weapons;'::text),'With numerous mouths and eyes, with numerous wondrous sights, with numerous divine adornments, with numerous divine weapons uplifted, such a form He showed.','Swami Sivananda','11.10 अनेकवक्त्रनयनम् with numerous mouthsand eyes? अनेकाद्भुतदर्शनम् with numerous wonderful sights? अनेकदिव्याभरणम् with numerous divine ornaments? दिव्यानेकोद्यतायुधम् with numerous divine weapons uplifted.Commentary Countless faces appeared there. Arjuna looked at this Cosmic Form in all its magnificence. He saw the Lord everywhere and in everything. The whole manifestation appeared as one gigantic body of the Lord. He saw the Lord as the allinall.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bwmb000au7eu6fmf61a0',11,425,'11-11','दिव्यमाल्याम्बरधरं दिव्यगन्धानुलेपनम्।

सर्वाश्चर्यमयं देवमनन्तं विश्वतोमुखम्।।11.11।।','divya-mālyāmbara-dharaṁ divya-gandhānulepanam
sarvāśhcharya-mayaṁ devam anantaṁ viśhvato-mukham',to_json('divya—divine; mālya—garlands; āmbara—garments; dharam—wearing; divya—divine; gandha—fragrances; anulepanam—anointed with; sarva—all; āśhcharya-mayam—wonderful; devam—Lord; anantam—unlimited; viśhwataḥ—all sides; mukham—face'::text),'Wearing divine garlands and apparel, anointed with divine unguents, the all-wonderful, resplendent Being is endless with faces on all sides.','Swami Sivananda','11.11 दिव्यमाल्याम्बरधरम् wearing divine garlands (necklaces) and apparel? दिव्यगन्धानुलेपनम् anointed with divine unguents? सर्वाश्चर्यमयम् the allwonderful? देवम् resplendent? अनन्तम् endless? विश्वतोमुखम् with faces on all sides.Commentary Visvatomukham With faces on all sides? as He is the Self of all beings.Devam God. Also means resplendent.Anantam Endless. He Who is free from the three kinds of limitations? viz.? DesaKalaVastuPariccheda (limitations of space? time? and thing respectively) is Anantam. He is Brahman. This philosophical concept is explained below.The pot is here. This is spacelimitatio. The pot is now here. This is timelimitation. The pot is not a cloth. This is thing(material) limitation. There is saffron in Kashmir only. This is limitation of space and thing. You can have apples only in September. This is limitation of time and thing. But Brahman is everywhere? as It is allpervading. It exists in the past? the present and the future. It dwells in all parts. Hence It is beyond these three limitations. It is therefore endless.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bwmb000au7eu6fmf61a0',12,426,'11-12','दिवि सूर्यसहस्रस्य भवेद्युगपदुत्थिता।

यदि भाः सदृशी सा स्याद्भासस्तस्य महात्मनः।।11.12।।','divi sūrya-sahasrasya bhaved yugapad utthitā
yadi bhāḥ sadṛiśhī sā syād bhāsas tasya mahātmanaḥ',to_json('divi—in the sky; sūrya—suns; sahasrasya—thousand; bhavet—were; yugapat—simultaneously; utthitā—rising; yadi—if; bhāḥ—splendor; sadṛiśhī—like; sā—that; syāt—would be; bhāsaḥ—splendor; tasya—of them; mahā-ātmanaḥ—the great personality'::text),'If the splendour of a thousand suns were to blaze out simultaneously in the sky, that would be the splendour of that mighty being.','Swami Sivananda','11.12 दिवि in the sky? सूर्यसहस्रस्य of a thousand suns? भवेत् were? युगपत् at once (simultaneously)? उत्थिता arisen? यदि if? भाः splendour? सदृशी like? सा that? स्यात् would be? भासः splendour? तस्य of that? महात्मनः of the mighty Being (great soul).Commentary Divi here means in the Antariksha or the sky.Mahatma here refers to the great Soul or the mighty Being? the Cosmic Form.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bwmb000au7eu6fmf61a0',13,427,'11-13','तत्रैकस्थं जगत्कृत्स्नं प्रविभक्तमनेकधा।

अपश्यद्देवदेवस्य शरीरे पाण्डवस्तदा।।11.13।।','tatraika-sthaṁ jagat kṛitsnaṁ pravibhaktam anekadhā
apaśhyad deva-devasya śharīre pāṇḍavas tadā',to_json('tatra—there; eka-stham—established in one place; jagat—the universe; kṛitsnam—entire; pravibhaktam—divided; anekadhā—many; apaśhyat—could see; deva-devasya—of the God of gods; śharīre—in the body; pāṇḍavaḥ—Arjun; tadā—at that time'::text),'There, in the body of the God of gods, Arjuna then saw the entire universe resting in one, with its myriad of divisions.','Swami Sivananda','11.13 तत्र there? एकस्थम् resting in one? जगत् the universe? कृत्स्नम् the whole? प्रविभक्तम् divided? अनेकधा in many groups? अपश्यत् saw? देवदेवस्य of the God of gods? शरीरे in the body? पाण्डवः son of Pandu? तदा then.Commentary Tatra There -- in the Cosmic Form.Anekadha Many groups -- gods? manes? men and other species of beings.Arjuna beheld all forms as the forms of the Lord? all heads as His heads? all eyes as His eyes? all hands as His hands? all feet as His feet? every part of every body as the limb of the Lords divine form. Wherever he looked he beheld nothing but the Lord. He got mystic divine knowledge.Sanjaya has given a truly graphic description of the Cosmic Form. Yet? it would be futile to grasp it with the finite mind. It is a transcendental vision? beyond the reach of the mind and senses. It has to be realised in Samadhi.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bwmb000au7eu6fmf61a0',14,428,'11-14','ततः स विस्मयाविष्टो हृष्टरोमा धनञ्जयः।

प्रणम्य शिरसा देवं कृताञ्जलिरभाषत।।11.14।।','tataḥ sa vismayāviṣhṭo hṛiṣhṭa-romā dhanañjayaḥ
praṇamya śhirasā devaṁ kṛitāñjalir abhāṣhata',to_json('tataḥ—then; saḥ—he; vismaya-āviṣhṭaḥ—full of wonder; hṛiṣhṭa-romā—with hair standing on end; dhanañjayaḥ—Arjun, the conqueror of wealth; praṇamya—bow down; śhirasā—with (his) head; devam—the Lord; kṛita-añjaliḥ—with folded hands; abhāṣhata—he addressed'::text),'Then, Arjuna, filled with wonder and his hair standing on end, bowed his head to the God and spoke with palms joined.','Swami Sivananda','11.14 ततः then? सः he? विस्मयाविष्टः filled with wonder? हृष्टरोमा with hair standing on end? धनञ्जयः Arjuna? प्रणम्य having prostrated? शिरसा with (his) head? देवम् the God? कृताञ्जलिः with joined palms? अभाषत spoke.Commentary Tatah Then? having seen the Cosmic Form.Arjuna joined his palms in order to do prostration to the Cosmic Form. The great hero had attained true humility which the bowed head and joined palms represented? and which is the essential ingredient of devotion.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bwmb000au7eu6fmf61a0',15,429,'11-15','अर्जुन उवाच

पश्यामि देवांस्तव देव देहे

सर्वांस्तथा भूतविशेषसङ्घान्।

ब्रह्माणमीशं कमलासनस्थ

मृषींश्च सर्वानुरगांश्च दिव्यान्।।11.15।।','arjuna uvācha
paśhyāmi devāns tava deva dehe
sarvāns tathā bhūta-viśheṣha-saṅghān
brahmāṇam īśhaṁ kamalāsana-stham
ṛiṣhīnśh cha sarvān uragānśh cha divyān',to_json('arjunaḥ uvācha—Arjun said; paśhyāmi—I behold; devān—all the gods; tava—your; deva—Lord; dehe—within the body; sarvān—all; tathā—as well as; bhūta viśheṣha-saṅghān—hosts of different beings; brahmāṇam—Lord Brahma; īśham—Shiv; kamala-āsana-stham—seated on the lotus flower; ṛiṣhīn—sages; cha—and; sarvān—all; uragān—serpents; cha—and; divyān—divine'::text),'Arjuna said, "O God, I see all the gods in Your body, as well as hosts of various classes of beings, Brahma the Lord seated on the lotus, all the sages, and the celestial serpents."','Swami Sivananda','11.15 पश्यामि (I) see? देवान् the gods? तव Thy? देव O God? देहे in the body? सर्वान् all? तथा also? भूतविशेषसङ्घान् hosts of various classes of beings? ब्रह्माणम् Brahma? ईशम् the Lord? कमलासनस्थम् seated on the lotus? ऋषीन् sages? च and? सर्वान् all? उरगान् serpents? च and? दिव्यान् divine.Commentary Arjuna describes his own experience of the Cosmic Form in this and the following verses? 15 to 31.Bhutaviseshasanghan Hosts of various classes of beings? both animate and inanimate. These numerous entities are in Thy Cosmic Form? like hairs on the human body.Brahma? the fourfaced? the Lord of all creatures? is seated in the centre of the earthlotus on the Meru which forms the thalamus as it were of the earthlotus.Sages? such as Vasishtha. Serpents? such as Vasuki.Moreover --','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bwmb000au7eu6fmf61a0',16,430,'11-16','अनेकबाहूदरवक्त्रनेत्रं

पश्यामि त्वां सर्वतोऽनन्तरूपम्।

नान्तं न मध्यं न पुनस्तवादिं

पश्यामि विश्वेश्वर विश्वरूप।।11.16।।','aneka-bāhūdara-vaktra-netraṁ
paśhyāmi tvāṁ sarvato ’nanta-rūpam
nāntaṁ na madhyaṁ na punas tavādiṁ
paśhyāmi viśhveśhvara viśhva-rūpa',to_json('aneka—infinite; bāhu—arms; udara—stomachs; vaktra—faces; netram—eyes; paśhyāmi—I see; tvām—you; sarvataḥ—in every direction; ananta-rūpam—inifinite forms; na antam—without end; na—not; madhyam—middle; na—no; punaḥ—again; tava—your; ādim—beginning; paśhyāmi—I see; viśhwa-īśhwara—The Lord of the universe; viśhwa-rūpa—universal form'::text),'I see You with boundless form on every side, with many arms, stomachs, mouths, and eyes; neither the end nor the middle nor the beginning do I see, O Lord of the Universe, O Cosmic Form.','Swami Sivananda','11.16 अनेकबाहूदरवक्त्रनेत्रम् with manifold arms? stomachs? mouths and eyes? पश्यामि (I) see? त्वाम् Thee? सर्वतः on every side? अनन्तरूपम् of boundless form? न not? अनत्म् end? न not? मध्यम् middle? न not? पुनः,again? तव Thy? आदिम् origin? पश्यामि (I) see? विश्वेश्वर O Lord of the universe? विश्वरूप O Cosmic Form.Commentary A thing that is limited by space and time has a begining? a middle and an end? but the Lord is omnipresent and eternal. He exists in the three periods of time -- past? present and future? but is not limited by time and space. Therefore He has neither a beginning nor middle nor end.Arjuna could have this divine vision only with the help of the divine eye bestowed upon him by the Lord. He who has supreme devotion to the Lord and on whom the Lord showers His grace can enjoy this wondrous vision.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bwmb000au7eu6fmf61a0',17,431,'11-17','किरीटिनं गदिनं चक्रिणं च

तेजोराशिं सर्वतोदीप्तिमन्तम्।

पश्यामि त्वां दुर्निरीक्ष्यं समन्ता

द्दीप्तानलार्कद्युतिमप्रमेयम्।।11.17।।','kirīṭinaṁ gadinaṁ chakriṇaṁ cha
tejo-rāśhiṁ sarvato dīptimantam
paśhyāmi tvāṁ durnirīkṣhyaṁ samantād
dīptānalārka-dyutim aprameyam',to_json('kirīṭinam—adorned with a crown; gadinam—with club; chakriṇam—with discs; cha—and; tejaḥ-rāśhim—abode of splendor; sarvataḥ—everywhere; dīpti-mantam—shining; paśhyāmi—I see; tvām—you; durnirīkṣhyam—difficult to look upon; samantāt—in all directions; dīpta-anala—blazing fire; arka—like the sun; dyutim—effulgence; aprameyam—immeasurable'::text),'I see You with the diadem, club, and discus, a mass of radiance shining everywhere, very hard to look at, blazing all around like a burning fire and the sun, and immeasurable.','Swami Sivananda','11.17 किरीटिनम् one with diadem? गदिनम् with club? चक्रिणम् with discus? च and? तेजोराशिम् a mass of radiance? सर्वतः everywhere? दीप्तिमन्तम् shining? पश्यामि (I) see? त्वाम् Thee? दुर्निरीक्ष्यम् very hard to look at? समन्तात् all round? दीप्तानलार्कद्युतिम् blazing like burning fire and sun? अप्रमेयम् immeasurable.Commentary Kiritam is a special ornament for the head? the crown.Arjuna had worshipped the Lord as having a crown? club and discus and the Lord showed him the same form now. He is in all forms and He is beyond all forms as the transcendental Reality. Who can comprehend His GloryTejorasim A mass of splendour that cannot be perceived without the inner divine eye of intuition.Aprameyam Immeasurable? whose limits cannot be fixed.I infer from this vision of Thy power of Yoga that Thu art the Imperishable? etc.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bwmb000au7eu6fmf61a0',18,432,'11-18','त्वमक्षरं परमं वेदितव्यं

त्वमस्य विश्वस्य परं निधानम्।

त्वमव्ययः शाश्वतधर्मगोप्ता

सनातनस्त्वं पुरुषो मतो मे।।11.18।।','tvam akṣharaṁ paramaṁ veditavyaṁ
tvam asya viśhvasya paraṁ nidhānam
tvam avyayaḥ śhāśhvata-dharma-goptā
sanātanas tvaṁ puruṣho mato me',to_json('tvam—you; akṣharam—the imperishable; paramam—the supreme being; veditavyam—worthy of being known; tvam—you; asya—of this; viśhwasya—of the creation; param—supreme; nidhānam—support; tvam—you; avyayaḥ—eternal; śhāśhvata-dharma-goptā—protector of the eternal religion; sanātanaḥ—everlasting; tvam—you; puruṣhaḥ—the Supreme Divine Person; mataḥ me—my opinion'::text),'You are the Imperishable, the Supreme Being, worthy of being known. You are the great treasure-house of this universe; You are the imperishable protector of the eternal Dharma; You are the Primal Person, I believe.','Swami Sivananda','11.18 त्वम् Thou? अक्षरम् imperishable? परमम् the Supreme Being? वेदितव्यम् worthy to be known? त्वम् Thou? अस्य (of) this? विश्वस्य of universe? परम् the great? निधानम् treasurehouse? त्वम् Thou? अव्ययः imperishable? शाश्वतधर्मगोप्ता Protector of the Eternal Dharma? सनातनः ancient? त्वम् Thou? पुरुषः Purusha? मतः thought? मे of me.Commentary VisvasyaNidhaanam Treasurehouse of this universe? also means abode or refuge or the substratum of this universe. It is because of this that all the beings in the universe are preserved and protected. He is the inexhaustibel source to Whom the devotee turns at all times. Deluded indeed are they that ignore this divine treasurehouse and runa fter the shadow of the objects of the senses which do not contain even an iota of pleasure.Veditavyam To be known by the aspirants or seekrs of liberation? through Sravana (hearing of the scriptures)? Manana (reflection) and Nididhyasana (meditation).Avyayah means inexhaustible? unchanging? undying.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bwmb000au7eu6fmf61a0',19,433,'11-19','अनादिमध्यान्तमनन्तवीर्य

मनन्तबाहुं शशिसूर्यनेत्रम्।

पश्यामि त्वां दीप्तहुताशवक्त्रम्

स्वतेजसा विश्वमिदं तपन्तम्।।11.19।।','स्वतेजसा विश्वमिदं तपन्तम् || 19||',to_json('anādi-madhyāntam ananta-vīryam
ananta-bāhuṁ śhaśhi-sūrya-netram
paśhyāmi tvāṁ dīpta-hutāśha-vaktraṁ
sva-tejasā viśhvam idaṁ tapantam'::text),'I see You without beginning, middle, or end, infinite in power, with endless arms, the sun and moon as Your eyes, the burning fire Your mouth, heating the entire universe with Your radiance.','Swami Sivananda','11.19 अनादिमध्यान्तम् without beginning? middle or end? अनन्तवीर्यम् infinite in power? अनन्तबाहुम् of endless arms? शशिसूर्यनेत्रम् Thy eyes as the sun and the moon? पश्यामि (I) see? त्वाम् Thee? दीप्तहुताशवक्त्रम् Thy mouth as the burning fire? स्वतेजसा with Thy radiance? विश्वम् the universe? इदम् this? तपन्तम् heating.Commentary Anantabahu Having endless arms. This denotes that the multiplicity of His limbs are endless.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bwmb000au7eu6fmf61a0',20,434,'11-20','द्यावापृथिव्योरिदमन्तरं हि

व्याप्तं त्वयैकेन दिशश्च सर्वाः।

दृष्ट्वाऽद्भुतं रूपमुग्रं तवेदं

लोकत्रयं प्रव्यथितं महात्मन्।।11.20।।','dyāv ā-pṛithivyor idam antaraṁ hi
vyāptaṁ tvayaikena diśhaśh cha sarvāḥ
dṛiṣhṭvādbhutaṁ rūpam ugraṁ tavedaṁ
loka-trayaṁ pravyathitaṁ mahātman',to_json('dyau-ā-pṛithivyoḥ—between heaven and earth; idam—this; antaram—space between; hi—indeed; vyāptam—pervaded; tvayā—by you; ekena—alone; diśhaḥ—directions; cha—and; sarvāḥ—all; dṛiṣhṭvā—seeing; adbhutam—wondrous; rūpam—form; ugram—terrible; tava—your; idam—this; loka—worlds; trayam—three; pravyathitam—trembling; mahā-ātman—The greatest of all beings'::text),'This space between the earth and the heavens, and all the quarters, is filled by You alone; having seen this, Your wonderful and terrible form, the three worlds are trembling with fear, O great-souled Being.','Swami Sivananda','11.20 द्यावापृथिव्योः of heaven and earth? इदम् this? अन्तरम् interspace? हि indeed? व्याप्तम् is filled? त्वया by Thee? एकेन alone? दिशः arters? च and? सर्वाः all? दृष्ट्वा having seen? अद्भुतम् wonderful? रूपम् form? उग्रम् terrible? तव Thy? इदम् this? लोकत्रयम् the three worlds? प्रव्यथितम् are trembling with fear? महात्मन् O greatsouled Being.Commentary Thee In Thy Cosmic Form.The space and the arters This denotes that the Lord has filled the whole universe of animate and inanimate objects.In order to remove the doubt entertained by Arjuna as to his success (Cf.II.6) Lord Krishna makes him feel now that victoyr for the Pandavas is certain.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bwmb000au7eu6fmf61a0',21,435,'11-21','अमी हि त्वां सुरसङ्घाः विशन्ति

केचिद्भीताः प्राञ्जलयो गृणन्ति।

स्वस्तीत्युक्त्वा महर्षिसिद्धसङ्घाः

स्तुवन्ति त्वां स्तुतिभिः पुष्कलाभिः।।11.21।।','amī hi tvāṁ sura-saṅghā viśhanti
kechid bhītāḥ prāñjalayo gṛiṇanti
svastīty uktvā maharṣhi-siddha-saṅghāḥ
stuvanti tvāṁ stutibhiḥ puṣhkalābhiḥ',to_json('amī—these; hi—indeed; tvām—you; sura-saṅghāḥ—assembly of celestial gods; viśhanti—are entering; kechit—some; bhītāḥ—in fear; prāñjalayaḥ—with folded hands; gṛiṇanti—praise; svasti—auspicious; iti—thus; uktvā—reciting; mahā-ṛiṣhi—great sages; siddha-saṅghāḥ—perfect beings; stuvanti—are extolling; tvām—you; stutibhiḥ—with prayers; puṣhkalābhiḥ—hymns'::text),'Verily, these hosts of gods enter into Thee; some extol Thee with joined palms in fear, saying, ''May it be well!'' Bands of great sages and perfected ones praise Thee with complete hymns.','Swami Sivananda','11.21 अमी these? हि verily? त्वाम् Thee? सुरसङ्घाः hosts of gods? विशन्ति enter? केचित् some? भीताः in fear? प्राञ्जलयः with joined palms? गृणन्ति extol? स्वस्ति may it be well? इति thus? उक्त्वा having said? महर्षिसिद्धसङ्घाः bands of great Rishis and Siddhas? स्तुवन्ति paise? त्वाम् Thee? स्तुतिभिः with hymns? पुष्कलाभिः complete.Commentary Pushkalabhih means complete or wellworded praises or praises full of deep meanings.Great sages like Narada and perfected ones like Kapila praise Thee with inspiring hymns.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bwmb000au7eu6fmf61a0',22,436,'11-22','रुद्रादित्या वसवो ये च साध्या

विश्वेऽश्िवनौ मरुतश्चोष्मपाश्च।

गन्धर्वयक्षासुरसिद्धसङ्घा

वीक्षन्ते त्वां विस्मिताश्चैव सर्वे।।11.22।।','rudrādityā vasavo ye cha sādhyā
viśhve ’śhvinau marutaśh choṣhmapāśh cha
gandharva-yakṣhāsura-siddha-saṅghā
vīkṣhante tvāṁ vismitāśh chaiva sarve',to_json('rudra—a form of Lord Shiv; ādityāḥ—the Adityas; vasavaḥ—the Vasus; ye—these; cha—and; sādhyāḥ—the Sadhyas; viśhve—the Vishvadevas; aśhvinau—the Ashvini kumars; marutaḥ—the Maruts; cha—and; uṣhma-pāḥ—the ancestors; cha—and; gandharva—Gandharvas; yakṣha—the Yakshas; asura—the demons; siddha—the perfected beings; saṅghāḥ—the assemblies; vīkṣhante—are beholding; tvām—you; vismitāḥ—in wonder; cha—and; eva—verily; sarve—all'::text),'The Rudras, Adityas, Vasus, Sadhyas, Visvedevas, the two Asvins, Maruts, the Manus, and the hosts of celestial singers, Yakshas, demons, and the perfected ones, all look upon Thee with great amazement.','Swami Sivananda','11.22 रुद्रादित्याः Rudras and Adityas? वसवः Vasus? ये these? च and? साध्याः Sadhyas? विश्वे Visvedevas? अश्िवनौ the two Asvins? मरुतः Maruts? च and? उष्मपाः Pitris? च and? गन्धर्वयक्षासुरसिद्धसङ्घाः hosts of Gandharvas? Yakshas? Asuras and Siddhas? वीक्षन्ते are looking at? त्वाम् Thee? विस्मिताः astonished? च and? एव even? सर्वे all.Commentary Sadhyas are a class of gods of whom Brahma is the chief.Visvedevas are ten gods who in Vedic times were considered as protectors of human beings. They were called guardians of the world. They were givers of plenty to the human beings. Their names are Krata? Daksha? Vasu? Satya? Kama? Kala? Dhvani? Rochaka? Adrava and Pururava.The two Asvins? born of Prabha (light)? daughter of Tushta and the Sun? are the physicians of the gods.Rudras? Adityas? Vasus and Maruts -- see tenth chapter? verses 21 and 23.Ushmapa A class of manes. They accept the food offered in the Sraaddha (anniversary) ceremony or the obseies? while it is hot. Hence they are called Ushmapas. There are seven groups of manes.Gandharvas are celestial singers such as Haha and Huhu.Yakshas such as Kubera (the god of wealth) Asuras such as Virochana perfected ones such as Kapila.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bwmb000au7eu6fmf61a0',23,437,'11-23','रूपं महत्ते बहुवक्त्रनेत्रं

महाबाहो बहुबाहूरुपादम्।

बहूदरं बहुदंष्ट्राकरालं

दृष्ट्वा लोकाः प्रव्यथितास्तथाऽहम्।।11.23।।','rūpaṁ mahat te bahu-vaktra-netraṁ
mahā-bāho bahu-bāhūru-pādam
bahūdaraṁ bahu-danṣhṭrā-karālaṁ
dṛiṣhṭvā lokāḥ pravyathitās tathāham',to_json('rūpam—form; mahat—magnificent; te—your; bahu—many; vaktra—mouths; netram—eyes; mahā-bāho—mighty-armed Lord; bahu—many; bāhu—arms; ūru—thighs; pādam—legs; bahu-udaram—many stomachs; bahu-danṣhṭrā—many teeth; karālam—terrifying; dṛiṣhṭvā—seeing; lokāḥ—all the worlds; pravyathitāḥ—terror-stricken; tathā—so also; aham—I'::text),'Having seen Your immeasurable form with many mouths and eyes, O mighty-armed one, with many arms, thighs, and feet, with many stomachs and fearsome with many teeth, the worlds are terrified, and so am I.','Swami Sivananda','11.23 रूपम् form? महत् immeasurable? ते Thy? बहुवक्त्रनेत्रम् with many mouths and eyes? महाबाहो O,mightyarmed? बहुबाहूरुपादम् with many arms? thighs and feet? बहूदरम् with many stomachs. बहुदंष्ट्राकरालम् fearful with many teeth? दृष्ट्वा having seen? लोकाः the worlds? प्रव्यथिताः are terrified? तथा also? अहम् I.Commentary Lokah The worlds -- all living beings in the world. Here is the cause of my fear. Arjuna describes below the nature of the Cosmic Form which has caused terror in his heart.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bwmb000au7eu6fmf61a0',24,438,'11-24','नभःस्पृशं दीप्तमनेकवर्णं

व्यात्ताननं दीप्तविशालनेत्रम्।

दृष्ट्वा हि त्वां प्रव्यथितान्तरात्मा

धृतिं न विन्दामि शमं च विष्णो।।11.24।।','nabhaḥ-spṛiśhaṁ dīptam aneka-varṇaṁ
vyāttānanaṁ dīpta-viśhāla-netram
dṛiṣhṭvā hi tvāṁ pravyathitāntar-ātmā
dhṛitiṁ na vindāmi śhamaṁ cha viṣhṇo',to_json('nabhaḥ-spṛiśham—touching the sky; dīptam—effulgent; aneka—many; varṇam—colors; vyātta—open; ānanam—mouths; dīpta—blazing; viśhāla—enormous; netram—eyes; dṛiṣhṭvā—seeing; hi—indeed; tvām—you; pravyathitāntar-ātmā—my heart is trembling with fear; dhṛitim—firmness; na—not; vindāmi—I find; śhamam—mental peace; cha—and; viṣhṇo—Lord Vishnu'::text),'On seeing Thee, touching the sky, shining in many colors, with mouths wide open, with large fiery eyes, I am terrified at heart and find neither courage nor peace, O Vishnu.','Swami Sivananda','11.24 नभःस्पृशम् touching the sky? दीप्तम् shining? अनेकवर्णम् in many colours? व्यात्ताननम् with mouths wide open? दीप्तविशालनेत्रम् with larve fiery eyes? दृष्ट्वा having seen? हि verily? त्वाम् Thee? प्रव्यथितान्तरात्मा terrified at heart? धृतिम् courage? न not? विन्दामि (I) find? शमम् peace? च and? विष्णो O Vishnu.Commentary Dhriti also means patience and strength. Sama also means control.The vision of the Cosmic Form has frightened Arjuna considerably.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bwmb000au7eu6fmf61a0',25,439,'11-25','दंष्ट्राकरालानि च ते मुखानि

दृष्ट्वैव कालानलसन्निभानि।

दिशो न जाने न लभे च शर्म

प्रसीद देवेश जगन्निवास।।11.25।।','danṣhṭrā-karālāni cha te mukhāni
dṛiṣhṭvaiva kālānala-sannibhāni
diśho na jāne na labhe cha śharma
prasīda deveśha jagan-nivāsa',to_json('danṣhṭrā—teeth; karālāni—terrible; cha—and; te—your; mukhāni—mouths; dṛiṣhṭvā—having seen; eva—indeed; kāla-anala—the fire of annihilation; sannibhāni—resembling; diśhaḥ—the directions; na—not; jāne—know; na—not; labhe—I obtain; cha—and; śharma—peace; prasīda—have mercy; deva-īśha—The Lord of lords; jagat-nivāsa—The shelter of the universe'::text),'Having seen Thy mouths fearful with teeth blazing like the fires of cosmic dissolution, I know not the four quarters, nor do I find peace. Have mercy, O Lord of the gods, O abode of the universe.','Swami Sivananda','11.25 दंष्ट्राकरालानि fearful with teeth? च and? ते Thy? मुखानि mouths? दृष्ट्वा having seen? एव even? कालानलसन्निभानि blazing like Pralayafires? दिशः the four arters? न not? जाने know? न not? लभे do (I) obtain? च and? शर्म peace? प्रसीद have mercy? देवेश O Lord of the gods? जगन्निवास O abode of the universe.Commentary Jagannivasa The substratum of the universe.Kalanala The fires which consume the worlds during the final dissolution of the worlds (Pralaya). Time (Kala) is the consumer of all that is manifest.Diso no jane I do not know the four arters. I cannot distinguish the east from the west? nor the north from the south.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bwmb000au7eu6fmf61a0',26,440,'11-26','अमी च त्वां धृतराष्ट्रस्य पुत्राः

सर्वे सहैवावनिपालसङ्घैः।

भीष्मो द्रोणः सूतपुत्रस्तथाऽसौ

सहास्मदीयैरपि योधमुख्यैः।।11.26।।','amī cha tvāṁ dhṛitarāśhtrasya putrāḥ
sarve sahaivāvani-pāla-saṅghaiḥ
bhīṣhmo droṇaḥ sūta-putras tathāsau
sahāsmadīyair api yodha-mukhyaiḥ
 vaktrāṇi te tvaramāṇā viśhanti
danṣhṭrā-karālāni bhayānakāni
kechid vilagnā daśhanāntareṣhu
sandṛiśhyante chūrṇitair uttamāṅgaiḥ',to_json('amī—these; cha—and; tvām—you; dhṛitarāśhtrasya—of Dhritarashtra; putrāḥ—sons; sarve—all; saha—with; eva—even; avani-pāla—their allied kings; sanghaiḥ—assembly; bhīṣhmaḥ—Bheeshma; droṇaḥ—Dronacharya; sūta-putraḥ—Karna; tathā—and also; asau—this; saha—with; asmadīyaiḥ—from our side; api—also; yodha-mukhyaiḥ—generals;
 vaktrāṇi—mouths; te—your; tvaramāṇāḥ—rushing; viśhanti—enter; danṣhṭrā—teeth; karālāni—terrible; bhayānakāni—fearsome; kechit—some; vilagnāḥ—getting stuck; daśhana-antareṣhu—between the teeth; sandṛiśhyante—are seen; chūrṇitaiḥ—getting smashed; uttama-aṅgaiḥ—heads'::text),'All the sons of Dhritarashtra, along with the hosts of kings of the earth, Bhishma, Drona, and Karna, as well as the chief among our warriors.','Swami Sivananda','11.26 अमी these? च and? त्वाम् Thee? धृतराष्ट्रस्य of Dhritarashtra? पुत्राः sons? सर्वे all? सह with? एव even? अवनिपालसङ्घैः hosts of kings? भीष्मः Bhishma? द्रोणः Drona? सूतपुत्रः Karana? तथा also? असौ this? सह with? अस्मदीयैः with (those) of ours? अपि also? योधमुख्यैः (with) warrior chiefs.Commentary Karna? though he was the son of Kunti? the mother of the Pandavas? was brought up by a charioteer and hence came to be regarded as his son.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bwmb000au7eu6fmf61a0',27,441,'11-27','वक्त्राणि ते त्वरमाणा विशन्ति

दंष्ट्राकरालानि भयानकानि।

केचिद्विलग्ना दशनान्तरेषु

संदृश्यन्ते चूर्णितैरुत्तमाङ्गैः।।11.27।।','vaktrāṇi te  tvaramāṇā   viśanti daṁṣṭrā-karālāni    bhayānakāni kecid   vilagnā daśanāntareṣu   sandṛśyante cūrṇitair   uttamāṅgaiḥ',to_json('vaktrāṇi—mouths;   te—Your;    tvaramāṇāḥ—fearful;     viśanti—entering;   daṁṣṭrā—teeth;  karālāni—terrible;  bhayānakāni—very    fearful;    kecit—some  of  them;   vilagnāḥ—being  attacked;   daśanāntareṣu—between   the teeth;  sandṛśyante—being   seen;   cūrṇitaiḥ—smashed;  uttama-aṅgaiḥ—by    the head'::text),'Some hurry into Your mouths with their terrible teeth, fearful to behold. Some are found stuck in the gaps between the teeth, their heads crushed to powder.','Swami Sivananda','11.27 वक्त्राणि mouths? ते Thy? त्वरमाणाः hurrying? विशन्ति enter? दंष्ट्राकरालानि terribletoothed? भयानकानि fearful to behold? केचित् some? विलग्नाः sticking? दशनान्तरेषु in the gaps between the teeth? संदृश्यन्ते are found? चूर्णितैः crushed to powder? उत्तमाङ्गैः with (their) heads.Commentary How do they enter into the mouth Arjuna continues','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bwmb000au7eu6fmf61a0',28,442,'11-28','यथा नदीनां बहवोऽम्बुवेगाः

समुद्रमेवाभिमुखाः द्रवन्ति।

तथा तवामी नरलोकवीरा

विशन्ति वक्त्राण्यभिविज्वलन्ति।।11.28।।','yathā nadīnāṁ bahavo ’mbu-vegāḥ
samudram evābhimukhā dravanti
tathā tavāmī nara-loka-vīrā
viśhanti vaktrāṇy abhivijvalanti',to_json('yathā—as; nadīnām—of the rivers; bahavaḥ—many; ambu-vegāḥ—water waves; samudram—the ocean; eva—indeed; abhimukhāḥ—toward; dravanti—flowing rapidly; tathā—similarly; tava—your; amī—these; nara-loka-vīrāḥ—kings of human society; viśhanti—enter; vaktrāṇi—mouths; abhivijvalanti—blazing;'::text),'Verily, just as many torrents of rivers flow towards the ocean, so too these heroes in the world of men enter Thy flaming mouths.','Swami Sivananda','11.28 यथा as? नदीनाम् of rivers? बहवः many? अम्बुवेगाः watercurrents? समुद्रम् to the ocean? एव verily? अभिमुखाः towards? द्रवन्ति flow? तथा so? तव Thy? अमी these? नरलोकवीराः heroes in the world of men? विशन्ति enter? वक्त्राणि mouths? अभिविज्वलन्ति flaming.Commentary Ami These warriors such as Bhishma. Arjuna is now seeing all these warriors,whom he did not wish to kill? rushing to death. His delusion has vanished. He thinks now This battle cannot be avoided. It has the sanction of the Supreme Lord. Why should I worry about the inevitable The Lord has already destroyed these warriors. I am only an instrument in His hands. No sin can touch me even if I kill them. This is a just cause also.Why and how do they enter Arjuna says --','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bwmb000au7eu6fmf61a0',29,443,'11-29','यथा प्रदीप्तं ज्वलनं पतङ्गा

विशन्ति नाशाय समृद्धवेगाः।

तथैव नाशाय विशन्ति लोका

स्तवापि वक्त्राणि समृद्धवेगाः।।11.29।।','yathā pradīptaṁ jvalanaṁ pataṅgā
viśhanti nāśhāya samṛiddha-vegāḥ
tathaiva nāśhāya viśhanti lokās
tavāpi vaktrāṇi samṛiddha-vegāḥ',to_json('yathā—as; pradīptam—blazing; jvalanam—fire; pataṅgāḥ—moths; viśhanti—enter; nāśhāya—to be perished; samṛiddha vegāḥ—with great speed; tathā eva—similarly; nāśhāya—to be perished; viśhanti—enter; lokāḥ—these people; tava—your; api—also; vaktrāṇi—mouths; samṛiddha-vegāḥ—with great speed'::text),'As moths hurriedly rush into a blazing fire, leading to their own destruction, so too these creatures hurry into Your mouths, leading to their own destruction.','Swami Sivananda','11.29 यथा as? प्रदीप्तम् blazing? ज्वलनम् fire? पतङ्गाः moths? विशन्ति enter? नाशाय to destruction? समृद्धवेगाः with ickened speed? तथा so? एव only? नाशाय to destruction? विशन्ति enter? लोकाः creatures? तव Thy? अपि also? वक्त्राणि mouths? समृद्धवेगाः with ickened speed.No Commentary.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bwmb000au7eu6fmf61a0',30,444,'11-30','लेलिह्यसे ग्रसमानः समन्ता

ल्लोकान्समग्रान्वदनैर्ज्वलद्भिः।

तेजोभिरापूर्य जगत्समग्रं

भासस्तवोग्राः प्रतपन्ति विष्णो।।11.30।।','lelihyase grasamānaḥ samantāl
lokān samagrān vadanair jvaladbhiḥ
tejobhir āpūrya jagat samagraṁ
bhāsas tavogrāḥ pratapanti viṣhṇo',to_json('lelihyase—you are licking; grasamānaḥ—devouring; samantāt—on all sides; lokān—worlds; samagrān—all; vadanaiḥ—with mouths; jvaladbhiḥ—blazing; tejobhiḥ—by effulgence; āpūrya—filled with; jagat—the universe; samagram—all; bhāsaḥ—rays; tava—your; ugrāḥ—fierce; pratapanti—scorching; viṣhṇo—Lord Vishnu'::text),'Thou lickest up, devouring all the worlds on every side with Thy flaming mouths. Thy fierce rays, filling the whole world with radiance, burn, O Vishnu!','Swami Sivananda','11.30 लेलिह्यसे (Thou) lickest? ग्रसमानः devouring? समन्तात् on every side? लोकान् the worlds? समग्रान् all? वदनैः with mouths? ज्वलद्भिः flaming? तेजोभिः with radiance? आपूर्य filling? जगत् the world? समग्रम् the whole? भासः rays? तव Thy? उग्राः fierce? प्रतपन्ति are burning? विष्णो O VishnuCommentary Vishnu means allpervading? Vyapanasila.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bwmb000au7eu6fmf61a0',31,445,'11-31','आख्याहि मे को भवानुग्ररूपो

नमोऽस्तु ते देववर प्रसीद।

विज्ञातुमिच्छामि भवन्तमाद्यं

न हि प्रजानामि तव प्रवृत्तिम्।।11.31।।','ākhyāhi me ko bhavān ugra-rūpo
namo ’stu te deva-vara prasīda
vijñātum ichchhāmi bhavantam ādyaṁ
na hi prajānāmi tava pravṛittim',to_json('ākhyāhi—tell; me—me; kaḥ—who; bhavān—you; ugra-rūpaḥ—fierce form; namaḥ astu—I bow; te—to you; deva-vara—God of gods; prasīda—be merciful; vijñātum—to know; ichchhāmi—I wish; bhavantam—you; ādyam—the primeval; na—not; hi—because; prajānāmi—comprehend; tava—your; pravṛittim—workings'::text),'Tell me, who you are, so fierce of form. I offer my salutations to you, O God Supreme; have mercy on me. I desire to know you, the original Being. I do not indeed know your workings.','Swami Sivananda','11.31 आख्याहि tell? मे me? कः who (art)? भवान् Thou? उग्ररूपः fierce in form? नमः salutation? अस्तु be? ते to Thee? देववर O God Supreme? प्रसीद have mercy? विज्ञातुम् to know? इच्छामि (I) wish? भवन्तम् Thee? आद्यम् the original Being? न not? हि indeed? प्रजानामि (I) know? तव Thy? प्रवृत्तिम् doing.No Commentary.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bwmb000au7eu6fmf61a0',32,446,'11-32','श्री भगवानुवाच

कालोऽस्मि लोकक्षयकृत्प्रवृद्धो

लोकान्समाहर्तुमिह प्रवृत्तः।

ऋतेऽपि त्वां न भविष्यन्ति सर्वे

येऽवस्थिताः प्रत्यनीकेषु योधाः।।11.32।।','śhrī-bhagavān uvācha
kālo ’smi loka-kṣhaya-kṛit pravṛiddho
lokān samāhartum iha pravṛittaḥ
ṛite ’pi tvāṁ na bhaviṣhyanti sarve
ye ’vasthitāḥ pratyanīkeṣhu yodhāḥ',to_json('śhrī-bhagavān uvācha—the Supreme Lord said; kālaḥ—time; asmi—I am; loka-kṣhaya-kṛit—the source of destruction of the worlds; pravṛiddhaḥ—mighty; lokān—the worlds; samāhartum—annihilation; iha—this world; pravṛittaḥ—participation; ṛite—without; api—even; tvām—you; na bhaviṣhyanti—shall cease to exist; sarve—all; ye—who; avasthitāḥ—arrayed; prati-anīkeṣhu—in the opposing army; yodhāḥ—the warriors'::text),'The Blessed Lord said, "I am the full-grown, world-destroying Time, now engaged in destroying the worlds. Even without you, none of the warriors arrayed in the hostile armies will live."','Swami Sivananda','11.32 कालः time? अस्मि (I) am? लोकक्षयकृत् worlddestroying? प्रवृद्धः fullgrown? लोकान् the worlds? समाहर्तुम् to destroy? इह here? प्रवृत्तः engaged? ऋते without? अपि also? त्वाम् thee? न not? भविष्यन्ति shall live? सर्वे all? ये these? अवस्थिताः arrayed? प्रत्यनीकेषु in hostile armies? योधाः warriors.Commentary Even without thee Even if thou? O Arjuna? wouldst not fight? these warriors are doomed to die under My dispensation. I am the alldestroying Time. I have already slain them. You have seen them dying. Therefore thy instrumentality is not of much importance.Such being the case? therefore? stand up and obtain fame.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bwmb000au7eu6fmf61a0',33,447,'11-33','तस्मात्त्वमुत्तिष्ठ यशो लभस्व

जित्वा शत्रून् भुङ्क्ष्व राज्यं समृद्धम्।

मयैवैते निहताः पूर्वमेव

निमित्तमात्रं भव सव्यसाचिन्।।11.33।।','tasmāt tvam uttiṣhṭha yaśho labhasva
jitvā śhatrūn bhuṅkṣhva rājyaṁ samṛiddham
mayaivaite nihatāḥ pūrvam eva
nimitta-mātraṁ bhava savya-sāchin',to_json('tasmāt—therefore; tvam—you; uttiṣhṭha—arise; yaśhaḥ—honor; labhasva—attain; jitvā—conquer; śhatrūn—foes; bhuṅkṣhva—enjoy; rājyam—kingdom; samṛiddham—prosperous; mayā—by me; eva—indeed; ete—these; nihatāḥ—slain; pūrvam—already; eva nimitta-mātram—only an instrument; bhava—become; savya-sāchin—Arjun, the one who can shoot arrows with both hands'::text),'Therefore, stand up and obtain fame. Conquer the enemies and enjoy the unparalleled kingdom. Verily, by Me they have already been slain; be thou a mere instrument, O Arjuna.','Swami Sivananda','11.33 तस्मात् therefore? त्वम् thou? उत्तिष्ठ stand up? यशः fame? लभस्व obtain? जित्वा having conered? शत्रून् enemies? भुङ्क्ष्व enjoy? राज्यम् the kingdom? समृद्धम् the unrivalled? मया by Me? एव even? एते these? निहताः have been slain? पूर्वम् before? एव even? निमित्तमात्रम् a mere instrument? भव be? सव्यसाचिन् O ambidexterous one.Commentary Be thou merely an apparent or nominal cause. I have already killed them in advance. I have destroyed them long ago.Fame People will think that Bhishma? Drona and the other great warriors whom even the gods cannot kill have been defeated by you and so you will obtain great fame. Such fame is due to virtuous Karma only.Satrun Enemies such as Duryodhana.Savyasachi Arjuna who could shoot arrows even with the left hand.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bwmb000au7eu6fmf61a0',34,448,'11-34','द्रोणं च भीष्मं च जयद्रथं च

कर्णं तथाऽन्यानपि योधवीरान्।

मया हतांस्त्वं जहि मा व्यथिष्ठा

युध्यस्व जेतासि रणे सपत्नान्।।11.34।।','droṇaṁ cha bhīṣhmaṁ cha jayadrathaṁ cha
karṇaṁ tathānyān api yodha-vīrān
mayā hatāṁs tvaṁ jahi mā vyathiṣhṭhā
yudhyasva jetāsi raṇe sapatnān',to_json('droṇam—Dronacharya; cha—and; bhīṣhmam—Bheeshma; cha—and; jayadratham—Jayadratha; cha—and; karṇam—Karn; tathā—also; anyān—others; api—also; yodha-vīrān—brave warriors; mayā—by me; hatān—already killed; tvam—you; jahi—slay; mā—not; vyathiṣhṭhāḥ—be disturbed; yudhyasva—fight; jetā asi—you shall be victorious; raṇe—in battle; sapatnān—enemies'::text),'Drona, Bhishma, Jayadratha, Karna, and other brave warriors have already been slain by Me; do not be distressed with fear; fight and you shall conquer your enemies in battle.','Swami Sivananda','11.34 द्रोणम् Drona? च and? भीष्मम् Bhishma? च and? जयद्रथम् Jayadratha? च and? कर्णम् Karna? तथा also? अन्यान् others? अपि also? योधवीरान् brave warriors? मया by Me? हतान् slain? त्वम् thou? जहि do kill? मा not? व्यथिष्ठाः be distressed with fear? युध्यस्व fight? जेतासि shall coner? रणे in the battle? सपत्नान् the enemies.Commentary Already slain by Me Therefore? O Arjuna? you need not be afraid of incurring sin by killing them.Drona had celestial weapons. He was Arjunas teacher in the science of archery. He was Arjunas beloved and greatest Guru. Bhishma also possessed celetial weapons. He could die only if and when he wanted to die. He once faught singlehanded with Lord Parasurama and was not defeated. So powerful was he.The father of Jayadratha performed penance with a resolve the head of the man who may cause the head of my son to fall on the ground? shall also fall. During the war? however? Arjunas arrow cuts the head and drops it on the lap of the father who? inadvertently? makes it fall on the ground he too dies at once. Karna? the son of the Sungod? had obtained an unerring missile from Indra.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bwmb000au7eu6fmf61a0',35,449,'11-35','सञ्जय उवाच

एतच्छ्रुत्वा वचनं केशवस्य

कृताञ्जलिर्वेपमानः किरीटी।

नमस्कृत्वा भूय एवाह कृष्णं

सगद्गदं भीतभीतः प्रणम्य।।11.35।।','sañjaya uvācha
etach chhrutvā vachanaṁ keśhavasya
kṛitāñjalir vepamānaḥ kirīṭī
namaskṛitvā bhūya evāha kṛiṣhṇaṁ
sa-gadgadaṁ bhīta-bhītaḥ praṇamya',to_json('sañjayaḥ uvācha—Sanjay said; etat—thus; śhrutvā—hearing; vachanam—words; keśhavasya—of Shree Krishna; kṛita-añjaliḥ—with joined palms; vepamānaḥ—trembling; kirītī—the crowned one, Arjun; namaskṛitvā—with palms joined; bhūyaḥ—again; eva—indeed; āha—spoke; kṛiṣhṇam—to Shree Krishna; sa-gadgadam—in a faltering voice; bhīta-bhītaḥ—overwhelmed with fear; praṇamya—bowed down'::text),'Sanjaya said, Having heard that speech of Lord Krishna, Arjuna, with joined palms, trembling, prostrated himself, again addressing Krishna in a choked voice, bowing down, overwhelmed with fear.','Swami Sivananda','11.35 एतत् that? श्रुत्वा having heard? वचनम् speech? केशवस्य of Kesava? कृताञ्जलिः with joined palms? वेपमानः trembling? किरीटि Arjuna? नमस्कृत्वा prostrating (himself)? भूयः again? एव even? आह addressed? कृष्णम् to Krishna? सगद्गदम् in a choked voice? भीतभीतः overwhelmed with fear? प्रणम्य having prostrated.Commentary When anyone is in a state of extreme terror or joy he sheds tears on account of pain or exhilaration of spirits. Then his throat is choked and he stammers or speaks indistinctly or in a dull? choked voice. Arjuna was extremely frightened when he saw the Cosmic Form and so he spoke in a stammering tone.There is great significane in Sanjayas words. He thought that Dhritarashtra might come to terms or make peace with the Pandavas when he knew that his sons would certainly be killed for want of proper support when Drona and Karna would be killed by Arjuna. He hoped that conseently there would be peace and happiness to both the parties. But Dhritarashtra was obstinate he did not listen to this suggestion on account of the force of destiny.','Swami Sivananda',now(),now()),
(gen_random_uuid(),'cmpl2bwmb000au7eu6fmf61a0',36,450,'11-36','अर्जुन उवाच

स्थाने हृषीकेश तव प्रकीर्त्या

जगत् प्रहृष्यत्यनुरज्यते च।

रक्षांसि भीतानि दिशो द्रवन्ति

सर्वे नमस्यन्ति च सिद्धसङ्घाः।।11.36।।','arjuna uvācha
sthāne hṛiṣhīkeśha tava prakīrtyā
jagat prahṛiṣhyaty anurajyate cha
rakṣhānsi bhītāni diśho dravanti
sarve namasyanti cha siddha-saṅghāḥ',to_json('arjunaḥ uvācha—Arjun said; sthāne—it is but apt; hṛiṣhīka-īśha—Shree Krishna, the master of the senses; tava—your; prakīrtyā—in praise; jagat—the universe; prahṛiṣhyati—rejoices; anurajyate—be enamored; cha—and; rakṣhānsi—the demons; bhītāni—fearfully; diśhaḥ—in all directions; dravanti—flee; sarve—all; namasyanti—bow down; cha—and; siddha-saṅghāḥ—hosts of perfected saints'::text),'Arjuna said, "It is fitting, O Krishna, that the world delights and rejoices in Your praise; demons fly in fear in all directions and the hosts of the perfected ones bow to You."','Swami Sivananda','11.36 स्थाने it is meet? हृषीकेश O Krishna? तव Thy? प्रकीर्त्या by praise? जगत् the world? प्रहृष्यति is delighted? अनुरज्यते rejoices? च and? रक्षांसि the demons? भीतानि in fear? दिशः to all arters? द्रवन्ति fly? सर्वे all? नमस्यन्ति bow (to Thee)? च and? सिद्धसङ्घाः the hosts of the perfected ones.Commentary Praise description of the glory of the Lord. The Lord is the object worthy of adortion? love and delight? because He is the Self and friend of all beings.The Lord is the object of adoration? love and delight for the following reason also. He is the primal cause even of Brahma? the Creator of the universe.','Swami Sivananda',now(),now())
ON CONFLICT (slug) DO UPDATE SET
  sanskrit            = EXCLUDED.sanskrit,
  transliteration     = EXCLUDED.transliteration,
  "wordByWord"        = EXCLUDED."wordByWord",
  translation         = EXCLUDED.translation,
  "translationAuthor" = EXCLUDED."translationAuthor",
  commentary          = EXCLUDED.commentary,
  "commentaryAuthor"  = EXCLUDED."commentaryAuthor",
  "updatedAt"         = now();